- Gemfile.lock
> file changes

- _data/sidebars/marketplace_developer_sidebar.yml
- _data/sidebars/marketplace_user_sidebar.yml
- _templates/feature-integration-guide-template.md
- docs/marketplace/dev/glue-api-guides/glue-api-sample-page.md
- docs/marketplace/dev/glue-api-guides/retrieving-merchant-information.md
- docs/marketplace/dev/glue-api-guides/retrieving-product-offers.md
- docs/marketplace/user/features/merchant-users-feature-overview.md
- docs/marketplace/user/features/merchants-feature-overview.md
- docs/marketplace/user/features/product-offer-feature-overview.md
> Added sample pages and IG template

- .vscode/settings.json
- _templates/howto-guide-template.md
- _templates/module-migration-guide-template.md
> Adding HowTo and MG templates

- _data/sidebars/marketplace_developer_sidebar.yml
- _templates/howto-guide-template.md
- _templates/module-migration-guide-template.md
- docs/marketplace/dev/glue-api-guides/abstract-products/retrieving-abstract-products.md
- docs/marketplace/dev/glue-api-guides/carts-of-registered-users/managing-carts-of-registered-users.md
- docs/marketplace/dev/glue-api-guides/carts-of-registered-users/managing-items-in-carts-of-registered-users.md
- docs/marketplace/dev/glue-api-guides/catalog-search.md
- docs/marketplace/dev/glue-api-guides/concrete-products/retrieving-concrete-products.md
- docs/marketplace/dev/glue-api-guides/concrete-products/retrieving-product-offers-for-a-concrete-product.md
- docs/marketplace/dev/glue-api-guides/guest-carts/managing-guest-cart-items.md
- docs/marketplace/dev/glue-api-guides/guest-carts/managing-guest-carts.md
- docs/marketplace/dev/glue-api-guides/resolving-search-engine-friendly-urls.md
- docs/marketplace/dev/glue-api-guides/retrieving-marketplace-orders.md
- docs/marketplace/dev/glue-api-guides/retrieving-merchant-information.md
- docs/marketplace/dev/glue-api-guides/retrieving-product-offers.md
- docs/marketplace/dev/glue-api-guides/retrieving-suggestions-for-auto-completion-and-search.md
> Adding Glue API guides

- _data/sidebars/marketplace_developer_sidebar.yml
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-merchant-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-product-offer-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/merchants-feature-integration.md
Added:
-Marketplace Merchant feature integration
-Marketplace Product Offer feature integration
TBD
> publishing Marketplace IGs

- _data/sidebars/marketplace_developer_sidebar.yml
- docs/marketplace/dev/feature-integration-guides/glue/product-offer-cart-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/product-offer-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/merchant-category-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/merchant-portal-product-offer-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/product-offer-cart-feature-integration.md
> Added more IGs

- _data/sidebars/marketplace_developer_sidebar.yml
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-product-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-product-offer-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/product-offer-cart-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-inventory-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-marketplace-product-offer-feature-integration.md
> Adding igs

- _templates/feature-integration-guide-template.md
> IG template - v1

- _config.yml
> Change markdown renderer to default

- docs/marketplace/dev/feature-integration-guides/merchants-feature-integration.md
- docs/marketplace/dev/glue-api-guides/abstract-products/retrieving-abstract-products.md
- docs/marketplace/dev/glue-api-guides/carts-of-registered-users/managing-carts-of-registered-users.md
- docs/marketplace/dev/glue-api-guides/carts-of-registered-users/managing-items-in-carts-of-registered-users.md
- docs/marketplace/dev/glue-api-guides/catalog-search.md
- docs/marketplace/dev/glue-api-guides/concrete-products/retrieving-concrete-products.md
- docs/marketplace/dev/glue-api-guides/guest-carts/managing-guest-cart-items.md
- docs/marketplace/dev/glue-api-guides/guest-carts/managing-guest-carts.md
- docs/marketplace/dev/glue-api-guides/resolving-search-engine-friendly-urls.md
- docs/marketplace/dev/glue-api-guides/retrieving-marketplace-orders.md
- docs/marketplace/dev/glue-api-guides/retrieving-product-offers.md
- docs/marketplace/dev/glue-api-guides/retrieving-suggestions-for-auto-completion-and-search.md
> fixing dropdowns

- Gemfile.lock
> deleting unf_ext (0.0.7.7-x64-mingw32)

- _templates/feature-integration-guide-template.md
> Add meta, update verification

- _data/sidebars/marketplace_developer_sidebar.yml
- docs/marketplace/dev/feature-integration-guides/marketplace-return-management-feature-integration.md
> MP-4100: Add IG merchant order return.

- _templates/syntax-and-formatting-rules
> adding syntax and formatting rules

- _data/sidebars/marketplace_developer_sidebar.yml
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-inventory-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-product-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/merchant-category-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/merchant-opening-hours-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/product-offer-cart-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-inventory-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-inventory-management-order-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-inventory-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-marketplace-product-offer-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/merchant-category-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/product-offer-feature-integration.md
> Added IGs, fixed developer sidebar, fixed links in prerequisites

- _templates/feature-integration-guide-template.md
- docs/marketplace/dev/glue-api-guides/abstract-products/retrieving-abstract-products.md
- docs/marketplace/dev/glue-api-guides/concrete-products/retrieving-concrete-products.md
> Volume prices API 

- _data/sidebars/marketplace_developer_sidebar.yml
- docs/marketplace/dev/feature-integration-guides/marketplace-inventory-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-inventory-management-order-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-cart-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-inventory-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-marketplace-product-offer-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-return-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/merchant-category-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/merchant-portal-marketplace-product-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/merchant-portal-marketplace-product-tax-feature-integration.md
> Added new IGs, fixed typos, added verification blocks

- _data/sidebars/marketplace_developer_sidebar.yml
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-inventory-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-merchant-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-product-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-product-offer-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-product-offer-prices-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-return-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/merchant-category-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/merchant-opening-hours-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/offers-volume-prices.md
- docs/marketplace/dev/feature-integration-guides/glue/product-offer-cart-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-inventory-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-inventory-management-order-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-inventory-management-packaging-units-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-order-management-cart-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-order-management-customer-account-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-order-management-order-threshold-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-cart-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-promotions-discounts-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/merchant-portal-integration-guide.md
- docs/marketplace/dev/feature-integration-guides/merchant-portal-marketplace-merchant-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/merchant-switcher-feature-integration.md
> Integration guides

- _data/sidebars/marketplace_developer_sidebar.yml
> Adding IG to toc

- _templates/feature-integration-guide-template.md
- _templates/formatting-templates-for-feature-integration-guides.md
> Add formatting templates and update ES and Redis verification

- _data/sidebars/marketplace_developer_sidebar.yml
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-inventory-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-merchant-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-product-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-product-offer-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-product-offer-prices-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-return-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/merchant-category-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/merchant-opening-hours-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/offer-volume-prices.md
- docs/marketplace/dev/feature-integration-guides/glue/product-offer-cart-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-inventory-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-inventory-management-order-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-inventory-management-packaging-units-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-merchants-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-order-management-cart-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-order-management-customer-account-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-order-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-order-management-order-threshold-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-cart-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-inventory-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-marketplace-product-offer-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-offer-prices-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-promotions-discounts-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-shipment-cart-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-shipment-checkout-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-shipment-customer-feature-integration.md
- index.md
> Updating integration guides

- _data/sidebars/marketplace_developer_sidebar.yml
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-product-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-product-offer-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-inventory-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-marketplace-product-offer-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-shipment-feature-integration.md
> editing IGs, fixing mistakes, links, titles, and sidebar

- docs/marketplace/dev/feature-integration-guides/glue/marketplace-product-offer-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-return-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-return-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/merchant-portal-integration-guide.md
- docs/marketplace/dev/feature-integration-guides/merchant-portal-marketplace-merchant-feature-integration.md
> MerchantPortal: Marketplace Merchant Feature integration

- _data/sidebars/marketplace_developer_sidebar.yml
- docs/marketplace/dev/feature-integration-guides/merchant-portal-core-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/merchant-portal-marketplace-merchant-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/merchant-portal-marketplace-product-offer-feature-integration.md
> Merchant Portal - Marketplace Product Offer feature integration

- docs/marketplace/dev/feature-integration-guides/merchant-portal-marketplace-product-offer-feature-integration.md
> Merchant Portal - Marketplace Product Offer IG update

- _templates/feature-integration-guide-template.md
> Small fix for the IG template

- _data/sidebars/marketplace_developer_sidebar.yml
> fixed the sidebar

- docs/marketplace/dev/feature-integration-guides/glue/marketplace-inventory-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-merchant-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-product-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-product-offer-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-product-offer-prices-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/marketplace-return-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/merchant-category-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/merchant-opening-hours-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/glue/offer-volume-prices.md
- docs/marketplace/dev/feature-integration-guides/glue/product-offer-cart-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-inventory-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-inventory-management-order-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-inventory-management-packaging-units-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-merchants-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-order-management-cart-feature-integration.md
> Fixing IGs

- docs/marketplace/dev/feature-integration-guides/glue/marketplace-return-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-return-management-feature-integration.md
Ticket: https://spryker.atlassian.net/browse/MP-4104
> MP-4144: Back Office: Marketplace Returns feature integration guide

- docs/marketplace/dev/glue-api-guides/abstract-products/retrieving-abstract-products.md
- docs/marketplace/dev/glue-api-guides/concrete-products/retrieving-concrete-products.md
- docs/marketplace/dev/glue-api-guides/guest-carts/managing-guest-carts.md
- docs/marketplace/dev/glue-api-guides/retrieving-merchant-information.md
> editing-igs

- _data/sidebars/marketplace_developer_sidebar.yml
- _data/sidebars/marketplace_user_sidebar.yml
- docs/marketplace/dev/data-import/file-details-merchantcsv.md
- docs/marketplace/user/back-office-user-guides/merchants/managing-merchant-users.md
- docs/marketplace/user/back-office-user-guides/merchants/managing-merchants.md
- docs/marketplace/user/back-office-user-guides/merchants/merchants-reference-information.md
> adding-marketplace-guides

- _data/sidebars/marketplace_developer_sidebar.yml
- docs/marketplace/dev/data-import/file-details-merchant-profilecsv.md
- docs/marketplace/dev/data-import/file-details-merchantcsv.md
> adding-file-details

- _data/sidebars/marketplace_developer_sidebar.yml
- docs/marketplace/dev/data-import/file-details-merchant-usercsv.md
the File details - merchant_user.csv document is added
TBD
> added-import-file

- docs/marketplace/dev/glue-api-guides/catalog-search.md
- docs/marketplace/dev/glue-api-guides/guest-carts/managing-guest-cart-items.md
- docs/marketplace/dev/glue-api-guides/resolving-search-engine-friendly-urls.md
- docs/marketplace/dev/glue-api-guides/retrieving-marketplace-orders.md
- docs/marketplace/dev/glue-api-guides/retrieving-suggestions-for-auto-completion-and-search.md
- docs/marketplace/user/features/marketplace-and-merchant-state-machines/marketplace-and-merchant-state-machine-module-schema.md
- docs/marketplace/user/features/marketplace-and-merchant-state-machines/marketplace-and-merchant-state-machines-feature-overview.md
- docs/marketplace/user/features/marketplace-and-merchant-state-machines/marketplace-and-merchant-state-machines-interaction.md
- docs/marketplace/user/features/marketplace-order/marketplace-order-feature-overview.md
- docs/marketplace/user/features/marketplace-order/marketplace-order-module-relations.md
- docs/marketplace/user/features/merchant-order/merchant-order-feature-overview.md
- docs/marketplace/user/features/merchant-order/merchant-order-module-relations.md
- docs/marketplace/user/features/merchants/merchant-users-feature-overview.md
- docs/marketplace/user/features/merchants/merchants-feature-overview.md
- docs/marketplace/user/features/products-and-offers/product-offer-feature-overview.md
- docs/marketplace/user/intro-to-spryker/marketplace-concept.md
> Updated the front matter

- _data/sidebars/marketplace_user_sidebar.yml
- _templates/info-blocks/error.md
- _templates/info-blocks/info.md
- _templates/info-blocks/verification.md
- _templates/info-blocks/warning.md
- docs/marketplace/dev/feature-integration-guides/marketplace-inventory-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-inventory-management-order-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-inventory-management-packaging-units-feature-integration.md
- docs/marketplace/user/back-office-user-guides/catalog/availability/availability-reference-information.md
- docs/marketplace/user/back-office-user-guides/catalog/products/abstract-product-reference-information.md
- docs/marketplace/user/back-office-user-guides/catalog/products/products-reference-information.md
- docs/marketplace/user/back-office-user-guides/marketplace/merchants/managing-merchant-users.md
- docs/marketplace/user/back-office-user-guides/marketplace/merchants/managing-merchants.md
- docs/marketplace/user/back-office-user-guides/marketplace/merchants/merchants-reference-information.md
- index.md
> fixing-guides

- _includes/topnav.html
- _layouts/home.html
In scope of https://spryker.atlassian.net/browse/TE-8779
> TE-8779: Add valid links to homepage

- docs/marketplace/dev/feature-integration-guides/marketplace-inventory-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-inventory-management-packaging-units-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-merchants-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-order-management-cart-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-order-management-customer-account-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-order-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-order-management-order-threshold-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-cart-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/marketplace-product-feature-integration.md
> fixing Verification and editing IGs

- _templates/feature-integration-guide-template.md
Add a template for data import description table
> add data import table

- docs/marketplace/dev/feature-integration-guides/202106.0/marketplace-order-management-customer-account-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/marketplace-order-management-order-threshold-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/marketplace-product-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/marketplace-product-offer-prices-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/merchant-opening-hours-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/merchant-portal-marketplace-merchant-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/merchant-portal-marketplace-product-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/merchant-portal-marketplace-product-offer-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/merchant-portal-marketplace-product-tax-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/merchant-portal-product-offer-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/merchant-switcher-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/product-offer-cart-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/product-offer-feature-integration.md
> Edited IG guides

- _data/sidebars/marketplace_dev_sidebar.yml
- docs/marketplace/dev/feature-integration-guides/202106.0/glue/marketplace-inventory-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/glue/marketplace-merchants-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/glue/marketplace-product-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/glue/marketplace-product-offer-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/glue/marketplace-product-offer-prices-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/glue/marketplace-product-offer-wishlist-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/glue/marketplace-return-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/glue/merchant-category-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/glue/merchant-opening-hours-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/glue/offer-volume-prices.md
- docs/marketplace/dev/feature-integration-guides/202106.0/glue/product-offer-cart-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/marketplace-inventory-management-feature-integration.md
> edited-glue-igs

- _data/sidebars/marketplace_dev_sidebar.yml
- docs/marketplace/dev/glue-api-guides/202106.0/abstract-products/retrieving-abstract-products.md
- docs/marketplace/dev/glue-api-guides/202106.0/carts-of-registered-users/managing-carts-of-registered-users.md
- docs/marketplace/dev/glue-api-guides/202106.0/carts-of-registered-users/managing-items-in-carts-of-registered-users.md
- docs/marketplace/dev/glue-api-guides/202106.0/catalog-search.md
- docs/marketplace/dev/glue-api-guides/202106.0/concrete-products/retrieving-concrete-products.md
- docs/marketplace/dev/glue-api-guides/202106.0/concrete-products/retrieving-product-offers-for-a-concrete-product.md
- docs/marketplace/dev/glue-api-guides/202106.0/guest-carts/managing-guest-cart-items.md
- docs/marketplace/dev/glue-api-guides/202106.0/guest-carts/managing-guest-carts.md
- docs/marketplace/dev/glue-api-guides/202106.0/resolving-search-engine-friendly-urls.md
> Reviewing glue guides

- docs/marketplace/dev/glue-api-guides/202106.0/carts-of-registered-users/managing-carts-of-registered-users.md
- docs/marketplace/dev/glue-api-guides/202106.0/catalog-search.md
- docs/marketplace/dev/glue-api-guides/202106.0/concrete-products/retrieving-product-offers-for-a-concrete-product.md
- docs/marketplace/dev/glue-api-guides/202106.0/resolving-search-engine-friendly-urls.md
- docs/marketplace/dev/glue-api-guides/202106.0/retrieving-marketplace-orders.md
- docs/marketplace/dev/glue-api-guides/202106.0/retrieving-merchant-information.md
- docs/marketplace/dev/glue-api-guides/202106.0/retrieving-product-offers.md
- docs/marketplace/dev/glue-api-guides/202106.0/retrieving-suggestions-for-auto-completion-and-search.md
> fixed guest carts

- docs/marketplace/user/back-office-user-guides/202106.0/catalog/availability/availability-reference-information.md
- docs/marketplace/user/back-office-user-guides/202106.0/marketplace/merchants/managing-merchant-users.md
- docs/marketplace/user/back-office-user-guides/202106.0/marketplace/merchants/managing-merchants.md
- docs/marketplace/user/back-office-user-guides/202106.0/marketplace/merchants/merchants-reference-information.md
- docs/marketplace/user/back-office-user-guides/202106.0/marketplace/offers/offers.md
> reviewed-bo-guides

- _plugins/algolia_hooks.rb
- _plugins/canonical_url.rb
- _plugins/page_versions.rb
* Improved versions sorting
* Fixed issues with `canonical_url.rb` plugin
* Added version-related optimization for Algolia indexing
> TE-9211 Adjusted the logic for choosing latest page version

- docs/marketplace/dev/data-import/file-details-merchant-profilecsv.md
- docs/marketplace/dev/data-import/file-details-merchant-usercsv.md
- docs/marketplace/dev/data-import/file-details-merchantcsv.md
> Update of the import files to fit the template

- docs/marketplace/dev/data-import/file-details-merchant-profilecsv.md
- docs/marketplace/dev/data-import/file-details-merchant-usercsv.md
- docs/marketplace/dev/data-import/file-details-merchantcsv.md
> updates of the import files

- _layouts/home.html
> adjusting wording on the homepage

- docs/marketplace/dev/data-import/file-details-merchant-profilecsv.md
- docs/marketplace/dev/data-import/file-details-merchant-usercsv.md
> ups to import file commands

- _data/sidebars/marketplace_dev_sidebar.yml
- docs/marketplace/dev/front-end/migration-guide-extending-the-project.md
- docs/marketplace/dev/front-end/table-design/table-actions-extension.md
- docs/marketplace/dev/front-end/table-design/table-column-type-extension.md
- docs/marketplace/dev/front-end/table-design/table-feature-extension.md
- docs/marketplace/dev/front-end/table-design/table-filter-extension.md
- docs/marketplace/dev/front-end/ui-components-library/cache.md
- docs/marketplace/dev/front-end/ui-components-library/data-transformers.md
- docs/marketplace/dev/front-end/ui-components-library/datasources.md
- docs/marketplace/dev/front-end/ui-components-library/persistence.md
> @gibmirmilch Migration guide - Extending the project, Table Actions extension

- docs/marketplace/dev/feature-integration-guides/202106.0/glue/offer-volume-prices.md
- docs/marketplace/dev/feature-integration-guides/202106.0/marketplace-promotions-discounts-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/merchant-portal-marketplace-merchant-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202106.0/merchant-switcher-feature-integration.md
- docs/marketplace/user/back-office-user-guides/202106.0/catalog/products/abstract-product-reference-information.md
- docs/marketplace/user/features/202106.0/marketplace-and-merchant-state-machines/marketplace-and-merchant-state-machines-feature-overview.md
- docs/marketplace/user/features/202106.0/marketplace-and-merchant-state-machines/marketplace-and-merchant-state-machines-interaction.md
- docs/marketplace/user/features/202106.0/marketplace-order/marketplace-order-feature-overview.md
- docs/marketplace/user/features/202106.0/merchants/merchant-users-feature-overview.md
- docs/marketplace/user/features/202106.0/merchants/merchants-feature-overview.md
- docs/marketplace/user/features/202106.0/products-and-offers/product-offer-feature-overview.md
- docs/marketplace/user/merchant-portal-user-guides/202106.0/dashboard/managing-merchants-performance-data.md
> fixing-documents

- _includes/sidebar_item.html
- css/_variables.scss
- css/components/_anchor-nav.scss
- css/components/_code.scss
- css/components/_info-block.scss
- css/components/_sidebar-nav.scss
- css/pages/_content.scss
- js/customscripts.js
> Update nav accordeon

- _data/sidebars/marketplace_dev_sidebar.yml
- docs/marketplace/dev/front-end/project-structure.md
- docs/marketplace/dev/front-end/table-design/table-actions-extension.md
- docs/marketplace/dev/front-end/table-design/table-column-type-extension.md
- docs/marketplace/dev/front-end/table-design/table-feature-extension.md
- docs/marketplace/dev/front-end/table-design/table-filter-extension.md
- docs/marketplace/dev/front-end/ui-components-library/cache.md
- docs/marketplace/dev/front-end/ui-components-library/data-transformers/array-map.md
- docs/marketplace/dev/front-end/ui-components-library/data-transformers/chain.md
- docs/marketplace/dev/front-end/ui-components-library/data-transformers/index.md
- docs/marketplace/dev/front-end/ui-components-library/data-transformers/lens.md
- docs/marketplace/dev/front-end/ui-components-library/data-transformers/object-map.md
- docs/marketplace/dev/front-end/ui-components-library/data-transformers/pluck.md
- docs/marketplace/dev/front-end/ui-components-library/datasources.md
- docs/marketplace/dev/front-end/ui-components-library/persistence.md
Ticket: https://spryker.atlassian.net/browse/MP-5116
> MP-5116  Data Transformer Chain

- _data/sidebars/marketplace_dev_sidebar.yml
- docs/marketplace/dev/front-end/ui-components-library/data-transformers/date-parse.md
- docs/marketplace/dev/front-end/ui-components-library/data-transformers/index.md
Ticket: https://spryker.atlassian.net/browse/MP-5117
> MP-5117 Data Transformer Date-parse

- css/pages/_content.scss
> fix scss var

- _data/sidebars/marketplace_user_sidebar.yml
- docs/marketplace/user/features/202106.0/marketplace-merchant/marketplace-merchant.md
- docs/marketplace/user/merchant-portal-user-guides/202106.0/login-and-logout/managing-login-and-logout.md
- docs/marketplace/user/merchant-portal-user-guides/202106.0/my-account/managing-account-details-and-settings.md
> Login and logout

- _data/sidebars/marketplace_dev_sidebar.yml
- docs/marketplace/dev/glue-api-guides/202106.0/carts-of-registered-users/managing-carts-of-registered-users.md
- docs/marketplace/dev/glue-api-guides/202106.0/managing-the-returns.md
- docs/marketplace/dev/glue-api-guides/202106.0/retrieving-marketplace-orders.md
> added-managing-the-returns-doc

- _templates/feature-integration-guide-template.md
Since Glue APIs are not features, we need to update the wording and column names in integration guides. This PR updates the integration guide template to reflect the changes.
> Resolve the feature/Glue API conflict

- docs/marketplace/user/merchant-portal-user-guides/202106.0/logging-in-to-the-merchant-portal.md
> [BO-294] Merchant Portal: Forgot password (WIP)

- docs/marketplace/dev/glue-api-guides/202106.0/retrieving-product-offers.md
- docs/marketplace/user/features/202106.0/marketplace-product-offer.md
> api link fix

- _data/sidebars/marketplace_user_sidebar.yml
- docs/marketplace/user/features/202106.0/marketplace-product-offer.md
- docs/marketplace/user/merchant-portal-user-guides/202106.0/offers/managing-product-offers.md
> Merchant Portal - Managing product offers

- _includes/toc.html
- _layouts/default.html
- _layouts/page.html
- css/_layout.scss
- css/base/_utils.scss
- css/components/_anchor-nav.scss
- css/components/_main-sidebar.scss
- css/components/_toc.scss
- css/pages/_content.scss
- js/customscripts.js
https://trello.com/c/sbXJjae7/56-toc-tablet-and-desktop
https://trello.com/c/YGCjEk1w/66-only-one-title-in-toc-should-be-highligted
https://trello.com/c/OMwEKWGq/70-long-words-titles-are-stretched-outside-of-the-content-area
https://trello.com/c/g9y797m1/62-upon-the-first-click-on-a-title-in-the-table-of-contents-the-red-bar-does-not-appear
TBD
> Responsive toc

- _data/sidebars/marketplace_user_sidebar.yml
- docs/marketplace/user/back-office-user-guides/202106.0/sales/managing-main-merchant-orders.md
> Managing main merchant orders

- _data/sidebars/marketplace_user_sidebar.yml
- docs/marketplace/user/intro-to-spryker/marketplace-personas.md
> Marketplace Personas

- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-promotions-and-discounts-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-wishlist-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/merchant-category-feature-walkthrough.md
- docs/marketplace/user/merchant-portal-user-guides/202108.0/index.md
>   Updates of tables in the feature walkthroughs

- _plugins/liquid/sidebar.rb
- Fixed the sidebar for category items with index pages
> Fixed sidebar

- .travis.yml
- Gemfile
- Gemfile.lock
- _config.yml
- _config_production.yml
- _includes/sidebar.html
- _layouts/page.html
- _plugins/liquid/sidebar.rb
- _plugins/page_versions.rb
- redirect.html
- Added new scopes for `SCOS` product
- Refactored and optimised sidebar, got rid of `include` to increase performance
- Added sidebar data for `scos/user` and `scos/dev` realms
- Installed `liquid-c` and `jekyll-include-cache` for performance reasons
- Added separate config for production environment and adjusted `.travis.yml` accordingly
> Scos migration infrastructure

- _templates/back-office-user-guide-template.md
- _templates/data-export-template.md
- _templates/data-import-template.md
- _templates/glue-api-storefront-guide-template.md
- _templates/howto-guide-template.md
- _templates/module-migration-guide-template.md
> adjust templates

- _data/sidebars/marketplace_user_sidebar.yml
- docs/marketplace/user/back-office-user-guides/202108.0/sales/managing-main-merchant-returns.md
- docs/marketplace/user/back-office-user-guides/202108.0/sales/managing-marketplace-returns.md
- docs/marketplace/user/features/202108.0/marketplace-return-management-feature-overview.md
> Marketplace return management

- .travis.yml
- _config.yml
- _layouts/page.html
* Added github.com and glue example links to error page validator ignore list.
* Introduced related page functionality.
> Adjusted htmlproofer ignore list

- _layouts/home.html
> Fixing a typo

- docs/marketplace/dev/setup/system-requirements.md
> System requirements

- docs/scos/dev/migration-and-integration/202108.0/feature-integration-guides/order-management-feature-integration.md
- docs/scos/dev/migration-and-integration/202108.0/feature-integration-guides/packaging-units-feature-integration.md
* Publish an updated order management IG
* Update the packaging units IG
> Add order management IG

- _data/sidebars/marketplace_user_sidebar.yml
- docs/marketplace/user/features/202108.0/marketplace-product-feature-overview.md
- docs/marketplace/user/release-notes/release-notes-2021080.md
> Add TE for MP RN

- Rakefile
- _config.yml
- _includes/head.html
- robots.txt
> Release preparation

- docs/scos/dev/technology-partners/202108.0/operational-tools-monitoring-legal-etc/new-relic.md
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-7611
- RG: https://release.spryker.com/release-groups/view/3791
> SC-7611: NewRelic: bad transaction name by default

- _data/sidebars/cloud_dev_sidebar.yml
- _includes/topnav.html
- _layouts/home.html
- docs/cloud/dev/spryker-cloud-commerce-os/getting-started-with-the-spryker-cloud-commerce-os.md
> adjusting the toc

- _data/sidebars/cloud_dev_sidebar.yml
- docs/cloud/dev/spryker-cloud-commerce-os/access/locating-service-credentials.md
- docs/cloud/dev/spryker-cloud-commerce-os/customizing-aws-cloudwatch-dashboards.md
- docs/cloud/dev/spryker-cloud-commerce-os/setting-up-a-custom-domain-name/setting-up-a-custom-domain-name-with-route-53.md
- docs/cloud/dev/spryker-cloud-commerce-os/setting-up-a-custom-domain-name/setting-up-a-custom-domain-name.md
- docs/cloud/dev/spryker-cloud-commerce-os/working-with-logs.md
> fixing formatting

- .github/workflows/ci.yml
> Cache and cron enablement

- _data/sidebars/marketplace_dev_sidebar.yml
- docs/marketplace/dev/feature-integration-guides/202108.0/acl-feature-integration.md
> Acl update

- docs/marketplace/dev/feature-integration-guides/202108.0/marketplace-order-management-cart-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202108.0/marketplace-order-management-customer-account-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202108.0/marketplace-order-management-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202108.0/marketplace-order-management-order-threshold-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202108.0/marketplace-product-offer-cart-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202108.0/marketplace-product-offer-checkout-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202108.0/marketplace-product-offer-prices-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202108.0/marketplace-promotions-discounts-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202108.0/marketplace-shipment-cart-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202108.0/marketplace-shipment-checkout-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202108.0/marketplace-shipment-customer-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202108.0/marketplace-shipment-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202108.0/merchant-opening-hours-feature-integration.md
- docs/marketplace/dev/feature-integration-guides/202108.0/merchant-switcher-feature-integration.md
- docs/marketplace/dev/setup/system-requirements.md
> updated versions for the IGs

- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-cart-notes-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-inventory-management-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-merchant-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-merchant-portal-product-offer-management-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-order-management-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-product-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-product-offer-feature-walkthrough/marketplace-product-offer-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-product-offer-prices-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-product-options-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-promotions-and-discounts-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-return-management-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-shipment-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-wishlist-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/merchant-category-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/merchant-opening-hours-feature-walkthrough.md
> Updated feature walkthroughs pages

- docs/scos/user/intro-to-spryker/whats-new/security-audit-reports/2019.11-security-audit-by-sektioneins.md
- docs/scos/user/intro-to-spryker/whats-new/security-audit-reports/2020.11-penetration-test-by-port-zero-executive-summary.md
> renaming the articles

- js/customscripts.js
> fix scroll bug on iphone

- _data/sidebars/marketplace_dev_sidebar.yml
- docs/marketplace/dev/front-end/ui-components-library/actions/actions-http.md
Ticket: https://spryker.atlassian.net/browse/MP-5862
> MP-5862 Actions HTTP

- _data/sidebars/marketplace_dev_sidebar.yml
- docs/marketplace/dev/front-end/ui-components-library/actions/actions-http.md
- docs/marketplace/dev/front-end/ui-components-library/actions/actions-notification.md
- docs/marketplace/dev/front-end/ui-components-library/actions/actions-redirect.md
- docs/marketplace/dev/front-end/ui-components-library/actions/actions-refresh-table.md
Ticket: https://spryker.atlassian.net/browse/MP-5863
> MP-5863 Actions Notification

- docs/scos/dev/feature-walkthroughs/201811.0/refunds-feature-walkthrough/reference-information-refund-module.md
- docs/scos/dev/feature-walkthroughs/201811.0/shipment-feature-walkthrough/reference-information-shipment-method-plugins.md
- docs/scos/dev/feature-walkthroughs/201903.0/refunds-feature-walkthrough/reference-information-refund-module.md
- docs/scos/dev/feature-walkthroughs/201903.0/shipment-feature-walkthrough/reference-information-shipment-method-plugins.md
- docs/scos/dev/feature-walkthroughs/201907.0/quotation-process-feature-walkthrough/quotation-process-module-relations.md
- docs/scos/dev/feature-walkthroughs/201907.0/refunds-feature-walkthrough/reference-information-refund-module.md
- docs/scos/dev/feature-walkthroughs/201907.0/shipment-feature-walkthrough/reference-information-shipment-method-plugins.md
- docs/scos/dev/feature-walkthroughs/202001.0/quotation-process-feature-walkthrough/quotation-process-module-relations.md
- docs/scos/dev/feature-walkthroughs/202001.0/shipment-feature-walkthrough/reference-information-shipment-method-plugins.md
- docs/scos/dev/feature-walkthroughs/202005.0/quotation-process-feature-walkthrough/quotation-process-module-relations.md
- docs/scos/dev/feature-walkthroughs/202005.0/shipment-feature-walkthrough/reference-information-shipment-method-entities-in-the-database.md
- docs/scos/dev/feature-walkthroughs/202005.0/shipment-feature-walkthrough/reference-information-shipment-method-plugins.md
- docs/scos/dev/feature-walkthroughs/202009.0/shipment-feature-walkthrough/reference-information-shipment-method-plugins.md
> fixing the build issues

- docs/scos/dev/feature-walkthroughs/201811.0/tax-feature-walkthrough/tax-feature-walkthrough.md
- docs/scos/dev/feature-walkthroughs/201903.0/tax-feature-walkthrough/tax-feature-walkthrough.md
- docs/scos/dev/feature-walkthroughs/201907.0/tax-feature-walkthrough/tax-feature-walkthrough.md
- docs/scos/dev/feature-walkthroughs/202001.0/tax-feature-walkthrough/tax-feature-walkthrough.md
- docs/scos/dev/feature-walkthroughs/202005.0/tax-feature-walkthrough/tax-feature-walkthrough.md
- docs/scos/user/features/201811.0/tax-feature-overview.md
- docs/scos/user/features/201903.0/tax-feature-overview.md
- docs/scos/user/features/201907.0/tax-feature-overview.md
- docs/scos/user/features/202001.0/tax-feature-overview.md
- docs/scos/user/features/202005.0/tax-feature-overview.md
> tax overview and walkthrough updates

- docs/scos/user/intro-to-spryker/whats-new/supported-versions-of-php.md
> Supported versions of php

- docs/scos/user/technology-partners/202108.0/payment-partners/adyen/adyen-provided-payment-methods.md
> Adyen docs update

- docs/scos/dev/data-import/202108.0/data-import-categories/catalog-setup/products/file-details-product-abstract.csv.md
- docs/scos/dev/data-import/202108.0/data-import-categories/commerce-setup/file-details-currency.csv.md
- docs/scos/dev/data-import/202108.0/data-import-categories/commerce-setup/file-details-glossary.csv.md
- docs/scos/dev/data-import/202108.0/data-import-categories/commerce-setup/file-details-shipment.csv.md
- docs/scos/dev/data-import/202108.0/data-import-categories/commerce-setup/file-details-warehouse-address.csv.md
- docs/scos/dev/data-import/202108.0/data-import-categories/special-product-types/product-options/file-details-product-option.csv.md
- docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-cms.md
> Te 9354 fix 404 for version 202108.0

- _data/sidebars/cloud_dev_sidebar.yml
- docs/cloud/dev/spryker-cloud-commerce-os/deploying-in-a-production-environment.md
- docs/cloud/dev/spryker-cloud-commerce-os/deploying-in-a-staging-environment.md
- docs/cloud/dev/spryker-cloud-commerce-os/environments-overview.md
- docs/cloud/dev/spryker-cloud-commerce-os/getting-started-with-the-spryker-cloud-commerce-os.md
> adding the page

- _data/sidebars/marketplace_dev_sidebar.yml
- docs/marketplace/dev/front-end/ui-components-library/cache.md
- docs/marketplace/dev/front-end/ui-components-library/persistence/in-memory-persistence-strategy.md
- docs/marketplace/dev/front-end/ui-components-library/persistence/index.md
Ticket: https://spryker.atlassian.net/browse/MP-5142
> MP-5142 Persistence InMemoryPersistenceStrategy

- _data/sidebars/marketplace_dev_sidebar.yml
- docs/marketplace/dev/front-end/ui-components-library/persistence/index.md
- docs/marketplace/dev/front-end/ui-components-library/persistence/local-storage-persistence-strategy.md
Ticket: https://spryker.atlassian.net/browse/MP-5143
> MP-5143 Persistence LocalStoragePersistenceStrategy

- _data/sidebars/marketplace_dev_sidebar.yml
- docs/marketplace/dev/front-end/ui-components-library/persistence/index.md
- docs/marketplace/dev/front-end/ui-components-library/persistence/url-persistence-strategy.md
Ticket: https://spryker.atlassian.net/browse/MP-5144
> MP-5144 Persistence UrlPersistenceStrategy

- _data/sidebars/cloud_dev_sidebar.yml
- docs/cloud/dev/spryker-cloud-commerce-os/performance-testing.md
> adding the performance testing doc

- docs/scos/user/features/201903.0/product-rating-and-reviews-feature-overview.md
> Update video links

- _data/sidebars/cloud_dev_sidebar.yml
- docs/cloud/dev/spryker-cloud-commerce-os/monitoring-issues-and-informing-about-alerts.md
- docs/marketplace/user/features/202108.0/marketplace-order-management-feature-overview/marketplace-and-merchant-state-machines-overview/marketplace-and-merchant-state-machines-interaction.md
> adding a doc

- docs/scos/dev/glue-api-guides/202108.0/managing-carts/carts-of-registered-users/managing-items-in-carts-of-registered-users.md
- docs/scos/dev/glue-api-guides/202108.0/managing-products/retrieving-bundled-products.md
- docs/scos/dev/glue-api-guides/202108.0/managing-products/retrieving-configurable-bundle-templates.md
- docs/scos/user/intro-to-spryker/b2c-suite.md
- docs/scos/user/intro-to-spryker/releases/archive/2017/release-notes-december-2017.md
- docs/scos/user/intro-to-spryker/releases/archive/2017/release-notes-october-1-2017.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202001.0/release-notes-202001.0.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202009.0/release-notes-202009.0.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202108.0/release-notes-202108.0.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-code-releases-may-2020/release-notes-code-releases-may-2020.md
- docs/scos/user/intro-to-spryker/releases/releases.md
- docs/scos/user/intro-to-spryker/support/business-impact-and-case-priorities.md
- docs/scos/user/intro-to-spryker/support/how-to-use-the-support-portal.md
- docs/scos/user/intro-to-spryker/support/understand-slas.md
- docs/scos/user/intro-to-spryker/whats-new/documentation-updates.md
> fixing the links

- _data/sidebars/scos_user_sidebar.yml
- _includes/footer.html
- docs/scos/user/intro-to-spryker/overview-of-features.md
> adding the previous capabilities page

- docs/marketplace/dev/feature-walkthroughs/202108.0/merchant-category-feature-walkthrough.md
Walkthrough Guide for Merchant Category feature.
> MP-5723: added walkthrough guide for merchant category

- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-merchant-feature-walkthrough.md
Added a Walkthrough guide for Marketplace Merchant feature.
> MP-5711: Walkthrough guide for Marketplace Merchant feature

- docs/scos/dev/developer-getting-started-guide.md
- docs/scos/user/intro-to-spryker/overview-of-features.md
> adding links

- _data/sidebars/scos_dev_sidebar.yml
- docs/scos/dev/architecture/modules-and-layers.md
- docs/scos/dev/back-end-development/data-manipulation/data-publishing/handling-data-with-publish-and-synchronization.md
- docs/scos/dev/back-end-development/zed-ui-tables/creating-and-configuring-zed-tables.md
- docs/scos/dev/data-import/202108.0/demo-shop-data-import/importing-demo-shop-data.md
- docs/scos/dev/developer-getting-started-guide.md
- docs/scos/dev/front-end-development/yves/atomic-frontend/atomic-front-end-general-overview.md
- docs/scos/dev/front-end-development/yves/atomic-frontend/customizing-spryker-front-end.md
- docs/scos/dev/module-migration-guides/202108.0/migration-guide-categorystorage.md
- docs/scos/dev/module-migration-guides/202108.0/migration-guide-productcategoryfiltergui.md
- docs/scos/dev/setup/installing-spryker-with-docker/docker-installation-prerequisites/installing-docker-prerequisites-on-linux.md
- docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-macos-and-linux.md
- docs/scos/dev/tutorials-and-howtos/howtos/howto-set-up-multiple-stores.md
> Adding redirects for links in safari

- docs/scos/dev/feature-walkthroughs/201811.0/spryker-core-back-office-feature-walkthrough/user-and-rights-overview.md
- docs/scos/dev/feature-walkthroughs/201903.0/spryker-core-back-office-feature-walkthrough/user-and-rights-overview.md
- docs/scos/dev/feature-walkthroughs/201907.0/spryker-core-back-office-feature-walkthrough/user-and-rights-overview.md
- docs/scos/dev/feature-walkthroughs/202001.0/spryker-core-back-office-feature-walkthrough/user-and-rights-overview.md
- docs/scos/dev/feature-walkthroughs/202005.0/spryker-core-back-office-feature-walkthrough/user-and-rights-overview.md
- docs/scos/dev/feature-walkthroughs/202009.0/spryker-core-back-office-feature-walkthrough/user-and-rights-overview.md
- docs/scos/dev/feature-walkthroughs/202108.0/spryker-core-back-office-feature-walkthrough/user-and-rights-overview.md
- docs/scos/dev/the-docker-sdk/202108.0/configuring-debugging-in-docker.md
> adding redirects

- docs/scos/dev/back-end-development/cronjobs/adding-and-configuring-cronjobs.md
- FIxed the deprecated console command to the correct one.
> Fix the outdated console command

- docs/scos/dev/back-end-development/cronjobs/adding-and-configuring-cronjobs.md
> fixing a command

- docs/scos/user/intro-to-spryker/releases/releases.md
To release-history on https://api.release.spryker.com/release-history
> Add release history link

- docs/scos/dev/the-docker-sdk/202108.0/deploy-file-reference-1.0.md
> Fixing typo

- docs/scos/dev/data-import/202108.0/data-import-categories/catalog-setup/products/file-details-product-abstract.csv.md
- docs/scos/dev/data-import/202108.0/data-import-categories/commerce-setup/file-details-shipment.csv.md
- docs/scos/dev/data-import/202108.0/data-import-categories/commerce-setup/file-details-warehouse-address.csv.md
- docs/scos/dev/data-import/202108.0/data-import-categories/special-product-types/product-options/file-details-product-option.csv.md
> fixing paths

- _data/sidebars/scos_dev_sidebar.yml
- docs/scos/dev/technical-enhancement-integration-guides/integrating-mariadb-database-engine.md
- docs/scos/dev/the-docker-sdk/201907.0/configuring-debugging-in-docker.md
- docs/scos/dev/the-docker-sdk/202001.0/configuring-debugging-in-docker.md
- docs/scos/dev/the-docker-sdk/202108.0/configuring-services.md
> Adding a note about why mariadb is the preferred db

- docs/scos/dev/tutorials-and-howtos/howtos/howto-set-up-multiple-stores.md
Publish howto-set-up-multiple-stores.md
> Publish howto-set-up-multiple-stores.md

- docs/scos/dev/guidelines/making-your-spryker-shop-secure.md
> Add missing instructions on securing GLUE API.

- docs/marketplace/user/intro-to-the-spryker-marketplace/marketplace-concept.md
> added video about the Marketplace

- docs/scos/user/intro-to-spryker/contributing-to-documentation/reviewing-pull-requests.md
> Adding a file on how to review PRs

- README.md
> Adding the readme file

- docs/scos/dev/glue-api-guides/202001.0/retrieving-discounts.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-2018.11.0/release-notes-2018.11.0.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-201903.0/release-notes-201903.0.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-201907.0/release-notes-201907.0.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202001.0/release-notes-202001.0.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202009.0/release-notes-202009.0.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202108.0/release-notes-202108.0.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-code-releases-may-2020/release-notes-code-releases-may-2020.md
> Updating release notes

- docs/scos/dev/upgradability-services/customization-tiers.md
- docs/scos/dev/upgradability-services/evaluation-tool-overview.md
- docs/scos/dev/upgradability-services/running-the-evaluation-tool.md
- docs/scos/dev/upgradability-services/running-the-upgrader-tool.md
- docs/scos/dev/upgradability-services/upgradability-reference.md
- docs/scos/dev/upgradability-services/upgradability-services.md
- docs/scos/dev/upgradability-services/upgrader-tool-overview.md
Add upgradability services drafts
> Upgradability services drafts

- docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-windows.md
Update b2b demo shop URL for git install
> Update b2b demo shop url in installation steps

- docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-macos-and-linux.md
> Update installation guide

- _data/sidebars/marketplace_user_sidebar.yml
- docs/marketplace/user/intro-to-the-spryker-marketplace/upcoming-major-module-releases.md
- docs/scos/user/intro-to-spryker/whats-new/upcoming-major-module-releases.md
> Add mp-upcoming-major-module-releases

- docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/howto-make-a-product-searchable-and-shown-on-the-storefront.md
- docs/scos/dev/tutorials-and-howtos/howtos/howto-add-a-new-shipment-method-2.0.md
- docs/scos/dev/tutorials-and-howtos/howtos/howto-add-a-new-shipment-method.md
- docs/scos/dev/tutorials-and-howtos/howtos/howto-build-your-own-product-relation-type.md
- docs/scos/dev/tutorials-and-howtos/howtos/howto-change-the-default-behavior-of-event-triggering-in-the-availabilitystorage-module.md
- docs/scos/dev/tutorials-and-howtos/howtos/howto-create-and-register-a-mail-provider.md
- docs/scos/dev/tutorials-and-howtos/howtos/howto-create-and-register-a-mailtypeplugin.md
- docs/scos/dev/tutorials-and-howtos/howtos/howto-create-personalized-prices.md
- docs/scos/dev/tutorials-and-howtos/howtos/howto-customize-http-headers-in-ajax-request.md
- docs/scos/dev/tutorials-and-howtos/howtos/howto-force-https.md
- docs/scos/dev/tutorials-and-howtos/howtos/howto-handle-case-sensitive-file-system-on-mac-os.md
- docs/scos/dev/tutorials-and-howtos/howtos/howto-install-spryker-in-aws-environment.md
- docs/scos/dev/tutorials-and-howtos/howtos/howto-product-data-from-import-to-front-end-view.md
- docs/scos/dev/tutorials-and-howtos/howtos/howto-replace-spryker-module-dependencies.md
- docs/scos/dev/tutorials-and-howtos/howtos/howto-set-up-database-connections.md
- docs/scos/dev/tutorials-and-howtos/howtos/howto-set-up-spryker-with-mysql.md
- docs/scos/dev/tutorials-and-howtos/howtos/howto-set-up-stores-with-multiple-locales.md
- docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-architectural-walkthrough-spryker-commerce-os.md
- docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-checkout-and-step-engine-spryker-commerce-os.md
- docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-cms.md
- docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-content-and-search-personalized-catalog-pages-spryker-commerce-os.md
- docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-different-sores-different-logic-landing-pages-spryker-commerce-os.md
- docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-handling-new-types-of-entity-urls-legacy-demoshop.md
- docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-hello-world-spryker-commerce-os.md
- docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-integrating-any-search-engine-into-a-project.md
- docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-testing-and-tdd-spryker-commerce-os.md
- docs/scos/dev/tutorials-and-howtos/tutorials-and-howtos.md
[TBD](https://spryker.atlassian.net/browse/TE-10320)
> Updating the redirect links

- docs/scos/dev/architecture/architecture-performance.md
This article explains the bad and best architecture practices which can affect the performance of applications in our very end servers.
> Ehsanmx patch 1

- Rakefile
- _includes/footer.html
> adding the social network links

- docs/scos/user/back-office-user-guides/202200.0/merchandising/discount/creating-cart-rules.md
- docs/scos/user/back-office-user-guides/202200.0/merchandising/discount/creating-vouchers.md
- docs/scos/user/back-office-user-guides/202200.0/merchandising/discount/managing-discounts.md
- docs/scos/user/features/202200.0/promotions-discounts-feature-overview.md
> Adding the discount docs to the upcoming version

- docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-windows.md
We found an issue with hostnames per line limit on one of Windows machines. See problem description here: https://superuser.com/questions/932112/is-there-a-maximum-number-of-hostname-aliases-per-line-in-a-windows-hosts-file
> Add note about Windows hostnames limit per line

- docs/scos/dev/back-end-development/data-manipulation/payment-methods/direct-debit-example-implementation/implementation-of-direct-debit-in-zed.md
Update documentation on how to implement direct debit into zed. Code examples were outdated.
> Update direct debit checkout plugins

- docs/scos/user/features/202108.0/product-labels-feature-overview.md
> Fixed typo- dynamic-product-labels

- docs/scos/user/features/202108.0/product-labels-feature-overview.md
> Fixed typo

- Rakefile
> adding a link to ignore

- .github/workflows/ci.yml
- Rakefile
> Aop ci check

- docs/scos/user/back-office-user-guides/202108.0/merchandising/search-and-filters/managing-filter-preferences.md
- docs/scos/user/features/202108.0/search-feature-overview/search-feature-overview.md
> updating docs on search and filter

- docs/scos/dev/architecture/modules-and-layers.md
> Typo in Documentation

- docs/scos/dev/guidelines/coding-guidelines/code-style-guide.md
> Adding date and time explanation

- _data/sidebars/marketplace_dev_sidebar.yml
- _data/sidebars/scos_dev_sidebar.yml
- docs/marketplace/dev/architecture-overview/marketplace-application-composition.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-merchant-portal-core-feature-walkthrough/persistence-acl-configuration.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/persistence-acl-feature-walkthrough/persistence-acl-feature-walkthrough.md
- docs/marketplace/dev/setup/infrastructure-requirements.md
- docs/scos/dev/setup/installing-spryker-with-vagrant/b2b-or-b2c-demo-shop-installation-mac-os-or-linux-with-development-virtual-machine.md
- docs/scos/dev/setup/installing-spryker-with-vagrant/b2b-or-b2c-demo-shop-installation-windows-with-development-virtual-machine.md
- docs/scos/dev/troubleshooting/troubleshooting-general-technical-issues/troubleshooting-general-technical-issues.md
> Adjusting the Marketplace guides

- docs/scos/user/intro-to-spryker/support/how-to-use-the-support-portal.md
replaced hosting change request with platform change request and removed incorrect link to escalation
TBD
> Updated wording and link

- _layouts/page.html
- js/customscripts.js
https://spryker.atlassian.net/browse/TE-10398
> TE-10397: Short feedback

- docs/marketplace/dev/architecture-overview/marketplace-domain-model.md
- docs/marketplace/dev/setup/installation.md
> MP installation guide fixes

- _data/sidebars/scos_dev_sidebar.yml
- docs/scos/dev/back-end-development/data-manipulation/datapayload-conversion/state-machine/common-pitfalls-in-oms-design.md
> Common pitfalls in OMS design

- _data/sidebars/scos_dev_sidebar.yml
- docs/scos/dev/guidelines/testing-guidelines/testing-console-commands.md
Added basic information about how to add console comman tests.
> Added basic console command test description.

- docs/scos/dev/back-end-development/data-manipulation/data-interaction/search/configuring-the-search-query.md
> Fix Typo in "search query configuration" docu

- docs/scos/dev/guidelines/performance-guidelines/architecture-performance-guidelines.md
Adding information about batch processing for data import and triggering events
TBD
> Add bulk event processing paragraph

- docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/data-imports/how-to-manage-business-unit-specific-prices-via-data-import.md
> Adding a related article

- docs/scos/dev/glue-api-guides/202108.0/glue-infrastructure.md
> contributor-erop patch 5

- README.md
- docs/scos/dev/analyzing-and-upgrading-your-project-with-spryker-jarvis.md
> Link to video

- docs/scos/dev/analyzing-and-upgrading-your-project-with-spryker-jarvis.md
- docs/scos/dev/setup/installing-spryker-with-development-virtual-machine/configuring-debugging-in-devvm/configuring-debugging-in-devvm.md
- docs/scos/dev/setup/installing-spryker-with-development-virtual-machine/configuring-spryker-with-devvm/configuring-spryker-after-installing-with-devvm.md
> fix-hashes

- docs/scos/dev/analyzing-and-upgrading-your-project-with-spryker-jarvis.md
- docs/scos/dev/setup/installing-spryker-with-development-virtual-machine/configuring-debugging-in-devvm/configuring-debugging-in-devvm.md
- docs/scos/dev/setup/installing-spryker-with-development-virtual-machine/configuring-spryker-with-devvm/configuring-spryker-after-installing-with-devvm.md
- docs/scos/user/technology-partners/202108.0/payment-partners/crefopay.md
- docs/scos/user/technology-partners/202108.0/payment-partners/heidelpay.md
- docs/scos/user/technology-partners/202108.0/payment-partners/klarna.md
> Te 9652/related dev guides 2

- docs/scos/dev/setup/installing-spryker-with-docker/docker-installation-prerequisites/installing-docker-prerequisites-on-linux.md
- docs/scos/dev/setup/installing-spryker-with-docker/docker-installation-prerequisites/installing-docker-prerequisites-on-macos.md
- docs/scos/dev/setup/installing-spryker-with-docker/docker-installation-prerequisites/installing-docker-prerequisites-on-windows-with-wsl1.md
- docs/scos/dev/setup/installing-spryker-with-docker/docker-installation-prerequisites/installing-docker-prerequisites-on-windows-with-wsl2.md
> urgent-typos

- docs/scos/dev/setup/installing-spryker-with-docker/database-access-credentials.md
Would be nice to show directly in the docs how one could connect to the database from `docker/sdk cli`
> Provide example how to connect to database

- docs/scos/dev/feature-integration-guides/202108.0/spryker-core-feature-integration.md
- docs/scos/dev/setup/setup.md
- docs/scos/dev/troubleshooting/troubleshooting.md
> Added redirects

- docs/cloud/dev/spryker-cloud-commerce-os/configuring-deployment-pipelines/deployment-pipelines.md
- docs/scos/dev/updating-a-spryker-based-project.md
> Remove excessive \

- Rakefile
> ignoring an external link

- docs/scos/dev/technology-partner-guides/202108.0/payment-partners/adyen/integrating-adyen-payment-methods.md
- docs/scos/dev/technology-partner-guides/202108.0/payment-partners/adyen/integrating-adyen.md
> Adding the payment method docs

- docs/scos/user/features/202108.0/refunds-feature-overview.md
> contributor-patch-1

- docs/scos/user/features/202108.0/refunds-feature-overview.md
> grammar corrected

- docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
> added performance related tips to the article

- docs/marketplace/dev/front-end/extending-the-project/migration-guide-upgrade-to-angular-v12.md
Ticket: https://spryker.atlassian.net/browse/MP-6085
> MP-6085 AC Migration Guide fixes

- docs/scos/dev/technology-partner-guides/202108.0/product-information-pimerp/akeneo/installing-and-configuring-akeneo.md
> fixed a broken link

- docs/aop/dev/aop-security-assessment.md
> Added info blocks

- _config.yml
- docs/aop/user/apps/bazzarvoice.md
- docs/aop/user/apps/payone.md
https://spryker.atlassian.net/browse/APPS-2513
> Payone docs

- _data/sidebars/scos_dev_sidebar.yml
> Moving the query containers sections

- docs/scos/dev/back-end-development/data-manipulation/data-publishing/handling-data-with-publish-and-synchronization.md
- docs/scos/dev/back-end-development/data-manipulation/data-publishing/implementing-publish-and-synchronization.md
- docs/scos/dev/back-end-development/data-manipulation/event/adding-events.md
- docs/scos/dev/back-end-development/data-manipulation/event/configuring-an-events-queue.md
- docs/scos/dev/back-end-development/data-manipulation/event/listening-to-events.md
Updated P&S guides with our latest conventions.
> P&S update

- .github/workflows/ci.yml
> Added deployment CI job 

- _data/sidebars/marketplace_dev_sidebar.yml
- _data/sidebars/scos_dev_sidebar.yml
- docs/marketplace/dev/glue-api-guides/202204.0/rest-api-reference.md
> Schema files

- _layouts/page.html
- css/components/_main-sidebar.scss
- css/pages/_content.scss
https://trello.com/c/5yzxs9yT/101-broken-styles
https://trello.com/c/fEDxe9GX/109-remove-double-heading-in-left-sidebar
TBD
> fix sidebar, swagger styles

- _data/sidebars/marketplace_user_sidebar.yml
- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-cart-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202204.0/marketplace-cart-feature-walkthrough.md
- docs/marketplace/user/features/202108.0/marketplace-cart-feature-overview.md
- docs/marketplace/user/features/202204.0/marketplace-cart-feature-overview.md
- docs/marketplace/user/intro-to-spryker-marketplace/marketplace-b2b-demo-shop.md
- docs/marketplace/user/intro-to-spryker-marketplace/marketplace-b2c-demo-shop.md
- Added Marketplace B2B Demo Shop page
- Added Marketplace B2C Demo Shop page
- Renamed Marketplace Cart Notes feature overview into Marketplace Cart feature overview + updated the links and set the redirects
> Marketplace b2b b2c demo shops pages

- docs/scos/dev/developer-getting-started-guide.md
> Update getting start guide

- _data/sidebars/marketplace_dev_sidebar.yml
- docs/marketplace/dev/technical-enhancement/migration-guide-upgrade-to-angular-v12.md
> Updated the location of the Angular doc

- docs/scos/dev/back-end-development/cronjobs/adding-and-configuring-cronjobs.md
As per this task https://spryker.atlassian.net/browse/SC-8237 the parameter are not used at all (double checked with Sylvain).
TBD
> fix: removed unused parameter

- docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-demo-mode-on-macos-and-linux.md
- docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-demo-mode-on-windows.md
- docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-macos-and-linux.md
- docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-windows.md
Updated installation guides to use the latest demoshop patch.
> Update installation guides

- docs/marketplace/dev/feature-integration-guides/202204.0/marketplace-shopping-lists-feature-integration.md
- docs/marketplace/dev/feature-walkthroughs/202204.0/marketplace-merchant-custom-prices-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202204.0/marketplace-product-approval-process-feature-walkthrough.md
- docs/marketplace/dev/glue-api-guides/202204.0/shopping-lists/managing-shopping-list-items.md
- docs/marketplace/user/back-office-user-guides/202204.0/catalog/products/managing-products/managing-products.md
- docs/marketplace/user/features/202204.0/marketplace-merchant-portal-product-offer-management-feature-overview.md
- docs/marketplace/user/features/202204.0/marketplace-product-approval-process-feature-overview.md
- docs/marketplace/user/features/202204.0/marketplace-shopping-list-feature-overview.md
- docs/marketplace/user/intro-to-spryker-marketplace/marketplace-b2b-demo-shop.md
- docs/marketplace/user/intro-to-spryker-marketplace/release-notes/release-notes-2022040.md
> Adding links for marketplace 

- docs/acp/user/apps/bazaarvoice.md
- docs/acp/user/apps/payone.md
- docs/acp/user/apps/usercentrics.md
- docs/acp/user/intro-to-acp/acp-overview.md
> Adding redirects for aop

- docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-demo-mode-on-macos-and-linux.md
- docs/scos/dev/the-docker-sdk/202204.0/configuring-debugging-in-docker.md
Punctuation fixes
- [ x ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md
> [AC-1364] Punctuation fixes

- docs/marketplace/user/features/202204.0/marketplace-order-management-feature-overview/marketplace-and-merchant-state-machines-overview/marketplace-and-merchant-state-machines-overview.md
- docs/marketplace/user/features/202204.0/marketplace-product-feature-overview.md
> Updated Marketplace and merchant state machines overview

- docs/scos/dev/glue-api-guides/202204.0/managing-customers/managing-customers.md
Updated the Customer RequestBody by including the gender parameter.
TBD
> Included gender parameter in Customer RequestBody

- .github/workflows/ci.yml
- _config.yml
- algolia_config/_acp_user.yml
- algolia_config/_cloud_dev.yml
- algolia_config/_fes_dev.yml
- algolia_config/_marketplace_dev.yml
- algolia_config/_marketplace_user.yml
- algolia_config/_paas_plus_dev.yml
- algolia_config/_scos_dev.yml
> Adding search configuration for acp

- .github/workflows/ci.yml
- algolia_config/_acp_user.yml
> Adding algolia configs

- docs/scos/dev/feature-integration-guides/201903.0/glue-api/glue-api-wishlist-feature-integration.md
- docs/scos/dev/feature-integration-guides/201903.0/product-relations-feature-integration.md
- docs/scos/dev/feature-integration-guides/202204.0/glue-api/glue-api-wishlist-feature-integration.md
- docs/scos/dev/feature-walkthroughs/202108.0/merchant-b2b-contracts-feature-walkthrough.md
- docs/scos/dev/feature-walkthroughs/202204.0/merchant-b2b-contracts-feature-walkthrough.md
- docs/scos/dev/glue-api-guides/202005.0/managing-products/retrieving-and-applying-product-options.md
- docs/scos/dev/glue-api-guides/202204.0/managing-b2b-account/retrieving-companies.md
- docs/scos/user/features/201811.0/cms-feature-overview/cms-page-drafts-and-previews.md
- docs/scos/user/features/201907.0/cms-feature-overview/cms-page-drafts-and-previews.md
- docs/scos/user/features/202005.0/cms-feature-overview/cms-page-drafts-and-previews.md
- docs/scos/user/features/202005.0/product-rating-and-reviews-feature-overview.md
Task: https://spryker.atlassian.net/browse/AC-1354
> [AC-1354]-fix-404s

- _data/sidebars/scos_user_sidebar.yml
- docs/scos/user/intro-to-spryker/whats-new/ie11-end-of-life.md
Add deprecation information about IE11 https://docs.google.com/document/d/19h0UGIgXgmPWRQqsHmEC0_IZeF37tdxwIC7corMne3Y/edit?usp=sharing
> Add page about ie11 deprecation

- docs/scos/dev/back-end-development/yves/yves-routes.md
> Replace console with correct binary

- docs/cloud/dev/spryker-cloud-commerce-os/troubleshooting/troubleshooting-general-issues/missing-migration-files-on-production-environments.md
Updated the info block + solution
TBD
> Updated the info block + solution

- _data/sidebars/scos_user_sidebar.yml
- docs/scos/dev/module-migration-guides/migration-guide-sharedcartpage.md
- docs/scos/dev/setup/installing-spryker-with-docker/docker-installation-prerequisites/installing-docker-prerequisites-on-macos.md
- docs/scos/user/back-office-user-guides/202108.0/administration/thresholds/managing-threshold-settings.md
- docs/scos/user/features/202204.0/cms-feature-overview/cms-feature-overview.md
> Issues fix

- algolia_config/_pbc_all_roles.yml
> fixing the search

- algolia_config/_acp_user.yml
> Search fix

- algolia_config/_acp_user.yml
- algolia_config/_pbc_all_roles.yml
> excluding unnecessary file from search

- algolia_config/_paas_plus_dev.yml
- algolia_config/_pbc_all_roles.yml
> search path fix

- css/pages/_content.scss
Implement this requirement https://spryker.aha.io/features/DOC-19
> Define 80% as minimum for image width

- docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-demo-mode-on-windows.md
> Updates endpoints

- Rakefile
- docs/pbc/all/payment-service-providers/unzer/domain-model-and-relationships.md
- docs/pbc/all/payment-service-providers/unzer/howto-tips-use-cases/refund-shipping-costs.md
- docs/scos/dev/feature-integration-guides/202204.0/glue-api/glue-api-shared-carts-feature-integration.md
- docs/scos/dev/feature-integration-guides/202204.0/uuid-generation-console-feature-integration.md
- docs/scos/dev/technology-partner-guides/202108.0/operational-tools-monitoring-legal-etc/new-relic/installing-and-configuring-new-relic–with–vagrant.md
https://spryker.atlassian.net/browse/AC-1389
> Fixing links

- docs/pbc/all/payment-service-providers/unzer/unzer.md
> fixed broken link

- _data/sidebars/marketplace_dev_sidebar.yml
- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-merchant-portal-core-feature-walkthrough/gui-modules-concept.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-merchant-portal-core-feature-walkthrough/marketplace-merchant-portal-core-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-merchant-portal-core-feature-walkthrough/merchant-user-concept.md
- docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-merchant-portal-core-feature-walkthrough/persistence-acl-configuration.md
- docs/marketplace/dev/feature-walkthroughs/202204.0/marketplace-merchant-portal-core-feature-walkthrough/gui-modules-concept.md
- docs/marketplace/dev/feature-walkthroughs/202204.0/marketplace-merchant-portal-core-feature-walkthrough/marketplace-merchant-portal-core-feature-walkthrough.md
- docs/marketplace/dev/feature-walkthroughs/202204.0/marketplace-merchant-portal-core-feature-walkthrough/merchant-user-concept.md
- docs/marketplace/dev/feature-walkthroughs/202204.0/marketplace-merchant-portal-core-feature-walkthrough/persistence-acl-configuration.md
- docs/marketplace/dev/howtos/how-to-extend-merchant-portal-dashboard.md
- docs/marketplace/dev/setup/infrastructure-requirements.md
- docs/marketplace/user/features/202108.0/marketplace-order-management-feature-overview/marketplace-and-merchant-state-machines-overview/marketplace-and-merchant-state-machines-interaction.md
- docs/marketplace/user/features/202204.0/marketplace-order-management-feature-overview/marketplace-and-merchant-state-machines-overview/marketplace-and-merchant-state-machines-interaction.md
- docs/marketplace/user/intro-to-spryker-marketplace/release-notes/release-notes-2021080.md
- docs/scos/user/intro-to-spryker/about-spryker-documentation.md
> Updates to marketplace namings

- _data/sidebars/scos_dev_sidebar.yml
- docs/scos/dev/data-export/202005.0/data-export.md
- docs/scos/dev/glue-api-guides/202204.0/managing-customers/managing-customer-addresses.md
- docs/scos/dev/sdk/data-import.md
- docs/scos/dev/sdk/development-tools/phpstan.md
- docs/scos/dev/sdk/development-tools/tooling-config-file.md
- docs/scos/dev/the-docker-sdk/202108.0/deploy-file/deploy-file-reference-1.0.md
- docs/scos/dev/the-docker-sdk/202204.0/configuring-a-mount-mode.md
> Fix MD/YAML syntax errors in scos_dev_sidebar.yml and some documents

- docs/scos/dev/front-end-development/migration-guide-switch-from-yarn-to-npm.md
Ticket: https://spryker.atlassian.net/browse/CC-18569
> СС-18569 Fix docs - Switch from Yarn to NPM

- docs/scos/dev/tutorials-and-howtos/howtos/howto-do-better-deployments.md
@ThomasLehnerSpryker original PR: https://github.com/spryker/spryker-docs/pull/1129
TBD
> HowTo: Do better deployments

- docs/scos/dev/back-end-development/client/client.md
Original PR: https://github.com/spryker/spryker-docs/pull/1132
TBD
> Contributor-pr

- docs/scos/dev/tutorials-and-howtos/howtos/howto-debug-payment-integrations-locally.md
Guide to show users how they can easily debug payment provider integrations with the help of NGROK
TBD
> HowTo: Debug Payment Integrations Locally

- docs/scos/dev/tutorials-and-howtos/introduction-tutorials/glue-api/validating-rest-request-format.md
Ticket: https://spryker.atlassian.net/browse/SUPESC-392
> SUPESC-392 Added warning for store specific generate validation cache command.

- _data/sidebars/scos_dev_sidebar.yml
- docs/scos/dev/feature-walkthroughs/202204.0/cart-feature-walkthrough/calculation-3-0.md
- docs/scos/dev/feature-walkthroughs/202204.0/cart-feature-walkthrough/calculation-data-structure.md
- docs/scos/dev/feature-walkthroughs/202204.0/cart-feature-walkthrough/calculator-plugins.md
- docs/scos/dev/feature-walkthroughs/202204.0/cart-feature-walkthrough/cart-module-reference-information.md
- docs/scos/dev/feature-walkthroughs/202204.0/cms-feature-walkthrough/cms-extension-points-reference-information.md
- docs/scos/dev/feature-walkthroughs/202204.0/company-account-feature-walkthrough/company-account-feature-walkthrough.md
- docs/scos/dev/feature-walkthroughs/202204.0/company-account-feature-walkthrough/company-account-module-relations.md
- docs/scos/dev/feature-walkthroughs/202204.0/company-account-feature-walkthrough/customer-login-by-token-reference-information.md
- docs/scos/dev/feature-walkthroughs/202204.0/configurable-product-feature-walkthrough/configuration-process-flow-of-configurable-product.md
- docs/scos/dev/feature-walkthroughs/202204.0/content-items-feature-walkthrough/content-item-types-module-relations.md
- docs/scos/dev/feature-walkthroughs/202204.0/customer-account-management-feature-walkthrough/customer-module-overview-reference-information.md
- docs/scos/dev/feature-walkthroughs/202204.0/inventory-management-feature-walkthrough/inventory-management-feature-walkthrough.md
- docs/scos/dev/feature-walkthroughs/202204.0/inventory-management-feature-walkthrough/managing-stocks-in-a-multi-store-environment-best-practices.md
- docs/scos/dev/feature-walkthroughs/202204.0/measurement-units-feature-walkthrough.md
- docs/scos/dev/feature-walkthroughs/202204.0/merchant-product-restrictions-feature-walkthrough/restricted-products-behavior.md
- docs/scos/dev/feature-walkthroughs/202204.0/navigation-feature-walkthrough/navigation-module-reference-information.md
- docs/scos/dev/feature-walkthroughs/202204.0/order-management-feature-walkthrough/sales-module-reference-information.md
- docs/scos/dev/feature-walkthroughs/202204.0/prices-feature-walkthrough/money-module-reference-information.md
- docs/scos/dev/feature-walkthroughs/202204.0/prices-feature-walkthrough/priceproduct-module-details-reference-information.md
- docs/scos/dev/feature-walkthroughs/202204.0/product-feature-walkthrough.md
- docs/scos/dev/feature-walkthroughs/202204.0/resource-sharing-feature-walkthrough.md
- docs/scos/dev/feature-walkthroughs/202204.0/search-feature-walkthrough.md
- docs/scos/dev/feature-walkthroughs/202204.0/shipment-feature-walkthrough/shipment-feature-walkthrough.md
- docs/scos/dev/feature-walkthroughs/202204.0/shipment-feature-walkthrough/shipment-method-plugins-reference-information.md
- docs/scos/dev/feature-walkthroughs/202204.0/spryker-core-back-office-feature-walkthrough/spryker-core-back-office-feature-walkthrough.md
Following #1096, updating language and grammar on feature walkthrough pages.
> Updating DOC-I-9 feature articles with better language.

- _data/sidebars/pbc_all_sidebar.yml
- docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue-api.md
- docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue.md
- Epic: https://spryker.atlassian.net/browse/CC-16934
- Ticket for IG: https://spryker.atlassian.net/browse/CC-16965
> CC-16934 Glue support for Unzer IG.

- docs/pbc/all/payment-service-providers/unzer/configuration-in-the-back-office/add-unzer-marketplace-credentials.md
- docs/pbc/all/payment-service-providers/unzer/configuration-in-the-back-office/add-unzer-standard-credentails.md
- docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer.md
Ticket: https://spryker.atlassian.net/browse/SUPESC-621
> SUPESC-621 Updated Unzer IG.

- docs/scos/dev/technology-partner-guides/202204.0/payment-partners/heidelpay/integrating-heidelpay.md
Ticket: https://spryker.atlassian.net/browse/SUPESC-400
> SUPESC-400 Updated Heideplay IG to show payment forms.

- docs/scos/dev/data-import/202204.0/data-import-categories/about-data-import-categories.md
It adds a verb that was missing to one of the sentences of the spryker documentation.
> add missing verb to the sentence

- docs/scos/dev/data-import/202005.0/creating-a-data-importer.md
- docs/scos/dev/data-import/202009.0/creating-a-data-importer.md
- docs/scos/dev/data-import/202108.0/creating-a-data-importer.md
- docs/scos/dev/data-import/202204.0/creating-a-data-importer.md
Code example in creating-a-data-importer.md file contains typo
> Update creating-a-data-importer.md file. Fix typo in code example

- docs/scos/dev/back-end-development/data-manipulation/data-ingestion/spryker-middleware.md
https://github.com/spryker/spryker-docs/pull/1190
TBD
> Contributor 2

- algolia_config/_paas_plus_dev.yml
- algolia_config/_pbc_all.yml
> Fixing the algolia config

- docs/scos/dev/back-end-development/zed-ui-tables/creating-and-configuring-zed-tables.md
> Wrong headlines and streamlining text

- _data/sidebars/sdk_dev_sidebar.yml
> Updating the sidebar with sdk docs

- docs/cloud/dev/spryker-cloud-commerce-os/configure-deployment-pipelines/customizing-deployment-pipelines.md
> Include warning about lengthy operations during deploy

- docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer.md
Original PR: https://github.com/spryker/spryker-docs/pull/1213
TBD
> Contributor: Remove Payone

- docs/pbc/all/payment-service-providers/unzer/extend-and-customize/implement-new-payment-methods-on-the-project-level.md
Original PR: https://github.com/spryker/spryker-docs/pull/1212
TBD
> Contributor: Wrong file name

- docs/pbc/all/payment-service-providers/unzer/extend-and-customize/implement-new-payment-methods-on-the-project-level.md
PRs https://github.com/spryker/spryker-docs/pull/1212, https://github.com/spryker/spryker-docs/pull/1212, and https://github.com/spryker/spryker-docs/pull/1215 will be merged within this one
TBD
> Contributor: Fixing doc blocks and casing

- docs/pbc/all/payment-service-providers/unzer/extend-and-customize/implement-new-payment-methods-on-the-project-level.md
> Wrong file name

- docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer.md
> Remove Payone

- docs/pbc/all/payment-service-providers/unzer/extend-and-customize/implement-new-payment-methods-on-the-project-level.md
Code sniffer alerted some wrong doc blocks and a miss cased method call
TBD
> Fixing doc blocks and casing

- _data/sidebars/scos_dev_sidebar.yml
- docs/pbc/all/pbc.md
- docs/scos/dev/guidelines/making-your-spryker-shop-secure.md
- docs/scos/dev/guidelines/security-guidelines.md
Added information about PaaS to security guidelines
Cleaned up the doc
> Label security guidelines

- _includes/pbc/all/glue-api-guides/retrieve-a-concrete-product-response-attributes.md
> Updating glue api guides with missing attributes

- _data/sidebars/scos_dev_sidebar.yml
- _layouts/home.html
- docs/scos/dev/setup/quick-installation-guides/quick-installation-guide-macos-and-linux.md
- docs/scos/dev/setup/quick-installation-guides/quick-installation-guide-windows.md
- docs/scos/dev/setup/quick-installation-guides/quick-installation-guides.md
> Quick installation guides

- docs/marketplace/dev/feature-integration-guides/202204.0/marketplace-merchant-feature-integration.md
This pull request 
See https://docs.spryker.com/docs/marketplace/dev/feature-integration-guides/202204.0/marketplace-merchant-feature-integration.html:
> Fix: Reference

- css/components/_search-drop.scss
- js/customscripts.js
https://trello.com/c/Z1imlGlK/110-make-the-search-results-form-scrollable
TBD
> add scrollbar to search drop

- docs/pbc/all/usercentrics/usercentrics.md
> fixing a link

- docs/pbc/all/payment-service-providers/unzer/configuration-in-the-back-office/add-unzer-marketplace-credentials.md
- docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue-api.md
> Fixed doc from Customer request.

- _data/sidebars/scos_dev_sidebar.yml
- docs/scos/dev/data-export/202204.0/data-export-orders-.csv-files-format.md
- docs/scos/dev/data-export/202204.0/data-export.md
- docs/scos/dev/data-export/202204.0/index.md
Added a landing page for the `docs/scos/dev/data-export/` section
Request: https://spryker.slack.com/archives/C3KMWM1UZ/p1663611589100459
TBD
> Landing page for /scos/dev/data export section

- docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
attached related document link
TBD
> Add link to performance tips

- docs/scos/dev/data-export/202005.0/index.md
- docs/scos/dev/data-export/202009.0/index.md
- docs/scos/dev/data-export/202108.0/index.md
- docs/scos/dev/feature-integration-guides/202204.0/prices-per-merchant-relation-feature-integration.md
- docs/scos/user/features/202108.0/measurement-units-feature-overview.md
> added changes requests in #documentation channel

- _data/sidebars/scos_dev_sidebar.yml
- docs/scos/dev/feature-integration-guides/202204.0/glue-api/glue-backend-api/authorization-scopes-integration.md
- docs/scos/dev/feature-integration-guides/202204.0/glue-api/glue-backend-api/glue-authentication-integration.md
- docs/scos/dev/feature-integration-guides/202204.0/glue-api/glue-backend-api/glue-json-api-convention-integration.md
- docs/scos/dev/feature-integration-guides/202204.0/glue-api/glue-backend-api/glue-storefront-and-backend-api-applications-integration.md
- docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/authorization-scopes.md
- docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/create-a-relationship.md
- docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/create-a-resource-with-parent.md
- docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/create-a-resource.md
- docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/create-a-route.md
- docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/create-api-application.md
- docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/create-backend-vs-storefront-api-endpoint.md
- docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/create-protected-endpoints.md
- docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/create_change-convention.md
- docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/documenting-glue-api-endpoints.md
- docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/glue-parameters-usage.md
- docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/using-authorization-framework.md
Adding new glue infrastructure documentation
> Glue infrastructure docs

- docs/scos/dev/front-end-development/yves/front-end-builder-for-yves.md
- Adjusts naming convention for extending class
- Fixes missing empty space
Adjusts naming convention for extending class
> Adjusts naming convention for extending class

- docs/scos/dev/back-end-development/extending-spryker/development-strategies/project-modules/adding-a-new-module.md
> Add missing interface definition

- _data/sidebars/scos_dev_sidebar.yml
Added missing docs to the dev sidebar. 
TBD
> added missing docs to sidebar

- _config.yml
> Adding more nodes to search by Algolia

- _config.yml
> reverting the algolia fix

- docs/scos/dev/back-end-development/data-manipulation/data-ingestion/spryker-middleware.md
Original contributor PR: https://github.com/spryker/spryker-docs/pull/1304
TBD
> contributor: `bosvaldas: patch-1`

- docs/scos/dev/guidelines/testing-guidelines/setting-up-tests.md
Original contributor PR: https://github.com/spryker/spryker-docs/pull/1303/files
TBD
> contributor: `jreller:patch-2`

- _data/sidebars/scos_dev_sidebar.yml
- docs/scos/dev/tutorials-and-howtos/howtos/glue-api-howtos/howto-integrate-a-ciam-provider.md
Created a how-to guide for a CIAM provider integration
> how-to guide for a CIAM provider integration

- docs/scos/dev/back-end-development/data-manipulation/data-ingestion/spryker-middleware.md
> fixed typo in spryker-middleware.md

- _data/sidebars/scos_dev_sidebar.yml
- docs/scos/dev/feature-integration-guides/202204.0/glue-api/glue-backend-api/glue-api-authorization-protected-endpoints-integration.md
- docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-create-grant-type-parameters.md
- docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-use-authentication-server.md
- docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/security-and-authentication.md
https://spryker.atlassian.net/browse/FRW-450
> FRW-450: Glue Authentication fixes

- docs/scos/dev/troubleshooting/troubleshooting-general-technical-issues/troubleshooting-rabbitmq/messages-stuck-in-unacked-state
> Create new troubleshooting article about messages stuck in unacked state

- docs/scos/dev/troubleshooting/troubleshooting-general-technical-issues/troubleshooting-rabbitmq/messages-stuck-without-error
> Added new article on how to deal with stuck messages w/o errors

- docs/sdk/dev/settings.md
> removing the duplicated text

- docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-sending-an-email.md
> Fixes typo.

- docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-integrating-any-search-engine-into-a-project.md
Original PR: https://github.com/spryker/spryker-docs/pull/1345
TBD
> contributor: Corrects typo

- _data/sidebars/scos_dev_sidebar.yml
- docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/data-imports/howto-add-support-for-number-formatting-in-the-storefront.md
- docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/data-imports/howto-add-support-of-number-formatting-in-the-storefront.md
Epic: https://spryker.atlassian.net/browse/CC-13275
Ticket for IG: https://spryker.atlassian.net/browse/CC-23018
> CC-13275: Display numbers in Yves based on the current user locale.

- docs/scos/dev/back-end-development/extending-spryker/development-strategies/spryker-os-module-customisation/extend-a-core-module-that-is-used-by-another.md
suggesting that this approach will not work any longer due to strict
TBD
> Added red notification

- docs/scos/dev/guidelines/security-guidelines.md
Ticket - https://spryker.atlassian.net/browse/SC-11052
> SC-11052 Update security guidelines

- docs/acp/user/app-manifest.md
Issue https://spryker.atlassian.net/browse/APPS-5785
> Fixed businessModels and isAvailable attributes

- docs/scos/dev/feature-integration-guides/202204.0/glue-api/decoupled-glue-infrastructure/glue-api-authentication-integration.md
- docs/scos/dev/glue-api-guides/202204.0/decoupled-glue-infrastructure/how-to-guides/how-to-use-glue-api-authorization-scopes.md
- docs/scos/dev/glue-api-guides/202204.0/decoupled-glue-infrastructure/how-to-guides/routing/how-to-create-a-backend-resource.md
- docs/scos/dev/glue-api-guides/202204.0/decoupled-glue-infrastructure/how-to-guides/routing/how-to-create-a-storefront-resource.md
Ticket: https://spryker.atlassian.net/browse/FRW-552
> FRW-449 Refactored public documentation regarding GLUE infrastructure

- docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-integrating-any-search-engine-into-a-project.md
> Corrects typo

- docs/scos/dev/feature-integration-guides/202204.0/glue-api/decoupled-glue-infrastructure/glue-api-authorization-protected-endpoints-integration.md
- docs/scos/dev/feature-integration-guides/202204.0/glue-api/decoupled-glue-infrastructure/glue-api-authorization-scopes-integration.md
- docs/scos/dev/feature-integration-guides/202204.0/glue-api/decoupled-glue-infrastructure/glue-api-glue-storefront-and-backend-api-applications-integration.md
> FRW Fixed storefront and backend dependency provider

- docs/pbc/all/ratings-reviews/third-party-integrations/bazaarvoice.md
- docs/pbc/all/ratings-reviews/third-party-integrations/integrate-bazaarvoice.md
- docs/pbc/all/usercentrics/integrate-usercentrics.md
- docs/pbc/all/usercentrics/usercentrics.md
> Fixing aop docs

- docs/pbc/all/digital-asset-management/digital-asset-management.md
- docs/pbc/all/digital-asset-management/import-and-export-data/file-details-mime-type.csv.md
- docs/pbc/all/digital-asset-management/manage-in-the-back-office/add-and-edit-mime-types.md
- docs/pbc/all/digital-asset-management/manage-in-the-back-office/manage-file-list.md
- docs/pbc/all/digital-asset-management/manage-in-the-back-office/manage-file-tree.md
Reviewed and made language, structural and content edits. Replaced two screenshots.
> Review digital asset management

- _data/sidebars/marketplace_user_sidebar.yml
- _data/sidebars/scos_user_sidebar.yml
- docs/marketplace/user/intro-to-spryker-marketplace/release-notes/release-notes-202211.0.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202211.0/release-notes-202211.0.md
> Release notes for 202211.0

- docs/scos/dev/guidelines/testing-guidelines/test-helpers.md
- docs/scos/dev/guidelines/testing-guidelines/testing-console-commands.md
- docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-testing-and-tdd-spryker-commerce-os.md
Ticket: https://spryker.atlassian.net/browse/FRW-523
> FRW-172 Updated config examples for codeception 5

- docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
- docs/marketplace/user/intro-to-spryker-marketplace/release-notes/release-notes-202211.0.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202211.0/release-notes-202211.0.md
> Fixing the release title and deploy file link

- docs/sdk/dev/build-flavored-spryker-sdks.md
- docs/sdk/dev/develop-the-sdk.md
- docs/sdk/dev/integrate-sdk-commands-to-php-storm-command-line-tools.md
- docs/sdk/dev/manifest-validation.md
- docs/sdk/dev/spryker-sdk.md
- docs/sdk/dev/task-lifecycle-management.md
- docs/sdk/dev/task-set.md
- docs/sdk/dev/task.md
- docs/sdk/dev/value-resolvers.md
> Final SDK changes

- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202211.0/release-notes-202211.0.md
> Fixing the meta description for release notes

- _data/sidebars/scos_dev_sidebar.yml
- docs/scos/dev/the-docker-sdk/202204.0/installation-recipes-of-deployment-pipelines.md
Move the doc from the docker sdk repo
> Installation recipes of deployment pipelines

- _includes/footer.html
- docs/scos/user/intro-to-spryker/whats-new/php8-as-a-minimum-version-for-all-spryker-projects.md
> Removing unnecessary module dependencies

- docs/acp/user/app-manifest.md
> is_available -> isAvailable (second try)

- docs/scos/dev/glue-api-guides/202204.0/decoupled-glue-infrastructure/how-to-guides/routing/how-to-create-a-backend-resource.md
fixing issue - GlueFrontendApiApplication -> GlueBackendApiApplication
TBD
- [ x ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md
> fixing file name issue

- docs/scos/dev/back-end-development/data-manipulation/data-ingestion/spryker-middleware.md
> Fix wrong strategy explanation

- _includes/pbc/all/install-features/202204.0/install-the-prices-feature.md
Net/Gross price descriptions were mixed up.
> Fixed net/gross price description

- docs/acp/user/developing-an-app.md
- docs/scos/user/intro-to-spryker/contribute-to-documentation/markdown-syntax.md
> Instructions on adding a video

- docs/acp/user/app-manifest.md
- docs/pbc/all/payment-service-providers/payone/integrate-payone.md
- docs/scos/user/technology-partners/202204.0/payment-partners/bs-payone/bs-payone.md
> fixed broken links

- docs/scos/dev/back-end-development/forms/create-forms.md
Original PR:https://github.com/spryker/spryker-docs/pull/1449
TBD
> Contributor alama nfq patch 1

- docs/scos/dev/the-docker-sdk/202204.0/deploy-file/deploy-file-reference-1.0.md
explained what the maximum recommended limit is
TBD
> Added info box on memory limits

- Rakefile
- _data/sidebars/scos_dev_sidebar.yml
- _includes/pbc/all/install-features/202204.0/install-the-splittable-order-items-feature.md
- _includes/pbc/all/install-features/202212.0/install-the-customer-account-management-agent-assist-feature.md
- _includes/pbc/all/install-features/202212.0/install-the-customer-account-management-feature.md
- docs/scos/dev/feature-integration-guides/202212.0/customer-account-management-feature-integration.md
- docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/howto-add-support-of-number-formatting-in-the-back-office.md
Ticket: https://spryker.atlassian.net/browse/CC-24951
> CC-24951 Updated Customer Account Management and Agent Assist IGs with customer session validation plugins.

- docs/scos/dev/tutorials-and-howtos/howtos/howto-set-up-stores-with-multiple-locales.md
Ticket: https://spryker.atlassian.net/browse/SUPESC-443
> SUPESC-443: Adjust "HowTo: Set up stores with multiple locales" page.

- docs/scos/dev/system-requirements/202204.0/system-requirements.md
> Adding available languages

- docs/scos/dev/system-requirements/202204.0/system-requirements.md
> formatting fix

- docs/scos/dev/system-requirements/202204.0/system-requirements.md
> wording fix

- docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
Customer should be familiar with NewRelic APM before go live
TBD
> Added reference to NewRelic

- docs/marketplace/user/intro-to-spryker-marketplace/release-notes/release-notes-202212.0.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202212.0/release-notes-202212.0.md
fixed feature description and price example table
TBD
> Update Number Formatting Part

- docs/scos/dev/module-migration-guides/migration-guide-publish-and-synchronization.md
- docs/scos/user/features/202204.0/configurable-product-feature-overview.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202212.0/release-notes-202212.0.md
Updated screenshots and added a video for the configurable product feature overview document
The PR also applies changes from https://github.com/spryker/spryker-docs/pull/1478
TBD
> Configurable Product update

- docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-demo-mode-on-macos-and-linux.md
- docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-demo-mode-on-windows.md
- docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-macos-and-linux.md
- docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-windows.md
> updating the version number

- docs/scos/dev/back-end-development/data-manipulation/data-interaction/data-interaction.md
- docs/scos/dev/back-end-development/data-manipulation/data-interaction/search/search.md
- docs/scos/dev/back-end-development/data-manipulation/data-manipulation.md
- docs/scos/dev/back-end-development/data-manipulation/datapayload-conversion/datapayload-conversion.md
- docs/scos/dev/back-end-development/data-manipulation/payment-methods/direct-debit-example-implementation/direct-debit-payment.md
- docs/scos/dev/back-end-development/data-manipulation/payment-methods/invoice/implement-invoice-payment.md
- docs/scos/dev/back-end-development/data-manipulation/payment-methods/payment-methods.md
- docs/scos/dev/back-end-development/data-manipulation/payment-methods/prepayment/implement-prepayment.md
- docs/scos/dev/back-end-development/zed/zed.md
Added landing pages to subsections under docs.spryker.com/docs/scos/dev/back-end-development/index.html
- [X ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md
> Add backend dev sub landing pages

- docs/scos/dev/glue-api-guides/202204.0/managing-b2b-account/managing-b2b-account.md
- docs/scos/dev/glue-api-guides/202204.0/managing-products/managing-products.md
Added subsection landing pages to docs.spryker.com/docs/scos/dev/glue-api-guides/
- [ X] I agree with the Code Contribution License Agreement in CONTRIBUTING.md
> Add glue api sub landing pages

- docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/bazaarvoice.md
> Fixing a link for bazaarvoice

- docs/scos/dev/guidelines/testing-guidelines/available-test-helpers.md
> added proper line breaks

- docs/scos/dev/glue-api-guides/202212.0/managing-b2b-account/managing-b2b-account.md
- docs/scos/dev/glue-api-guides/202212.0/managing-products/managing-products.md
add landing pages to 202212.0 version of docs
> Add landing pages to 202212 0

- docs/scos/user/technology-partners/202212.0/technology-partners.md
> Tech partners introductory text update

- docs/scos/dev/front-end-development/yves/atomic-frontend/atomic-front-end-general-overview.md
Fixed some typos and redundant sentences.
> Fixed some typos and redundant sentences.

- _data/sidebars/marketplace_dev_sidebar.yml
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202212.0/release-notes-202212.0.md
> 202212 version for MP

- docs/scos/user/intro-to-spryker/whats-new/upcoming-major-module-releases.md
Add Angular modules to the upcoming major release list.
> Add Angular modules to the upcoming major release list.

- _data/sidebars/marketplace_user_sidebar.yml
- _data/sidebars/scos_dev_sidebar.yml
- _data/sidebars/scos_user_sidebar.yml
> Adding missing version to sidebars

- docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
> Added recommendation to double check for passwords

- _data/sidebars/cloud_dev_sidebar.yml
- docs/cloud/dev/spryker-cloud-commerce-os/access/index.md
- docs/cloud/dev/spryker-cloud-commerce-os/configure-deployment-pipelines/index.md
- docs/cloud/dev/spryker-cloud-commerce-os/monitoring/index.md
- docs/cloud/dev/spryker-cloud-commerce-os/security/index.md
add missing landing pages to sccoss engineer guides
> Landing pages sccoss engineer guides

- _config.yml
- _data/sidebars/marketplace_dev_sidebar.yml
- docs/pbc/all/cart-and-checkout/202212.0/tutorials-and-howtos/howto-enable-guest-checkout-in-b2b-demo-shop.md
> Missing dev guides for MP 202212

- docs/sdk/dev/spryks/spryks.md
> Keywords test

- docs/scos/dev/back-end-development/zed-ui-tables/create-and-configure-zed-tables.md
https://spryker.atlassian.net/browse/FRW-1241
> FRW-1241: Adjusted strict search documentation

- docs/scos/dev/technology-partner-guides/202212.0/operational-tools-monitoring-legal-etc/new-relic/configuring-new-relic-logging.md
remove old information and provide a link to the actual documentation
> remove old information

- docs/scos/dev/the-docker-sdk/202212.0/configure-services.md
Included deployment tracking documentation
> Included deployment tracking documentation

- docs/scos/dev/technical-enhancement-integration-guides/integrate-elastic-computing.md
Fix new relic installation guide
> Fix new relic installation guide

- docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-architectural-walkthrough-spryker-commerce-os.md
> Fix missing project namespace

- _includes/pbc/all/install-features/202304.0/install-push-notification-feature.md
Replace a part with demo application from cloning external repository to the raw code injection.
> CC-20997: Inject push notification demo application code to the ig

- docs/scos/user/intro-to-spryker/whats-new/upcoming-major-module-releases.md
> update major module releases

- Rakefile
- _data/sidebars/marketplace_user_sidebar.yml
- _data/sidebars/scos_dev_sidebar.yml
- _data/sidebars/scos_user_sidebar.yml
- _includes/scos/user/intro-to-spryker/releases/release-notes/release-notes-202212.0/patch-releases-202212.0.md
- docs/marketplace/user/intro-to-spryker-marketplace/release-notes/release-notes-202212.0/patch-releases-202212.0.md
- docs/marketplace/user/intro-to-spryker-marketplace/release-notes/release-notes-202212.0/release-notes-202212.0.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202212.0/patch-releases-202212.0.md
> adding patch releases

- docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/integrate-bazaarvoice.md
Ticket: https://spryker.atlassian.net/browse/APPS-6324
TBD
> APPS-6324: Update BazaarVoice integration docs

- docs/pbc/all/emails/202204.0/emails.md
- docs/pbc/all/emails/202204.0/howto-create-and-register-a-mail-provider.md
- docs/pbc/all/emails/202204.0/howto-create-and-register-a-mail-type-builder-plugin.md
- docs/pbc/all/emails/202204.0/howto-create-and-register-a-mailtypeplugin.md
- docs/pbc/all/emails/202204.0/tutorial-sending-an-email.md
> E-mail Documentation Edits

- _data/sidebars/scos_user_sidebar.yml
- algolia_config/_acp_user.yml
- algolia_config/_cloud_dev.yml
- algolia_config/_marketplace_dev.yml
- algolia_config/_marketplace_user.yml
- algolia_config/_paas_plus_dev.yml
- algolia_config/_pbc_all.yml
- algolia_config/_scos_dev.yml
- algolia_config/_scos_user.yml
- algolia_config/_sdk_dev.yml
- docs/pbc/all/product-information-management/202212.0/import-and-export-data/products-data-import/file-details-product-concrete.csv.md
- docs/sdk/dev/spryker-sdk.md
> Fixing multiple issues

- _data/sidebars/pbc_all_sidebar.yml
- docs/pbc/all/search/202212.0/third-party-integrations/algolia.md
> Algolia-related sidebar fix

- docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
Further underlining the importance of these steps to go live prep
TBD
> Warning for Data Import and Email Quota

- docs/scos/dev/troubleshooting/troubleshooting-performance-issues/troubleshooting-performance-issues.md
Added  step 4 and 5 in the Next steps section
TBD
> Slightly adjusted Next steps section

- _data/sidebars/pbc_all_sidebar.yml
- _data/sidebars/scos_dev_sidebar.yml
> sidebar fixes

- docs/scos/dev/data-import/202212.0/creating-a-data-importer.md
Must not be writerAware, if we do not set writer
TBD
> Wrong importer type

- docs/scos/dev/technical-enhancement-integration-guides/integrating-separate-endpoint-bootstraps.md
> Included warning about coordination required for additional endpoints

- docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-demo-mode-on-macos-and-linux.md
- docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-demo-mode-on-windows.md
- docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-macos-and-linux.md
- docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-windows.md
- docs/scos/dev/setup/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-macos-and-linux.md
- docs/scos/dev/setup/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-windows.md
Updates the getting-started guides to the latest product release version
> Updates the getting-started guides to the latest product release version

- docs/scos/dev/the-docker-sdk/202212.0/configuring-debugging-in-docker.md
Original PR: https://github.com/spryker/spryker-docs/pull/1680
TBD
> Contributor: set pathmapping with vscode variable

- docs/scos/dev/technical-enhancement-integration-guides/integrating-separate-endpoint-bootstraps.md
> remove duplicate quotes

- _data/sidebars/scu_dev_sidebar.yml
- docs/scu/dev/onboard-to-spryker-code-upgrader/connect-spryker-code-upgrader-to-a-azure-managed-project.md
- docs/scu/dev/onboard-to-spryker-code-upgrader/connect-spryker-code-upgrader-to-a-gitlab-managed-project.md
- docs/scu/dev/onboard-to-spryker-code-upgrader/onboard-to-spryker-code-upgrader.md
- docs/scu/dev/onboard-to-spryker-code-upgrader/prepare-a-project-for-spryker-code-upgrader.md
- docs/scu/dev/run-spryker-code-upgrader.md
- docs/scu/dev/troubleshooting/the-process-exceeded-the-timeout.md
- docs/scu/dev/troubleshooting/transportexception-cannot-move-pack.md
Add instructions how to connect Azure Repo to SprykerCI.
> SDK-1932: Add documentation for Azure Repos connection to SprykerCI

- docs/scos/user/overview-of-features/201903.0/overview-of-features.md
- docs/scos/user/overview-of-features/202005.0/overview-of-features.md
- docs/scos/user/overview-of-features/202009.0/overview-of-features.md
> adding missing links for feature catalogs

- docs/scos/dev/feature-integration-guides/202212.0/feature-integration-guides.md
> Fix a broken link

- docs/scu/dev/onboard-to-spryker-code-upgrader/connect-spryker-code-upgrader-to-a-azure-managed-project.md
See comment: https://spryker.atlassian.net/browse/SDK-1932?focusedCommentId=386767
Ticket: https://spryker.atlassian.net/browse/SDK-1932
> SDK-1978: Fixed azure config image link in Upgadability doc.

- _includes/pbc/all/install-features/202304.0/install-the-cart-prices-feature.md
- docs/pbc/all/cart-and-checkout/202304.0/install-and-upgrade/install-features/install-the-cart-prices-feature.md
Ticket: https://spryker.atlassian.net/browse/CC-26296
> CC-23635 Introduced cart prices feature IG.

- _includes/pbc/all/install-features/202304.0/install-the-multiple-carts-feature.md
- docs/pbc/all/cart-and-checkout/202304.0/install-and-upgrade/install-features/install-the-multiple-carts-feature.md
- Bug ticket: https://spryker.atlassian.net/browse/SUPESC-685
- Documentation ticket: https://spryker.atlassian.net/browse/SUPESC-721
> SUPESC-685 Adjust Multiple Cart IG

- _includes/pbc/all/install-features/202304.0/install-the-warehouse-picking-feature.md
Ticket: https://spryker.atlassian.net/browse/CC-26368
Epic: https://spryker.atlassian.net/browse/CC-20611
> CC-20611: Updated the warehouse picking feature guide.

- docs/scu/dev/onboard-to-spryker-code-upgrader/connect-spryker-code-upgrader-to-a-azure-managed-project.md
Add notification about repository URL for Azure Repos
> SDK-1932: Add notification for Azure connection

- .github/workflows/enforce-labels.yml
> Enforce PR labels

- .github/workflows/release.yml
> Scheduled release notes

- .github/workflows/release-drafter.yml
> changing the release drafter version

- .github/workflows/release-drafter.yml
> adjust the release drafter workflow

- .github/workflows/build-changelog.yml
> Changelog configuration file fix

- .github/workflows/build-changelog.yml
> fixing syntax of the json file

- _includes/pbc/all/install-features/202304.0/install-the-product-category-feature.md
Updated product + category IG with expander plugin.
Docs Ticket: https://spryker.atlassian.net/browse/CC-26761
Ticket: https://spryker.atlassian.net/browse/SUPESC-193
> Product + Category feature integration

- _data/sidebars/scos_user_sidebar.yml
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202304.0/security-release-notes-202304.0.md
This PR adds security release notes 202304.0.
Jira ticket: https://spryker.atlassian.net/browse/DOC-63
TBD
> Security release notes 202304.0

- _includes/pbc/all/install-features/202304.0/install-the-shipment-feature.md
- docs/pbc/all/carrier-management/202204.0/base-shop/install-and-upgrade/install-features/install-the-shipment-feature.md
- docs/pbc/all/carrier-management/202212.0/base-shop/install-and-upgrade/install-features/install-the-shipment-feature.md
- docs/pbc/all/carrier-management/202304.0/base-shop/install-and-upgrade/install-the-shipment-feature.md
Extend the Shipment integration with Shipment Type.
Ticket: https://spryker.atlassian.net/browse/CC-25232
> Install the Shipment feature

- docs/pbc/all/merchant-management/202212.0/marketplace/tutorials-and-howtos/create-gui-modules.md
This PRs corrects and updates Create GUI modules document.
Original contributor PR: https://github.com/spryker/spryker-docs/pull/1804/files
TBD
> Create GUI modules

- _data/sidebars/scos_user_sidebar.yml
- docs/scos/user/intro-to-spryker/docs-release-notes.md
> Docs release notes

- docs/pbc/all/merchant-management/202212.0/marketplace/tutorials-and-howtos/create-gui-modules.md
Fixed the path for twig file and added the command to clear router cache after creating a new controller
> Fixed path and enhanced documentation

- docs/scos/user/features/202108.0/file-manager-feature-overview/file-manager-feature-overview.md
Actual page is for Asset Management and not measurement. I modified the name. See former page screenshot: https://monosnap.com/file/B9dg25UthOGH0E7QLblU8KT0ceTEhc
TBD
> Changed Asset Measurement to Management

- Rakefile
- docs/scos/dev/the-docker-sdk/202212.0/configuring-debugging-in-docker.md
This PR adds a how-to debug PHPMD command and fixes JSON trailing comma warnings.
> Configuring debugging in Docker

- docs/acp/user/intro-to-acp/acp-installation.md
- docs/acp/user/intro-to-acp/acp-overview.md
Fixed review comments by Ievgen Shevchenko
> [APPS-6419] resolving comments from Code Review by Ievgen

- docs/cloud/dev/spryker-cloud-commerce-os/environment-provisioning.md
- docs/cloud/dev/spryker-cloud-commerce-os/multi-store-setups/multistore-setup-options.md
> Environment provisioning

- docs/scos/dev/the-docker-sdk/202204.0/configure-services.md
> removing the blackfire link

- _data/sidebars/scos_dev_sidebar.yml
> sidebar fix

- docs/scos/dev/front-end-development/202212.0/oryx/reactivity/key-concepts-of-reactivity.md
> Fixing push to Algolia

- Rakefile
- _data/sidebars/scos_dev_sidebar.yml
- docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/additional-logic-in-dependency-provider.md
- docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/dead-code-checker.md
- docs/scos/user/intro-to-spryker/docs-release-notes.md
> Doc release notes May 2023

- _config.yml
- algolia_config/_sdk_dev.yml
> Fixing product names an search

- _includes/pbc/all/install-features/202304.0/install-the-service-points-feature.md
- IG Ticket: https://spryker.atlassian.net/browse/CC-28528
- Epic Ticket: https://spryker.atlassian.net/browse/CC-28503
> Install the Service Points feature

- docs/scu/dev/onboard-to-spryker-code-upgrader/prepare-a-project-for-spryker-code-upgrader.md
Ticket: https://spryker.atlassian.net/browse/SDK-2081
> SDK-2081: Add minimum technical requirements to the upgrader documentation

- docs/acp/user/app-composition-platform-installation.md
- docs/acp/user/intro-to-acp/acp-overview.md
- docs/pbc/all/payment-service-provider/202212.0/third-party-integrations/payone/integration-in-the-back-office/integrate-payone.md
- docs/pbc/all/payment-service-provider/202212.0/third-party-integrations/payone/integration-in-the-back-office/payone-integration-in-the-back-office.md
- docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/bazaarvoice.md
- docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/integrate-bazaarvoice.md
- docs/pbc/all/search/202212.0/third-party-integrations/algolia.md
- docs/pbc/all/search/202212.0/third-party-integrations/integrate-algolia.md
- docs/pbc/all/usercentrics/integrate-usercentrics.md
- docs/pbc/all/usercentrics/usercentrics.md
> Next steps for ACP guides

- docs/pbc/all/miscellaneous/202212.0/spryker-core-feature-overview/howto-add-support-for-number-formatting-in-the-storefront.md
> Adding explanation on number formatting

- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202306.0/security-release-notes-202306.0.md
Modify the 'last updated' date in the document
Correct the customer support link
> Small corrections in security-release-notes-202306.0.md

- _includes/pbc/all/install-features/202304.0/install-glue-api/install-the-dynamic-store-glue-api.md
Ticket: https://spryker.atlassian.net/browse/FRW-1613
> FRW-1610 Adjusted docs

- docs/scu/dev/onboard-to-spryker-code-upgrader/connect-spryker-ci-to-a-github-managed-project.md
> Extend the list of GitHub permissions required for integration of the repository into BuddyCI

- docs/scos/dev/technical-enhancement-integration-guides/Integrate-profiler-module.md
https://spryker.atlassian.net/browse/SDK-2600
> SDK-2600 profiler docs

- _data/sidebars/pbc_all_sidebar.yml
- docs/pbc/all/cart-and-checkout/202212.0/base-shop/install-and-upgrade/install-features/install-the-approval-process-feature.md
- docs/pbc/all/warehouse-management-system/202304.0/base-shop/install-and-upgrade/install-the-warehouse-user-management-feature.md
- docs/scos/user/intro-to-spryker/docs-release-notes.md
> Docs release notes June 2023

- docs/scu/dev/onboard-to-spryker-code-upgrader/connect-spryker-ci-to-a-github-managed-project.md
Ticket: [SDK-2885](https://spryker.atlassian.net/browse/SDK-2885)
[SDK-2885]: https://spryker.atlassian.net/browse/SDK-2885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SDK-2885: Extend the list of required GitHub permissions for upgrader

- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202306.0/security-release-notes-202306.0.md
Add an additional security vulnerability 'Missing security HTTP headers' in the security release notes for Q2
Jira: https://spryker.atlassian.net/browse/DOC-157
TBD
> Add 'Missing security HTTP headers' in security-release-notes-202306

- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202306.0/security-release-notes-202306.0.md
Minor changes. No content changes
> Minor changes in security-release-notes-202306.0.md

- docs/acp/user/intro-to-acp/acp-overview.md
Linked to integration pages directly instead of apps main landing page
TBD
> Update acp-overview.md with direct links to integration page of apps

- docs/pbc/all/payment-service-provider/202212.0/third-party-integrations/payone/integration-in-the-back-office/payone-integration-in-the-back-office.md
- docs/pbc/all/search/202212.0/base-shop/third-party-integrations/algolia.md
> Fixing the variables for acp docs

- docs/pbc/all/search/202212.0/base-shop/third-party-integrations/algolia.md
> Update JSON example

- _includes/pbc/all/install-features/202304.0/install-the-spryker-core-feature.md
- docs/scos/dev/feature-integration-guides/202304.0/spryker-core-feature-integration.md
Jira ticket: https://spryker.atlassian.net/browse/CC-25992
> CC-25992: Adjusted login mechanism for agent and customer.

- docs/scos/dev/guidelines/security-guidelines.md
Ticket: https://spryker.atlassian.net/browse/FRW-1042
> FRW-1042 Updated headers section.

- Rakefile
Removed the checks for the 202204 version
> Add 202204.0 to ignorelist

- _includes/pbc/all/install-features/202400.0/install-the-product-offer-shipment-feature.md
- docs/pbc/all/offer-management/202400.0/unified-commerce/install-and-upgrade/install-the-product-offer-shipment-feature.md
- docs/scos/user/intro-to-spryker/docs-release-notes.md
Epic 1: https://spryker.atlassian.net/browse/CC-26549
Epic 2: https://spryker.atlassian.net/browse/CC-26573
Epic 3: https://spryker.atlassian.net/browse/CC-26571
IG ticket: https://spryker.atlassian.net/browse/CC-29717
> CC-26571: Update Product Offer Shipment feature

- _includes/pbc/all/install-features/202400.0/install-the-shipment-service-points-feature.md
- docs/pbc/all/carrier-management/202400.0/unified-commerce/install-and-upgrade/install-the-shipment-service-points-feature.md
Epic 1: https://spryker.atlassian.net/browse/CC-26549
Epic 2: https://spryker.atlassian.net/browse/CC-26573
Epic 3: https://spryker.atlassian.net/browse/CC-26571
IG ticket: https://spryker.atlassian.net/browse/CC-29717
> CC-26571: Update Shipment + Service Points feature

- docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/npm-checker.md
Ticket: https://spryker.atlassian.net/browse/SDK-4487
> SDK-4487: Fixed npm-checker.md example format.

- docs/pbc/all/tax-management/202307.0/tax-management.md
> Add Vertex to the Tax management table

- _includes/footer.html
> Adding Partner Safari to footer

- .github/workflows/build-changelog.yml
> Adding time period to the changelog file

- docs/cloud/dev/spryker-cloud-commerce-os/add-variables-in-the-parameter-store.md
Update add-variables-in-the-parameter-store.md
Updates reserved environment variables list in cloud
> Add variables in the Parameter Store

- docs/scos/dev/back-end-development/data-manipulation/data-ingestion/spryker-middleware.md
> Note about the discontinued Spryker Middleware

- .github/workflows/build-changelog.yml
> Updating the build changelog file

- docs/scos/dev/feature-integration-guides/202307.0/glue-api/dynamic-data-api/dynamic-data-api-integration.md
- docs/scos/dev/glue-api-guides/202307.0/dynamic-data-api/how-to-guides/how-to-configure-dynamic-data-api.md
> Dynamic Data API guides

- _includes/pbc/all/install-features/202307.0/install-dynamic-multistore-the-availability-notification-feature.md
- _includes/pbc/all/install-features/202307.0/install-dynamic-multistore-the-cart-feature.md
- _includes/pbc/all/install-features/202307.0/install-dynamic-multistore-the-cms-feature.md
- _includes/pbc/all/install-features/202307.0/install-dynamic-multistore-the-customer-account-management-feature.md
- _includes/pbc/all/install-features/202307.0/install-dynamic-multistore-the-prices-feature.md
- _includes/pbc/all/install-features/202307.0/install-dynamic-multistore-the-product-feature.md
- _includes/pbc/all/install-features/202307.0/install-dynamic-multistore.md
- _includes/pbc/all/install-features/202307.0/marketplace/install-the-marketplace-merchant-portal-core-dynamic-multistore.md
- _includes/pbc/all/install-glue-api/202307.0/install-the-dynamic-multistore-glue-api.md
- _includes/pbc/all/upgrade-modules/upgrade-the-country-module.md
- _includes/pbc/all/upgrade-modules/upgrade-the-currency-module.md
- _includes/pbc/all/upgrade-modules/upgrade-the-locale-module.md
- docs/pbc/all/dynamic-multistore/202307.0/base-shop/delete-stores.md
- docs/pbc/all/dynamic-multistore/202307.0/base-shop/dynamic-multistore-feature-overview.md
- docs/pbc/all/dynamic-multistore/202307.0/dynamic-multistore.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202307.0/release-notes-202307.0.md
> Polishing the Early Access Release definition for DMS

- docs/scos/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-macos-and-linux.md
- docs/scos/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-windows.md
- docs/scos/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-macos-and-linux.md
- docs/scos/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-windows.md
- docs/scos/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-macos-and-linux.md
- docs/scos/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-windows.md
Updates the getting-started guides to the latest product release version 202307.0
> Updates the getting-started guides to the latest product release

- _data/sidebars/scos_dev_sidebar.yml
- docs/pbc/all/dynamic-multistore/202307.0/base-shop/install-and-upgrade/install-features/install-dynamic-multistore-availability-notification-feature.md
- docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/npm-checker.md
- docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/spryker-security-checker.md
- docs/scos/user/intro-to-spryker/docs-release-notes.md
> Doc release notes 08.2023

- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202307.0/release-notes-202307.0.md
> Adding details to a release notes item

- docs/pbc/all/ratings-reviews/202307.0/third-party-integrations/integrate-bazaarvoice.md
Updates the channel names described on the integration pages for BazaarVoice.
> PBC-2858: Updates channel names

- docs/scos/dev/front-end-development/202212.0/oryx/oryx.md
- docs/scos/dev/front-end-development/202307.0/oryx/oryx.md
> fix: Oryx is web framework agnostic

- _includes/pbc/all/install-features/202400.0/install-the-packaging-units-feature.md
> Fix typo in the packaging units feature IG

- docs/pbc/all/search/202307.0/base-shop/third-party-integrations/algolia/algolia.md
> Algolia video fix

- docs/scu/dev/run-spryker-code-upgrader.md
https://spryker.atlassian.net/browse/SDK-4885
> SDK-4885: Fixed link that for GitHab

- .github/workflows/build-changelog.yml
> Updating the changelog file

- docs/scu/dev/onboard-to-spryker-code-upgrader/prepare-a-project-for-spryker-code-upgrader.md
https://spryker.atlassian.net/browse/SDK-4691
> SDK-4691: updated minimum supported PHP version for Upgrader

- docs/pbc/all/tax-management/202307.0/base-shop/tax-feature-overview.md
> Fixing a link for tax management

- docs/pbc/all/data-exchange/202311.0/data-exchange-faq.md
- docs/pbc/all/data-exchange/202311.0/data-exchange.md
> Fixing the data exchange docs

- docs/pbc/all/tax-management/202400.0/third-party-integrations/vertex/install-vertex.md
> fixing a code sample

- _includes/pbc/all/upgrade-modules/upgrade-the-chart-module.md
- docs/pbc/all/order-management-system/202307.0/base-shop/import-and-export-data/orders-data-export/orders-data-export.md
https://spryker.atlassian.net/browse/CC-31676
> CC-25963 Update chart module migration

- .github/workflows/build-changelog.yml
> Changelog file for 10.2023

- _data/sidebars/scos_user_sidebar.yml
> Docs updates fix

- docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/configure-the-akeneo-pim-integration-app/configure-data-mapping-between-akeneo-and-sccos.md
> Fixing akeneo pages

- docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/vertex.md
> Vertex video fix

- _data/sidebars/pbc_all_sidebar.yml
> Adding landing pages to sidebar

- _data/sidebars/scos_user_sidebar.yml
- docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/akeneo-pim-integration-app.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202311.0/release-notes-202311.0.md
> Release notes 202311.0

- docs/sdk/dev/development-tools/development-tools.md
> Fixed redirects in this page

- docs/scos/dev/architecture/module-api/performance-and-scalability.md
- docs/scos/dev/guidelines/performance-guidelines/front-end-performance-guidelines.md
- docs/scos/dev/guidelines/performance-guidelines/general-performance-guidelines.md
- docs/scos/dev/guidelines/performance-guidelines/performance-guidelines.md
> Redirect fixes on a couple of  pages 

- docs/ca/dev/multi-store-setups/multistore-setup-options.md
> Fixed Redirect

- _data/sidebars/pbc_all_sidebar.yml
- _includes/footer.html
- docs/pbc/all/data-exchange/202311.0/tutorials-and-howtos/how-to-configure-data-exchange-api.md
- docs/pbc/all/data-exchange/202311.0/tutorials-and-howtos/how-to-send-request-in-data-exchange-api.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202311.0/release-notes-202311.0.md
> Release notes 202311.0 fix

- _config.yml
- _data/sidebars/pbc_all_sidebar.yml
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202311.0/release-notes-202311.0.md
> Fixing the service point PBC

- _config.yml
- _data/sidebars/scos_dev_sidebar.yml
- _data/sidebars/scos_user_sidebar.yml
- docs/pbc/all/offer-management/202311.0/offer-management.md
- docs/scos/dev/tutorials-and-howtos/howtos/how-to-make-a-multi-language-setup.html.md
- docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202212.0/release-notes-202212.0.md
> Changing the main docs version

- docs/ca/dev/configure-deployment-pipelines/deployment-pipelines.md
- docs/scos/dev/the-docker-sdk/202307.0/the-docker-sdk.md
- docs/scos/dev/the-docker-sdk/202311.0/the-docker-sdk.md
> Updating the PHP version for deployment pipelines docs

- _includes/search/algolia_quicksearch.html
> Algolia results set fix

- _includes/search/algolia_quicksearch.html
> Adjusting the result set value

- _data/sidebars/scos_user_sidebar.yml
- docs/scos/user/intro-to-spryker/releases/release-notes/security-release-notes-202312.0.md
- docs/scos/user/intro-to-spryker/releases/release-notes/security-release-notes-202312.0/security-release-notes-202312.0.md
Security release notes for Q4
- [ x ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md
> Security release notes for Q4

- docs/scos/user/intro-to-spryker/releases/release-notes/security-release-notes-202312.0.md
Adding the rest of the security vulnerabilities that were fixed in Q4
> Update the security release notes of Q4

- docs/pbc/all/data-exchange/202311.0/data-exchange.md
Minor updates on Data Exchange API explanation.
TBD
> Update data-exchange.md - Minor updates on Data Exchange API explanation.

- docs/scu/dev/integrating-code-releases/integrating-security-releases.md
https://spryker.atlassian.net/browse/SDK-5637
> SDK-5637: Updated doc for security release integration

- .github/workflows/build-changelog.yml
> Automated release notes 12.2023

- _data/sidebars/acp_user_sidebar.yml
- docs/acp/user/develop-an-app/debug-an-app-with-xdebug.md
- docs/scos/user/intro-to-spryker/docs-updates.md
> Docs updates 12.2023

- docs/pbc/all/merchant-management/202311.0/marketplace/manage-in-the-back-office/manage-merchants/edit-merchants.md
Fix for the broken link on this page: https://docs.spryker.com/docs/pbc/all/merchant-management/202311.0/marketplace/manage-in-the-back-office/manage-merchants/edit-merchants.html#edit-merchant-users
> Fix of the link

- docs/pbc/all/carrier-management/202311.0/base-shop/install-and-upgrade/install-features/install-the-shipment-feature.md
- docs/pbc/all/merchant-management/202311.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-portal-core-feature.md
- docs/pbc/all/product-information-management/202311.0/base-shop/feature-overviews/catalog-feature-overview.md
- docs/pbc/all/product-information-management/202311.0/base-shop/import-and-export-data/categories-data-import/import-file-details-category.csv.md
- docs/pbc/all/product-information-management/202311.0/base-shop/manage-in-the-back-office/products/manage-abstract-products-and-product-bundles/create-abstract-products-and-product-bundles.md
- docs/pbc/all/product-information-management/202311.0/marketplace/marketplace-product-approval-process-feature-overview.md
- docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/vertex.md
> Redirect fixes

- docs/acp/user/develop-an-app/develop-an-app.md
- docs/scos/dev/the-docker-sdk/202212.0/configure-services.md
- docs/scos/dev/the-docker-sdk/202307.0/configure-services.md
- docs/scos/dev/the-docker-sdk/202311.0/configure-services.md
Fixes for the links in documentation
> Fix the links

- Gemfile.lock
Trying to fix deploy by updating the RUby version
> Update ruby version

- docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/configure-stripe.md
- docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/stripe.md
> Stripe overview

- docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/stripe.md
Updated the description with more sections
TBD
> Updated stripe.md with more sections

- _data/sidebars/pbc_all_sidebar.yml
- docs/acp/user/app-composition-platform-installation.md
- docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/payone/integration-in-the-back-office/configure-payone.md
- docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/payone/integration-in-the-back-office/integrate-payone.md
- docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/integrate-stripe.md
- docs/pbc/all/ratings-reviews/202311.0/third-party-integrations/integrate-bazaarvoice.md
- docs/pbc/all/search/202311.0/base-shop/third-party-integrations/algolia/configure-algolia.md
- docs/pbc/all/search/202311.0/base-shop/third-party-integrations/algolia/integrate-algolia.md
- docs/pbc/all/usercentrics/configure-usercentrics.md
- docs/pbc/all/usercentrics/integrate-usercentrics.md
> Adjusting the ACP guides

- _data/sidebars/scos_user_sidebar.yml
> Fixing a title

- docs/pbc/all/customer-relationship-management/202403.0/base-shop/install-and-upgrade/install-features/install-the-customer-account-management-agent-assist-feature.md
- docs/pbc/all/customer-relationship-management/202403.0/base-shop/install-and-upgrade/install-glue-api/install-the-company-account-glue-api.md
- docs/pbc/all/miscellaneous/202403.0/install-and-upgrade/install-features/install-the-spryker-core-feature.md
- docs/pbc/all/user-management/202403.0/base-shop/install-and-upgrade/install-the-agent-assist-feature.md
- docs/scos/user/intro-to-spryker/docs-updates.md
> Docs updates 01.2024

- _data/sidebars/scos_user_sidebar.yml
- docs/dg/dev/backend-development/messages-and-errors/registering-a-new-service.md
- docs/dg/dev/guidelines/performance-guidelines/architecture-performance-guidelines.md
- docs/scos/user/intro-to-spryker/contribute-to-the-documentation/add-global-sections-to-the-documentation.md
- docs/scos/user/intro-to-spryker/contribute-to-the-documentation/build-the-documentation-site.md
- docs/scos/user/intro-to-spryker/contribute-to-the-documentation/contribute-to-the-documentation.md
- docs/scos/user/intro-to-spryker/contribute-to-the-documentation/edit-documentation-via-pull-requests.md
- docs/scos/user/intro-to-spryker/contribute-to-the-documentation/general-rules-and-guidance-for-adding-new-documents.md
- docs/scos/user/intro-to-spryker/contribute-to-the-documentation/install-recommended-vs-code-extensions.md
- docs/scos/user/intro-to-spryker/contribute-to-the-documentation/markdown-syntax.md
- docs/scos/user/intro-to-spryker/contribute-to-the-documentation/report-documentation-issues.md
- docs/scos/user/intro-to-spryker/contribute-to-the-documentation/review-pull-requests.md
Update the instructions for adding global sections to the docs
> Add global sections to the documentation

- _includes/search/algolia_quicksearch.html
> Hits per page in the new search

- docs/pbc/all/data-exchange/202311.0/tutorials-and-howtos/how-to-send-request-in-data-exchange-api.md
- docs/scos/dev/glue-api-guides/202311.0/use-default-glue-parameters.md
https://spryker.atlassian.net/browse/FRW-7333
> FRW-6879 Updated docs

- _data/sidebars/dg_dev_sidebar.yml
- docs/dg/dev/guidelines/coding-guidelines/secure-coding-practices-for-external-packages.md
- docs/pbc/all/customer-relationship-management/202311.0/base-shop/import-and-export-data/file-details-customer.csv.md
- docs/pbc/all/request-for-quote/202311.0/import-and-export-data/file-details-quote-request-version.csv.md
- docs/scos/user/intro-to-spryker/docs-updates.md
> Docs updates Feb 2024

- docs/scos/user/intro-to-spryker/docs-updates.md
> Docs updated pages

- docs/ca/dev/preparation-for-going-live.md
> fixing the infoblock

- docs/ca/devscu/spryker-code-upgrader.md
- docs/dg/dev/updating-spryker/analyzing-and-upgrading-projects-with-spryker-jarvis.md
https://spryker.atlassian.net/browse/FRW-7478
> Adjusted upgrader docs

- docs/pbc/all/data-exchange/202311.0/tutorials-and-howtos/how-to-send-request-in-data-exchange-api.md
> Fixed typo for Data Exchange API doc

- docs/dg/dev/backend-development/zed/persistence-layer/query-container/query-container.md
> Fixing typo on the "About the query container" page

- docs/pbc/all/customer-relationship-management/202404.0/base-shop/manage-in-the-back-office/company-units/create-company-units.md
- docs/pbc/all/customer-relationship-management/202404.0/base-shop/manage-in-the-back-office/company-units/edit-company-units.md
https://spryker.atlassian.net/browse/SUPESC-38
> SUPESC-38 Added Phone field for Company Business Unit.

- docs/dg/dev/acp/app-composition-platform-installation.md
> BUGFIX: Fixed namespace typo

- docs/dg/dev/code-contribution-guide.md
Update code contribution guidelines and howto
> Update code contribution guidelines and howto

- docs/pbc/all/search/202311.0/base-shop/third-party-integrations/algolia/integrate-algolia.md
Triggered by new functionality and fixed introduced in https://github.com/spryker-shop/suite/pull/1530/files
https://spryker.atlassian.net/browse/ACP-2532
> ACP-2532: Update integrate-algolia.md

- _data/sidebars/pbc_all_sidebar.yml
- _includes/pbc/all/install-features/202404.0/install-the-checkout-non-splittable-products-feature.md
- docs/pbc/all/cart-and-checkout/202404.0/base-shop/install-and-upgrade/install-features/install-the-checkout-non-splittable-products-feature.md
- Ticket: https://spryker.atlassian.net/browse/CC-33273
> CC-33273 Add Checkout + Non-splittable Products IG

- docs/pbc/all/search/202311.0/base-shop/third-party-integrations/algolia/disconnect-algolia.md
https://spryker.atlassian.net/browse/ACP-2478
> ACP-2478: Mention that algolia indexes won't be removed after disconnect

- docs/about/all/releases/release-notes-202404.0.md
- docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-merchant-portal/manage-merchant-relation-requests.md
- docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/manage-merchant-relations/manage-merchant-relation-requests.md
- docs/pbc/all/merchant-management/202404.0/marketplace/merchant-b2b-contracts-and-contract-requests-features-overview.md
- docs/pbc/all/user-management/202404.0/base-shop/agent-assist-feature-overview.md
- docs/pbc/all/user-management/202404.0/marketplace/merchant-portal-agent-assist-feature-overview.md
> Placeholder for the release notes

- _includes/pbc/all/install-features/202311.0/install-the-multi-store-products-feature.md
- docs/dg/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-windows.md
- docs/pbc/all/product-information-management/202311.0/base-shop/install-and-upgrade/install-features/install-the-multi-store-products-feature.md
> Hotfix deploy for release

- .github/workflows/ci.yml
> Update heroku deployment action

- docs/dg/dev/guidelines/keeping-a-project-upgradable/run-the-evaluator-tool.md
> Evaluator: extend doc with checkers

- _data/sidebars/pbc_all_sidebar.yml
- _includes/pbc/all/glue-api-guides/202307.0/product-labels-response-attributes.md
- _includes/pbc/all/glue-api-guides/202311.0/product-labels-response-attributes.md
- _includes/pbc/all/glue-api-guides/202404.0/abstract-product-image-sets-reponse-attributes.md
- _includes/pbc/all/glue-api-guides/202404.0/category-nodes-response-attributes.md
- _includes/pbc/all/glue-api-guides/202404.0/product-management-attributes-response-attributes.md
- docs/pbc/all/cart-and-checkout/202404.0/base-shop/manage-using-glue-api/glue-api-retrieve-customer-carts.md
- docs/pbc/all/cart-and-checkout/202404.0/base-shop/manage-using-glue-api/manage-carts-of-registered-users/glue-api-manage-carts-of-registered-users.md
- docs/pbc/all/cart-and-checkout/202404.0/base-shop/manage-using-glue-api/manage-guest-carts/glue-api-manage-guest-carts.md
- docs/pbc/all/merchant-management/202404.0/base-shop/merchant-b2b-contracts-and-contract-requests-feature-overview.md
- docs/pbc/all/merchant-management/202404.0/marketplace/marketplace-merchant-b2b-contracts-and-contract-requests-feature-overview.md
- docs/pbc/all/product-information-management/202311.0/base-shop/manage-using-glue-api/glue-api-retrieve-product-labels.md
- docs/pbc/all/product-information-management/202404.0/base-shop/manage-using-glue-api/abstract-products/glue-api-retrieve-abstract-products.md
- docs/pbc/all/product-information-management/202404.0/base-shop/manage-using-glue-api/abstract-products/glue-api-retrieve-image-sets-of-abstract-products.md
- docs/pbc/all/product-information-management/202404.0/base-shop/manage-using-glue-api/categories/glue-api-retrieve-category-nodes.md
- docs/pbc/all/product-information-management/202404.0/base-shop/manage-using-glue-api/concrete-products/glue-api-retrieve-concrete-products.md
- docs/pbc/all/product-information-management/202404.0/base-shop/manage-using-glue-api/glue-api-retrieve-product-attributes.md
- docs/pbc/all/product-information-management/202404.0/base-shop/manage-using-glue-api/glue-api-retrieve-product-labels.md
- docs/pbc/all/product-relationship-management/202404.0/glue-api-retrieve-related-products.md
- docs/pbc/all/shopping-list-and-wishlist/202404.0/base-shop/manage-using-glue-api/glue-api-manage-wishlists.md
> Glue api includes 1

- _includes/pbc/all/install-features/202404.0/install-dynamic-multistore.md
- _includes/pbc/all/upgrade-modules/upgrade-the-country-module.md
- _includes/pbc/all/upgrade-modules/upgrade-the-currency-module.md
> Dynamic multistore 202404.0

- docs/dg/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-macos-and-linux.md
The directory is wrong for B2C marketplace
> Fix issue for B2C Marketplace installation recipe

- docs/dg/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-windows.md
Fix wrong b2c marketplace path in windows installation guide
> Fix wrong b2c marketplace path in windows installation guide

- _data/sidebars/pbc_all_sidebar.yml
- docs/pbc/all/cart-and-checkout/202404.0/base-shop/feature-overviews/cart-feature-overview/dynamic-cart-overview.md
- docs/pbc/all/cart-and-checkout/202407.0/base-shop/feature-overviews/cart-feature-overview/cart-feature-overview.md
- docs/pbc/all/cart-and-checkout/202407.0/base-shop/feature-overviews/cart-feature-overview/dynamic-cart-overview.md
Overview for the dynamic cart functionality
> Dynamic cart overview

- _data/sidebars/about_all_sidebar.yml
- docs/about/all/about-the-docs/contribute-to-the-docs/merge-docs-pull-requests.md
> Community contributions

- _includes/pbc/all/install-features/202407.0/marketplace/install-the-category-management-marketplace-merchant-commission.md
- _includes/pbc/all/install-features/202407.0/marketplace/install-the-prices-marketplace-merchant-commission-feature.md
- _includes/pbc/all/install-features/202407.0/marketplace/install-the-product-marketplace-merchant-commission-feature.md
- docs/pbc/all/merchant-management/202407.0/marketplace/install-and-upgrade/install-features/install-the-category-management-marketplace-merchant-commission.md
- docs/pbc/all/merchant-management/202407.0/marketplace/install-and-upgrade/install-features/install-the-prices-marketplace-merchant-commission-feature.md
- docs/pbc/all/merchant-management/202407.0/marketplace/install-and-upgrade/install-features/install-the-product-marketplace-merchant-commission-feature.md
- IG ticket: https://spryker.atlassian.net/browse/CC-33835
- Epic ticket: https://spryker.atlassian.net/browse/CC-33281
> CC-33281 Add IGs for Connector modules

- _data/sidebars/about_all_sidebar.yml
- docs/about/all/about-the-docs/contribute-to-the-docs/add-images-and-other-media-to-the-docs.md
Add instructions for adding images to the docs
> Adding media to the docs

- docs/dg/dev/guidelines/security-guidelines.md
Add whitelisting of Third-party systems to Security guidelines
> Add whitelisting of Third-party systems to Security guidelines

- docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/payone/integration-in-the-back-office/configure-payone.md
[Ticket](https://spryker.atlassian.net/browse/ACP-3511)
Please add this pic
```
https://spryker.s3.eu-central-1.amazonaws.com/docs/aop/user/apps/payone/payone-payment-portal-configuration.png
```
> ACP-3511: Added missing Payone portal configuration description

- docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe.md
- docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe.md
Added docs on how to pass additionalPaymentData to Stripe.
> ACP-3375 Added docs on how to pass additionalPaymentData to Stripe.

- docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe.md
- docs/pbc/all/search/202404.0/base-shop/install-and-upgrade/upgrade-search-initialization.md
Ticket: https://spryker.atlassian.net/browse/ACP-2601
> ACP-2601: How to embed Stripe App payment page to your storefront application

- _data/sidebars/pbc_all_sidebar.yml
- docs/dg/dev/backend-development/audit-logs/audit-logs.md
- docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/payone/integration-in-the-back-office/payone-integration-in-the-back-office.md
- docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/payone/payone.md
https://spryker.atlassian.net/browse/ACP-3514
> ACP-3514: Updated limitation for payone & fixed navigation

- _data/sidebars/pbc_all_sidebar.yml
> Fix stripe sidebar version

- docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-macos-and-linux.md
- docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-windows.md
- docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-macos-and-linux.md
- docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-windows.md
- docs/dg/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-macos-and-linux.md
- docs/dg/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-windows.md
Update Spryker Demo Install Version to 202404.0
> Update Spryker Demo Install Version to 202404.0

- docs/pbc/all/payment-service-provider/202404.0/marketplace/stripe-third-party-integration/install-and-configure-stripe-prerequisites-for-marketplace.md
Added missing documentation for Asynchronous messages for the Stripe Marketplace configuration.
> ACP-2626 Added missing message configuration

- docs/pbc/all/merchant-management/202407.0/marketplace/import-and-export-data/merchant-commissions/import-file-details-merchant-comission.csv.md
- docs/pbc/all/merchant-management/202407.0/marketplace/marketplace-merchant-commission-feature-overview.md
Added tables with related articles
> related articles

- docs/dg/dev/guidelines/security-guidelines.md
> Bugfix the DependencyProviders names

- docs/ca/dev/configure-deployment-pipelines/deployment-in-states.md
- docs/pbc/all/merchant-management/202407.0/marketplace/install-and-upgrade/manage-in-the-back-office/back-office-import-merchant-commissions.md
- docs/pbc/all/order-management-system/202404.0/base-shop/order-management-feature-overview/order-cancellation-overview.md
- docs/pbc/all/product-information-management/202404.0/base-shop/feature-overviews/configurable-bundle-feature-overview.md
- docs/pbc/all/product-information-management/202404.0/base-shop/feature-overviews/product-groups-feature-overview.md
> Gifs to mp4

- css/pages/_content.scss
- docs/dg/dev/guidelines/security-guidelines.md
> Add instruction for the gateway protection

- css/pages/_content.scss
- docs/dg/dev/data-import/202404.0/implement-incremental-installers.md
> fixed implement-incremental-installers.md

- docs/pbc/all/payment-service-provider/202404.0/marketplace/stripe-third-party-integration/install-and-configure-stripe-prerequisites-for-marketplace.md
https://spryker.atlassian.net/browse/ACP-3754
> ACP-3754: Updated ACL plugins for stripe

- docs/about/all/releases/release-notes-202311.0.md
> added important message for the Dynatrace integration feature

- docs/dg/dev/backend-development/data-manipulation/data-publishing/add-publish-events.md
> Feature: Update add-publish-events.md

- _data/sidebars/about_all_sidebar.yml
- css/pages/_content.scss
- docs/about/all/releases/security-release-notes-202409.0.md
The security release notes for Q3
> Security release notes for Q3

- docs/dg/dev/best-practices/non-functional-requirement-templates/operational-and-deployment-guidelines.md
Scalability guidelines on P&S processes was not documented. The added guideline is vital for a healthy app - infrastructure cooperation.
> Update operational-and-deployment-guidelines.md with Scalability quality

- docs/dg/dev/guidelines/project-development-guidelines.md
> FRW-7700 Updated project guidlines

- docs/pbc/all/merchant-management/202407.0/marketplace/marketplace-merchant-commission-feature-overview.md
Remove current limitations and add price more description
> DOC-258 Remove store configuration

- docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/stripe/stripe.md
Add a meaningful description here that will let us know what you want to fix with this PR or what functionality you want to add.
This is a mandatory step to make sure you are aware of the license agreement and agree to it. `HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH` is a hash of the commit you are basing your branch from the master branch. You …
> Added AfterPay to Stripe page

- docs/dg/dev/backend-development/data-manipulation/data-publishing/publish-and-synchronization.md
- docs/pbc/all/dynamic-multistore/202404.0/base-shop/dynamic-multistore-feature-overview.md
- Epic: https://spryker.atlassian.net/browse/CC-33982
> CC-33982: Added limitations for Direct Sync feature.

- docs/about/all/releases/release-notes-202410.0.md
> Hot fix early access

- _includes/footer.html
- _layouts/home.html
Changed Two links, one for the homepage and one for the footer that leads to a canonical page or a redirected page for SEO purposes.
Homepage - Quick installation Link
Footer - Release Notes Link
This is a mandatory step to make sure you are aware of the license agreement and agree to it. `HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH` is a hash of …
> SEO Changes for the Homepage

- docs/about/all/about-spryker.md
- docs/about/all/master-suite.md
- docs/about/all/supported-browsers.md
Changed the following pages for small SEO update.
- About-Spyker: Meta Description & Canonical Links
- Master-Suite: Meta Description
- Supported Browsers: Meta Description
This is a mandatory step to make sure you are aware of the license agreement and agree to it. `HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH` is a hash of the commit you are …
> Spryker About All high level Pages SEO

- docs/about/all/about-the-docs/about-spryker-docs.md
- docs/about/all/about-the-docs/contribute-to-the-docs/add-global-sections-to-the-docs.md
- docs/about/all/about-the-docs/contribute-to-the-docs/add-images-and-other-media-to-the-docs.md
- docs/about/all/about-the-docs/contribute-to-the-docs/contribute-to-the-docs.md
- docs/about/all/about-the-docs/contribute-to-the-docs/edit-the-docs-locally.md
- docs/about/all/about-the-docs/contribute-to-the-docs/edit-the-docs-using-a-web-browser.md
- docs/about/all/about-the-docs/contribute-to-the-docs/report-docs-issues.md
- docs/about/all/about-the-docs/contribute-to-the-docs/review-docs-pull-requests.md
- docs/about/all/about-the-docs/run-the-docs-locally.md
- docs/about/all/about-the-docs/style-guide/general-rules-and-guidance-for-adding-docs.md
- docs/about/all/about-the-docs/style-guide/spryker-docs-style-guide.md
- docs/about/all/about-the-docs/style-guide/style-guide-examples.md
- docs/about/all/about-the-docs/style-guide/style-guide-spelling.md
- docs/about/all/about-the-docs/style-guide/word-list.md
The following pages have been updated for SEO:
About-spryker-docs: Meta Description
Add Global sections to the docs: Meta Description
Add images and other media to the docs: Meta Description
Contribute to the docs: Meta Description
Edit the docs Locally: Meta Description
Edit the docs using a web browser: Meta Description
Review Docs Pull Requests: Meta Description
Run the docs locally: Meta Description
general rules and guidance for adding docs: Meta Description
Spryker Docs Style Guide: Meta Description
Style guide examples: Meta Description
Style Guide Spelling: Meta Description
Word List: Meta Description
- Add a …
> About the Docs SEO

- _config_production.yml
- docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/unzer/extend-and-customize/customize-the-credit-card-display-in-your-payment-step.md
Ticket: https://spryker.atlassian.net/browse/FRW-9223
> FRW-9223 Added site.url configuration to the production config.

- docs/about/all/releases/product-and-code-releases.md
Updated the Product And Code releases meta description
> About All Releases SEO Update

- _config_production.yml
Ticket: https://spryker.atlassian.net/browse/FRW-9223
> fix production config

- _data/sidebars/dg_dev_sidebar.yml
- _includes/pbc/all/glue-api-guides/202311.0/shipments-response-attributes.md
- _includes/pbc/all/install-features/202410.0/install-the-shipment-feature.md
- docs/dg/dev/acp/acp-security-assessment.md
- docs/pbc/all/carrier-management/202311.0/base-shop/manage-in-the-back-office/add-delivery-methods.md
- docs/pbc/all/carrier-management/202311.0/base-shop/manage-in-the-back-office/edit-delivery-methods.md
> Table divs and seo

- _data/sidebars/ca_dev_sidebar.yml
- docs/ca/dev/add-variables-in-the-parameter-store.md
- docs/ca/dev/configure-data-import-from-an-s3-bucket.md
- docs/ca/dev/configure-debugging.md
- docs/ca/dev/connecting-the-docker-sdk.md
- docs/ca/dev/create-and-restore-database-backups.md
- docs/ca/dev/deploy-in-a-staging-environment.md
- docs/ca/dev/environment-scaling.md
- docs/ca/dev/getting-started-with-cloud-administration.md
- docs/ca/dev/monitoring-issues-and-informing-about-alerts.md
- docs/ca/dev/performance-testing-in-staging-enivronments.md
- docs/ca/dev/preparation-for-going-live.md
- docs/ca/dev/set-up-dns.md
- docs/ca/dev/set-up-notifications-for-5xx-errors.md
- docs/ca/dev/setting-up-a-custom-ssl-certificate.md
- docs/ca/dev/spryker-cloud-commerce-os-management.md
- docs/ca/dev/starting-asynchronous-commands.md
- docs/ca/dev/working-with-logs.md
Updated the following pages for an SEO update, changed the meta description for:
- Add variables in the parameter store
- configure data import from an s3 bucket
- configure debugging
- connecting the docker sdk
- create and restore database backups
- deploy in a staging environment
- environment scaling
- getting started with cloud administration
- monitoring issues and informing about alerts
- performance testing in staging environments
- preparation for going live
- set up dns
- set up notifications for 5xx errors
- setting up a custom ssl certificate
- spryker cloud commerce os management
- starting asynchronous commands
- working with logs
Changed a link in the ca_dev_sidebar.yml, the email services > Verify email address was pointing to an older URL, updated so its a direct hit and …
> Cloud Admin Higher Level Pages SEO Update

- docs/ca/dev/access/connect-to-services-via-ssh.md
- docs/ca/dev/best-practices/best-practices.md
- docs/ca/dev/best-practices/best-practises-jenkins-stability.md
- docs/ca/dev/best-practices/jenkins-operational-best-practices.md
Changed the meta description for SEO update for the following pages:
- Access > Connect to services via ssh
- Best Practices > Best Practices
- Best Practices > Best Practices Jenkins Stability
- Best Practices > Jenkins Operation Best Practices - Also changed a few internal links that were being redirected to another page after clicking. updated to the new location.
`I hereby agree to Spryker\'s Contribution License Agreement in https://github.com/spryker/spryker-docs/blob/HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH/CONTRIBUTING.md …
> Cloud Admin Access and best Practices SEO updates

- docs/ca/dev/configure-deployment-pipelines/configure-azure-pipelines.md
- docs/ca/dev/configure-deployment-pipelines/configure-bitbucket-pipelines.md
- docs/ca/dev/configure-deployment-pipelines/configure-github-actions.md
- docs/ca/dev/configure-deployment-pipelines/configure-gitlab-pipelines.md
- docs/ca/dev/configure-deployment-pipelines/customize-deployment-pipelines.md
- docs/ca/dev/configure-deployment-pipelines/deployment-pipelines.md
Meta description changed for the following pages:
- Configure azure pipelines
- configure bitbucket pipelines
- configure bitbucket pipelines
- configure github actions
- configure github pipelines
- customize deployment pipelines
- deployment pipelines
This is a mandatory step to make sure you are aware of the license agreement and agree to it. …
> Cloud Admin Configure Deployment Pipelines SEO Update

- docs/ca/dev/security/generate-access-keys.md
- docs/ca/dev/security/penetration-testing.md
- docs/ca/dev/security/set-up-multi-factor-authentication.md
- docs/ca/dev/security/web-application-firewall-waf.md
- docs/ca/dev/set-up-a-custom-domain-name/set-up-a-custom-domain-name-with-a-third-party-dns-zone-provider.md
- docs/ca/dev/set-up-a-custom-domain-name/set-up-a-custom-domain-name-with-route-53.md
- docs/ca/dev/set-up-a-custom-domain-name/set-up-a-custom-domain-name.md
The following pages meta descriptions have been changed for an SEO Update.
- security > generate access keys
- security > penetration testing
- security > set up multi factor authentication
- security > web application firewall
- set up a custom domain name > set up a custom domain name with a third party dns zone provider
- set up a custom domain name > set up a custom domain name with route 53
- set up a custom domain name > set up a custom domain name
`I hereby agree to Spryker\'s Contribution License Agreement in …
> Cloud Admin security and  custom domain SEO updates

- docs/ca/dev/troubleshooting/troubleshooting-deployment-issues/deployment-fails-due-to-a-failed-docker-authentication.md
- docs/ca/dev/troubleshooting/troubleshooting-deployment-issues/troubleshooting-deployment-issues.md
- docs/ca/dev/troubleshooting/troubleshooting-general-issues/changing-a-source-branch-fails.md
- docs/ca/dev/troubleshooting/troubleshooting-general-issues/email-address-is-not-verified.md
- docs/ca/dev/troubleshooting/troubleshooting-general-issues/fatal-error-allowed-memory-size-of-x-bytes-exhausted.md
- docs/ca/dev/troubleshooting/troubleshooting-general-issues/troubleshooting-general-issues.md
- docs/ca/dev/troubleshooting/troubleshooting-tutorials/troubleshooting-tutorials.md
- docs/ca/dev/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-403-error.md
- docs/ca/dev/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-a-failed-deployment.md
- docs/ca/dev/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-a-killed-process.md
- docs/ca/dev/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-an-unavailable-zed.md
- docs/ca/dev/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-failed-jenkins-jobs.md
- docs/ca/dev/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-failing-yves-authentication.md
- docs/ca/dev/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-unavailable-yves-or-glue.md
- docs/ca/dev/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-yves-or-zed-not-restarting-after-deployment.md
- docs/ca/dev/troubleshooting/troubleshooting.md
Changed the meta Description for the following pages
- Deployment fails due to a failed docker authentication
- troubleshooting deployment issues
- changing a source branch fails
- email address is not verified
- fatal error allowed memory size of x bytes exhausted
- troubleshooting general issues -troubleshooting tutorials
-tutorial troubleshooting 403 error
-tutorial troubleshooting a failed deployment
-tutorial troubleshooting an unavailable zed
- tutorial troubleshooting a killed process
- tutorial troubleshooting failed jenkins jobs
- tutorial troubleshooting failing yves authentication
- tutorial troubleshooting unavailable yves or glue
- tutorial troubleshooting yves or zed not restarting after deployment
- troubleshooting
Link changes:
- email address is not verified, verifying …
> Cloud Admin Troubleshooting SEO Update

- _includes/pbc/all/install-features/202410.0/install-the-product-sets-feature.md
Add a meaningful description here that will let us know what you want to fix with this PR or what functionality you want to add.
This is a mandatory step to make sure you are aware of the license agreement and agree to it. `HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH` is a hash of the commit you are basing your branch from the master branch. You …
> FRW-7399: update integration guide

- docs/ca/dev/email-service/email-deliverability.md
- docs/ca/dev/email-service/email-quota-restrictions.md
- docs/ca/dev/email-service/email-service.md
- docs/ca/dev/manage-maintenance-mode/enable-and-disable-maintenance-mode.md
- docs/ca/dev/multi-store-setups/add-and-remove-databases-of-stores.md
- docs/ca/dev/multi-store-setups/checklist-for-a-new-store-implementation.md
- docs/ca/dev/multi-store-setups/multi-store-setups.md
- docs/ca/dev/multi-store-setups/multistore-setup-options.md
Changed the meta description for the following pages:
- email service > email deliverability
- email service > email quota restrictions
- email service > email service
- manage maintenance mode > enable and disable maintenance mode
- multi store setups > add and remove databases of stores
- multi store setups > checklist for a new store implementation
- multi store setups > multi store setups
- multi store setups > multistore setup options
Links updated from a redirected page to a direct page;
- email service > email quote restrictions , Verify email address link changed
- multi store setup > checklist for a new store implementation , related pages section link changed
- Please check out our contribution guide: …
> Cloud Admin Email Service & Manage Maintenance & Monitoring SEO Update

- docs/pbc/all/carrier-management/202410.0/base-shop/domain-model-and-relationships/shipment-method-entities-in-the-database-reference-information.md
- docs/pbc/all/carrier-management/202410.0/base-shop/import-and-export-data/import-carrier-management-data.md
- docs/pbc/all/carrier-management/202410.0/base-shop/import-and-export-data/import-file-details-shipment-method-store.csv.md
- docs/pbc/all/carrier-management/202410.0/base-shop/import-and-export-data/import-file-details-shipment-price.csv.md
- docs/pbc/all/carrier-management/202410.0/base-shop/import-and-export-data/import-file-details-shipment.csv.md
- docs/pbc/all/carrier-management/202410.0/base-shop/install-and-upgrade/install-features/install-the-shipment-approval-process-feature.md
- docs/pbc/all/carrier-management/202410.0/base-shop/install-and-upgrade/install-features/install-the-shipment-cart-feature.md
- docs/pbc/all/carrier-management/202410.0/base-shop/install-and-upgrade/install-the-shipment-glue-api.md
- docs/pbc/all/carrier-management/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-shipmentgui-module.md
- docs/pbc/all/carrier-management/202410.0/base-shop/manage-in-the-back-office/add-carrier-companies.md
- docs/pbc/all/carrier-management/202410.0/base-shop/manage-in-the-back-office/add-delivery-methods.md
- docs/pbc/all/carrier-management/202410.0/base-shop/manage-in-the-back-office/edit-delivery-methods.md
- docs/pbc/all/carrier-management/202410.0/base-shop/manage-in-the-back-office/manage-carrier-companies-and-delivery-methods-in-the-back-office.md
- docs/pbc/all/carrier-management/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-shipments-and-shipment-methods-when-submitting-checkout-data.md
- docs/pbc/all/carrier-management/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-shipments-in-orders.md
- docs/pbc/all/carrier-management/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-shipments-when-checking-out-purchases.md
- docs/pbc/all/carrier-management/202410.0/base-shop/manage-using-glue-api/manage-shipment-types/glue-api-add-shipment-types.md
- docs/pbc/all/carrier-management/202410.0/base-shop/manage-using-glue-api/manage-shipment-types/glue-api-retrieve-shipment-types.md
- docs/pbc/all/carrier-management/202410.0/base-shop/manage-using-glue-api/manage-shipment-types/glue-api-update-shipment-types.md
- docs/pbc/all/carrier-management/202410.0/base-shop/shipment-cart-feature-overview.md
- docs/pbc/all/carrier-management/202410.0/base-shop/third-party-integrations/seven-senders/install-and-configure-seven-senders.md
- docs/pbc/all/carrier-management/202410.0/base-shop/third-party-integrations/seven-senders/integrate-seven-senders.md
- docs/pbc/all/carrier-management/202410.0/base-shop/third-party-integrations/seven-senders/seven-senders-api-requests.md
- docs/pbc/all/carrier-management/202410.0/base-shop/third-party-integrations/seven-senders/seven-senders-mappers.md
- docs/pbc/all/carrier-management/202410.0/base-shop/third-party-integrations/seven-senders/seven-senders-persistance-layer.md
- docs/pbc/all/carrier-management/202410.0/carrier-management.md
- docs/pbc/all/carrier-management/202410.0/marketplace/install-features/install-marketplace-shipment-feature.md
- docs/pbc/all/carrier-management/202410.0/marketplace/install-features/install-the-marketplace-shipment-cart-feature.md
- docs/pbc/all/carrier-management/202410.0/unified-commerce/shipment-service-points-feature-overview.md
Meta Description changed for the following pages within Carrier Management: (note, only 202410 pages being changed at this moment)
- base shop > domain model and relationships > shipment method entities in the database reference information
- base shop > import and export data > import carrier management data
- base shop > import and export data >  import file details shipment method store
- base shop > import and export data > import file details shipment price
- base shop > import and export data > import file details shipment
- base shop > install and upgrade > install features > install the shipment approval process feature
- base shop > install and upgrade > install features > install the shipment cart feature
- base shop > install and upgrade > install the shipment glue api
- base …
> PBC Carrier Management SEO Update

- docs/pbc/all/back-office/202410.0/base-shop/back-office-translations-overview.md
- docs/pbc/all/back-office/202410.0/base-shop/configure-the-timezone-in-the-back-office.md
- docs/pbc/all/back-office/202410.0/base-shop/install-and-upgrade/install-the-back-office-number-formatting.md
- docs/pbc/all/back-office/202410.0/base-shop/install-and-upgrade/install-the-spryker-core-back-office-comments-feature.md
- docs/pbc/all/back-office/202410.0/base-shop/install-and-upgrade/install-the-spryker-core-back-office-feature.md
- docs/pbc/all/back-office/202410.0/base-shop/install-and-upgrade/upgrade-the-chart-module.md
Updated the meta description in PBC > Back Office > 202410 for;
- Back office Translations Overview
- Configure the timezone in the back office
- install the back office number formatting
- install the spryker core commerce back office comments feature
- install the spryker core back office feature
- upgrade the chart module
This is a mandatory step to make sure …
> PBC Back Office SEO Update

- docs/pbc/all/cart-and-checkout/202410.0/base-shop/cart-and-checkout-base-shop.md
- docs/pbc/all/cart-and-checkout/202410.0/base-shop/domain-model-and-relationships/checkout-feature-module-relations.md
- docs/pbc/all/cart-and-checkout/202410.0/base-shop/domain-model-and-relationships/comments-feature-module-relations.md
- docs/pbc/all/cart-and-checkout/202410.0/base-shop/domain-model-and-relationships/persistent-cart-sharing-feature-module-relations.md
- docs/pbc/all/cart-and-checkout/202410.0/base-shop/extend-and-customize/calculation-data-structure.md
Changed the meta description for the following pages following an SEO update;
- cart and checkout base shop
- checkout feature module relations
- comments feature module relations = persistent cart sharing feature module relations
- calculation data structure
This is a mandatory step to make sure you are aware of the license agreement and agree to it. …
> PBC Cart and checkout domain model and extend SEO update

- docs/pbc/all/payment-service-provider/202404.0/marketplace/stripe-third-party-integration/connect-and-configure-stripe-for-marketplace.md
Add a meaningful description here that will let us know what you want to fix with this PR or what functionality you want to add.
This is a mandatory step to make sure you are aware of the license agreement and agree to it. `HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH` is a hash of the commit you are basing your branch from the master branch. You …
> Update connect and configure stripe for marketplace

- docs/pbc/all/cart-and-checkout/202410.0/base-shop/manage-in-the-back-office/define-global-thresholds.md
- docs/pbc/all/cart-and-checkout/202410.0/base-shop/manage-in-the-back-office/manage-threshold-settings.md
- docs/pbc/all/cart-and-checkout/202410.0/base-shop/manage-in-the-back-office/manage-thresholds-the-back-office.md
- docs/pbc/all/cart-and-checkout/202410.0/base-shop/manage-using-glue-api/check-out/glue-api-check-out-purchases.md
- docs/pbc/all/cart-and-checkout/202410.0/base-shop/manage-using-glue-api/check-out/glue-api-checkout-workflow.md
- docs/pbc/all/cart-and-checkout/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-customer-carts.md
- docs/pbc/all/cart-and-checkout/202410.0/base-shop/manage-using-glue-api/share-company-user-carts/glue-api-manage-shared-company-user-carts.md
- docs/pbc/all/cart-and-checkout/202410.0/base-shop/manage-using-glue-api/share-company-user-carts/glue-api-retrieve-cart-permission-groups.md
- docs/pbc/all/cart-and-checkout/202410.0/base-shop/manage-using-glue-api/share-company-user-carts/glue-api-share-company-user-carts.md
- docs/pbc/all/cart-and-checkout/202410.0/base-shop/tutorials-and-howtos/add-additional-countries-to-checkout.md
- docs/pbc/all/cart-and-checkout/202410.0/base-shop/tutorials-and-howtos/define-if-carts-are-deleted-after-placing-an-order.md
- docs/pbc/all/cart-and-checkout/202410.0/base-shop/tutorials-and-howtos/enable-guest-checkout-in-the-b2b-demo-shop.md
- docs/pbc/all/cart-and-checkout/202410.0/base-shop/tutorials-and-howtos/handling-carts-with-a-big-number-of-items.md
- docs/pbc/all/cart-and-checkout/202410.0/cart-and-checkout.md
Changed the mate description for the following pages as an SEO update;
- manage in the back office > define global thresholds
- manage in the back office > manage threshold settings
- manage in the back office > manage thresholds the back office
- manage using glue API > glue api check out purchases
- manage using glue API > glue api checkout workflow
- manage using glue API > glue api retrieve customer carts
- manage using glue API > glue api manage shared company user carts
- manage using glue API > glue api retrieve cart permission groups
- manage using glue API > glue api share company user carts
- tutorials and how tos > add additional countries to checkout
- tutorials and how tos > define if carts are deleted after placing an order
- tutorials and how tos > enable guest checkout in …
> PBC Cart and Checkout BO GLUEAPI and Tutorials SEO Update

- docs/pbc/all/cart-and-checkout/202410.0/marketplace/install/install-features/install-the-cart-marketplace-product-offer-feature.md
- docs/pbc/all/cart-and-checkout/202410.0/marketplace/install/install-features/install-the-cart-marketplace-product-options-feature.md
- docs/pbc/all/cart-and-checkout/202410.0/marketplace/install/install-features/install-the-checkout-marketplace-product-offer-feature.md
- docs/pbc/all/cart-and-checkout/202410.0/marketplace/install/install-features/install-the-checkout-marketplace-product-options-feature.md
- docs/pbc/all/cart-and-checkout/202410.0/marketplace/install/install-features/install-the-quick-add-to-cart-marketplace-product-feature.md
- docs/pbc/all/cart-and-checkout/202410.0/marketplace/install/install-features/install-the-quick-add-to-cart-marketplace-product-offer-feature.md
- docs/pbc/all/cart-and-checkout/202410.0/marketplace/install/install-glue-api/install-the-cart-marketplace-product-glue-api.md
- docs/pbc/all/cart-and-checkout/202410.0/marketplace/install/install-glue-api/install-the-cart-marketplace-product-offer-glue-api.md
- docs/pbc/all/cart-and-checkout/202410.0/marketplace/manage-using-glue-api/carts-of-registered-users/manage-items-in-carts-of-registered-users.md
- docs/pbc/all/cart-and-checkout/202410.0/marketplace/marketplace-cart-feature-module-relations.md
Changed the meta description for the following pages for an SEO update:
- Install the cart marketplace product offer feature
- install the cart marketplace product options feature
- install the checkout marketplace product offer feature install the checkout marketplace product options feature
- install the quick add to cart marketplace product feature
- install the quick add to cart marketplace product offer feature
- install the cart marketplace product glue api
- install the cart marketplace product offer glue api
- manage items in carts of registered users
- marketplace cart feature module relations
- Add a …
> PBC Cart and Checktout Marketplace SEO Update

- docs/pbc/all/content-management-system/202410.0/base-shop/cms-feature-overview/cms-pages-overview.md
- docs/pbc/all/content-management-system/202410.0/base-shop/cms-feature-overview/email-as-a-cms-block-overview.md
- docs/pbc/all/content-management-system/202410.0/base-shop/domain-model-and-relationships/content-item-types-module-relations.md
- docs/pbc/all/content-management-system/202410.0/base-shop/domain-model-and-relationships/product-sets-feature-domain-model-and-relationships.md
- docs/pbc/all/content-management-system/202410.0/base-shop/extend-and-customize/navigation-module-reference-information.md
- docs/pbc/all/content-management-system/202410.0/base-shop/navigation-feature-overview.md
- docs/pbc/all/content-management-system/202410.0/base-shop/product-sets-feature-overview.md
- docs/pbc/all/content-management-system/202410.0/content-management-system.md
Changed the meta description for SEO updates on small groups of pages within the CMS section;
- base shop > cms feature overview > cms pages overview
- base shop > cms feature overview > cms as a cms block overview
- base shop > domain model and relationships > content item types module relations
- base shop > domain model and relationships > product sets feature domain model and relationships
- base shop > extend and customize > navigation module reference information
- base shop > navigation feature overview
- base shop > product sets feature overview
- content management system
- Add a `contribution-license-agreement.txt` …
> PBC CMS small page groups SEO Updates

- docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-content-management-system-data.md
- docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-block-category-postion.csv.md
- docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-block-category.csv.md
- docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-block-store.csv.md
- docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-block.csv.md
- docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-page-store.csv.md
- docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-page.csv.md
- docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-slot-block.csv.md
- docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-slot-template.csv.md
- docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-slot.csv.md
- docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-template.csv.md
- docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-content-banner.csv.md
- docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-content-navigation.csv.md
- docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-content-product-abstract-list.csv.md
- docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-content-product-set.csv.md
- docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-mime-type.csv.md
- docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-navigation-node.csv.md
- docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-navigation.csv.md
- docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-product-set.csv.md
Updated the following pages meta description for an SEO update
- import content management system data
- import file details cms block category position
- import file details cms block category
- import file details cms block store
- import file details cms page store
- import file details cms page
- import file details cms slot block
- import file details cms slot template
- import file details cms slots
- import file details content banner
- import file details content navigation
- import file details content product abstract list
- import file details content product set
- import file details mime type (also fixed a broken link in this article)
- import file details navigation node
- import file details navigation
- import file details product set
- Please add tests for the code you …
> PBC CMS Import Export SEO Update

- _data/sidebars/dg_dev_sidebar.yml
- _includes/pbc/all/install-features/202410.0/install-dynamic-multistore.md
- docs/ca/dev/multi-store-setups/multi-store-setups.md
- docs/dg/dev/internationalization-and-multi-store/managing-translations-with-twig-translator.md
- docs/dg/dev/internationalization-and-multi-store/tutorial-different-stores-different-logic-landing-pages.md
- docs/pbc/all/dynamic-multistore/202410.0/base-shop/dynamic-multistore-feature-overview.md
- docs/pbc/all/product-information-management/202311.0/base-shop/tutorials-and-howtos/tutorial-product.md
- docs/pbc/all/product-information-management/202404.0/base-shop/tutorials-and-howtos/tutorial-product.md
- docs/pbc/all/product-information-management/202410.0/base-shop/tutorials-and-howtos/tutorial-product.md
- docs/pbc/all/warehouse-management-system/202410.0/base-shop/extend-and-customize/manage-stocks-in-a-multi-store-environment-best-practices.md
https://spryker.atlassian.net/browse/FRW-8552
https://spryker.atlassian.net/browse/FRW-8551
> FRW-8551 Dynamic Multistore vs Multistore. + MultiDB.

- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/install-category-cms-blocks.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/install-features/install-the-cms-category-management-feature.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/install-features/install-the-cms-feature-dynamic-multistore.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/install-features/install-the-cms-feature.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/install-features/install-the-cms-product-lists-catalog-feature.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/install-features/install-the-product-sets-feature.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/install-glue-api/install-the-cms-glue-api.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/install-multi-store-cms-blocks.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/install-product-cms-blocks.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-cms-module.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-cmsblockcategoryconnector-migration-console-module.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-cmsblockcategoryconnector-module.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-cmsblockwidget-module.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-cmsgui-module.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-cmspagesearch-module.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-cmsstorage-module.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-content-module.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-contentbanner-module.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-contentbannergui-module.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-contentbannersrestapi-module.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-contentgui-module.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-contentstorage-module.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-navigation-module.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-navigationgui-module.md
- docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-navigationsrestapi-module.md
- docs/pbc/all/merchant-management/202410.0/marketplace/import-and-export-data/merchant-commission/import-file-details-merchant_commission_merchant.csv.md
- docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-back-office/back-office-import-merchant-commissions.md
Changed the meta description for an SEO update for the following pages;
- install category cms blocks
- install multi store cms blocks install product cms blocks
- install features > install the cms category management feature
- install features > install the cms feature dynamic multistore
- install features > install the cms feature
- install features > install the cms product lists catalog feature
- install features > install the product sets feature
- install glue api > install the cms glue api
- upgrade modules > upgrade the cms module
- upgrade modules >  upgrade the cms block category connector migration console module
- upgrade modules >  upgrade the cms block category connector module
- upgrade modules >  upgrade the cms block widget module
- upgrade modules >  upgrade the cms gui …
> PBC CMS Install and upgrade SEO update

- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/add-and-edit-mime-types.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/blocks/add-content-items-to-cms-blocks.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/blocks/create-category-cms-blocks.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/blocks/create-cms-blocks.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/blocks/create-email-cms-blocks.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/blocks/create-product-cms-blocks.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/blocks/edit-placeholders-in-cms-blocks.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/content-items/create-abstract-product-list-content-items.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/content-items/create-banner-content-items.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/content-items/create-file-list-content-items.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/content-items/create-navigation-content-items.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/content-items/create-product-set-content-items.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/manage-content-in-the-back-office.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/manage-slots.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/navigation/create-navigation-elements.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/navigation/create-navigation-nodes.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/navigation/delete-navigation-nodes.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/navigation/duplicate-navigation-elements.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/navigation/edit-navigation-elements.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/navigation/edit-navigation-nodes.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/pages/add-content-items-to-cms-pages.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/product-sets/create-product-sets.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/product-sets/delete-product-sets.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/product-sets/edit-product-sets.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/product-sets/reorder-product-sets.md
- docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/product-sets/view-product-sets.md
The following pages have had meta description changed for SEO update;
- add and edit mime types
- manage content in the back office
- manage slots
- blocks > add content items to cms blocks
- blocks > create category cms blocks
- blocks > create cms blocks
- blocks > create email cms blocks
- blocks > create product cms blocks
- blocks > edit placeholders in cms blocks
- content items > create abstract product list content items
- content items > create banner content items
- content items > create file list content items
- content items > create navigation content items
- content items > create product set content items
- navigation > create navigation elements
- navigation > create navigation nodes
- navigation > delete navigation nodes
- navigation > duplicate navigation elements
- …
> PBC CMS manage in the back office SEO update

- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/company-roles/create-company-roles.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/company-roles/edit-company-roles.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/company-unit-addresses/create-company-unit-addresses.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/company-unit-addresses/edit-company-unit-addresses.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/company-units/create-company-units.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/company-units/edit-company-units.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/company-users/create-company-users.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/company-users/edit-company-users.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/customers/add-customer-addresses.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/customers/add-notes-to-customers.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/customers/create-customers.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/customers/edit-customer-addresses.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/customers/edit-customers.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/customers/view-customers.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/manage-companies-and-customers-in-the-back-office.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/manage-customer-access.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/manage-customer-groups.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-business-unit-addresses.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-business-units.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-companies.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-company-roles.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-company-users.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/company-account/glue-api-search-by-company-users.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/customers/glue-api-manage-customer-addresses.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/customers/glue-api-manage-customers.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/customers/glue-api-retrieve-customer-orders.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/manage-customer-access-to-glue-api-resources.md
- docs/pbc/all/customer-relationship-management/202410.0/customer-relationship-management.md
Changed the meta description for SEO Update for the following pages in CRM PBC;
- Manage in the back office  > company roles > create company roles
- Manage in the back office  > company roles > edit company roles
- Manage in the back office  > company unit addresses > create company unit addresses
- Manage in the back office  > company unit addresses > edit company unit addresses
- Manage in the back office  > company units > create company unit
- Manage in the back office  > company units >  edit company unit
- Manage in the back office  > company users > create company users
- Manage in the back office  > company users > edit company users
- Manage in the back office  > customers > add customer addresses
- Manage in the back office  > customers >  add notes to customers
- Manage in the …
> PBC CRM Part 2 SEO Update

- docs/dg/dev/acp/install-prerequisites-and-enable-acp.md
The client found the broken code on the page:
> hotfix of the broken code in the `config_default.php`

- docs/dg/dev/backend-development/data-manipulation/payment-methods/invoice/implement-invoice-payment-in-backend.md
- docs/dg/dev/backend-development/data-manipulation/payment-methods/invoice/implement-invoice-payment-in-frontend.md
- docs/dg/dev/backend-development/data-manipulation/payment-methods/invoice/implement-invoice-payment-in-shared-layer.md
- docs/dg/dev/backend-development/data-manipulation/payment-methods/invoice/implement-invoice-payment.md
- docs/dg/dev/backend-development/data-manipulation/payment-methods/invoice/integrate-invoice-payment-into-checkout.md
- docs/dg/dev/backend-development/data-manipulation/payment-methods/invoice/test-the-invoice-payment-implementation.md
- docs/dg/dev/backend-development/data-manipulation/payment-methods/payment-methods.md
- docs/dg/dev/backend-development/data-manipulation/payment-methods/prepayment/implement-prepayment-in-backend.md
- docs/dg/dev/backend-development/data-manipulation/payment-methods/prepayment/implement-prepayment-in-frontend.md
- docs/dg/dev/backend-development/data-manipulation/payment-methods/prepayment/implement-prepayment-in-shared-layer.md
- docs/dg/dev/backend-development/data-manipulation/payment-methods/prepayment/implement-prepayment.md
- docs/dg/dev/backend-development/data-manipulation/payment-methods/prepayment/integrate-prepayment-into-checkout.md
- docs/dg/dev/backend-development/data-manipulation/payment-methods/prepayment/test-the-prepayment-implementation.md
- docs/dg/dev/backend-development/data-manipulation/queue/integrate-rabbitmq-headers-in-queue-messages.md
- docs/dg/dev/backend-development/data-manipulation/queue/queue-pool.md
- docs/dg/dev/backend-development/data-manipulation/queue/queue.md
- docs/dg/dev/backend-development/extend-spryker/create-modules.md
- docs/dg/dev/backend-development/extend-spryker/development-strategies.md
- docs/dg/dev/backend-development/extend-spryker/extend-spryker.md
Fix canonical links and metadescriptions
> SEO update for dev guide 2

- docs/pbc/all/dynamic-multistore/202410.0/base-shop/add-fields-to-back-office-forms.md
- docs/pbc/all/dynamic-multistore/202410.0/base-shop/delete-stores.md
- docs/pbc/all/dynamic-multistore/202410.0/base-shop/dynamic-multistore-feature-overview.md
- docs/pbc/all/dynamic-multistore/202410.0/base-shop/install-and-upgrade/install-features/install-dynamic-multistore.md
- docs/pbc/all/dynamic-multistore/202410.0/base-shop/install-and-upgrade/install-the-dynamic-multistore-glue-api.md
- docs/pbc/all/dynamic-multistore/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-country-module.md
- docs/pbc/all/dynamic-multistore/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-currency-module.md
- docs/pbc/all/dynamic-multistore/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-locale-module.md
- docs/pbc/all/dynamic-multistore/202410.0/dynamic-multistore.md
changed the meta description for the following pages for an SEO update;
- add fields to back office forms
- delete stores
- dynamic multistore feature overview
- dynamic multistore -install and upgrade > install features > install dynamic multistore -install and upgrade > install the dynamic multistore glue api -install and upgrade >  upgrade modules > upgrade the country module -install and upgrade >  upgrade modules > upgrade the currency module -install and upgrade >  upgrade modules > upgrade the locale module
`I hereby agree to Spryker\'s …
> PBC DMS SEO Update

- docs/pbc/all/discount-management/202410.0/base-shop/import-and-export-data/import-discount-management-data.md
- docs/pbc/all/discount-management/202410.0/base-shop/import-and-export-data/import-file-details-discount-amount.csv.md
- docs/pbc/all/discount-management/202410.0/base-shop/import-and-export-data/import-file-details-discount-store.csv.md
- docs/pbc/all/discount-management/202410.0/base-shop/import-and-export-data/import-file-details-discount-voucher.csv.md
- docs/pbc/all/discount-management/202410.0/base-shop/import-and-export-data/import-file-details-discount.csv.md
- docs/pbc/all/discount-management/202410.0/base-shop/install-and-upgrade/install-features/install-the-promotions-and-discounts-category-management-feature.md
- docs/pbc/all/discount-management/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-discount-module.md
- docs/pbc/all/discount-management/202410.0/base-shop/manage-in-the-back-office/best-practices-promote-products-with-discounts.md
- docs/pbc/all/discount-management/202410.0/base-shop/manage-in-the-back-office/create-discounts.md
- docs/pbc/all/discount-management/202410.0/base-shop/manage-in-the-back-office/export-voucher-codes.md
- docs/pbc/all/discount-management/202410.0/base-shop/manage-in-the-back-office/manage-discounts-in-the-back-office.md
- docs/pbc/all/discount-management/202410.0/base-shop/manage-using-glue-api/glue-api-add-items-with-discounts-to-guest-carts.md
- docs/pbc/all/discount-management/202410.0/base-shop/manage-using-glue-api/glue-api-manage-discount-vouchers-in-guest-carts.md
- docs/pbc/all/discount-management/202410.0/base-shop/manage-using-glue-api/glue-api-manage-discounts.md
- docs/pbc/all/discount-management/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-discounts-in-guest-carts.md
- docs/pbc/all/discount-management/202410.0/discount-management.md
Changed the meta description for the following pages for the SEO update;
- base shop > import and export data > import discount management data
- base shop > import and export data > import file details discount amount csv
- base shop > import and export data > import file discount store
- base shop > import and export data > import file discount voucher csv
- base shop > import and export data > import file details discount csv
- base shop > install and upgrade > install features > install the promotions and discounts category management feature
- base shop  > install and upgrade >  upgrade modules > upgrade the discount module
- base shop  > manage in the back office > best practices promote products with discounts
- base shop >> manage in the back office >  create discounts
- base shop …
> PBC Discount Management SEO Update

- docs/pbc/all/identity-access-management/202410.0/identity-access-management.md
- docs/pbc/all/identity-access-management/202410.0/install-and-upgrade/install-the-customer-access-glue-api.md
- docs/pbc/all/identity-access-management/202410.0/install-and-upgrade/install-the-customer-account-management-glue-api.md
- docs/pbc/all/identity-access-management/202410.0/install-and-upgrade/install-the-spryker-core-back-office-feature.md
- docs/pbc/all/identity-access-management/202410.0/install-and-upgrade/upgrade-the-oauth-module.md
- docs/pbc/all/identity-access-management/202410.0/install-and-upgrade/upgrade-the-oauthcompanyuser-module.md
- docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-authenticate-as-a-back-office-user.md
- docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-authenticate-as-a-company-user.md
- docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-authenticate-as-an-agent-assist.md
- docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-confirm-customer-registration.md
- docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-create-customers.md
- docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-delete-expired-refresh-tokens.md
- docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-manage-agent-assist-authentication-tokens.md
- docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-manage-company-user-authentication-tokens.md
- docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-manage-customer-authentication-tokens.md
- docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-manage-customer-passwords.md
The following pages meta description has been updated for an SEO Update;
- Identity Access Management
- Install and upgrade > install the customer access glue api
- Install and upgrade > install the customer account management glue api
- Install and upgrade > install the spryker core back office feature
- Install and upgrade > upgrade the oauth module
- Install and upgrade > upgrade the oauth company users module
- manage using glue api > glue api authenticate as a back office user
- manage using glue api > glue api authenticate as a company user
- manage using glue api > glue api authenticate as an agent assist
- manage using glue api > glue api confirm customer registration
- manage using glue api > glue api create customers
- manage using glue api > glue api delete expired refresh …
> PBC IAM SEO Update

- docs/pbc/all/business-intelligence/202410.0/amazon-quicksight-third-party-integration/back-office-refresh-analytics-datasets.md
- docs/pbc/all/business-intelligence/202410.0/amazon-quicksight-third-party-integration/best-practices-working-with-analytics.md
- docs/pbc/all/business-intelligence/202410.0/amazon-quicksight-third-party-integration/manage-analytics-users-and-roles.md
important qs fixes
Add a meaningful description here that will let us know what you want to fix with this PR or what functionality you want to add.
This is a mandatory step to make sure you are aware of the license agreement and agree to it. `HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH` is a hash of the commit you are basing your branch from the …
> important qs fixes

- docs/about/all/support/general-product-safety-regulation.md
Made a few changes to the formatting and wording of the article.
This is a mandatory step to make sure you are aware of the license agreement and agree to it. `HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH` is a hash of the commit you are basing your branch from the master branch. You can take it from commits list of master branch before you submit …
> Gpsr updates

- docs/ca/dev/configure-deployment-pipelines/configure-azure-pipelines.md
Update documentation for Azure DevOps repo mirroring
> Azure pipeline documentation update

- docs/pbc/all/gift-cards/202410.0/import-and-export-data/import-file-details-gift-card-abstract-configuration.csv.md
- docs/pbc/all/gift-cards/202410.0/import-and-export-data/import-file-details-gift-card-concrete-configuration.csv.md
- docs/pbc/all/gift-cards/202410.0/import-and-export-data/import-gift-cards-data.md
- docs/pbc/all/gift-cards/202410.0/install-and-upgrade/enable-gift-cards.md
- docs/pbc/all/gift-cards/202410.0/install-and-upgrade/install-the-gift-cards-feature.md
- docs/pbc/all/gift-cards/202410.0/manage-using-glue-api/glue-api-retrieve-gift-cards-in-carts-of-registered-users.md
- docs/pbc/all/gift-cards/202410.0/manage-using-glue-api/glue-api-retrieve-gift-cards-in-guest-carts.md
Changed the meta description for the following pages for an SEO update;
- import file details gift card abstract configuration csv
- import file details gift card concrete configuration csv
- import gift cards data
- enable gift cards
- install the gift cards feature
- glue api retrieve gift cards in carts of registered users
- glue api retrieve gift cards in guest carts
`I hereby agree to Spryker\'s Contribution License Agreement in https://github.com/spryker/spryker-docs/blob/HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH/CONTRIBUTIN …
> PBC Gift Cards SEO Update

- docs/pbc/all/payment-service-provider/202410.0/base-shop/import-and-export-data/import-file-details-payment-method-store.csv.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/import-and-export-data/import-file-details-payment-method.csv.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/import-and-export-data/payment-service-provider-data-import-and-export.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/install-and-upgrade/install-the-payments-feature.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/install-and-upgrade/install-the-payments-glue-api.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/install-and-upgrade/upgrade-the-payment-module.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/manage-in-the-back-office/manage-payment-methods-in-the-back-office.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/manage-in-the-back-office/view-payment-methods.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/adyen/install-and-configure-adyen.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/adyen/integrate-adyen.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/afterpay/install-and-configure-afterpay.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/afterpay/integrate-afterpay.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/billie.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/billpay/billpay-switch-invoice-payments-to-a-preauthorize-mode.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/billpay/billpay.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/billpay/integrate-billpay.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/braintree/integrate-braintree.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/computop/install-and-configure-computop.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/computop/integrate-computop.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/computop/integrate-payment-methods-for-computop/integrate-the-ideal-payment-method-for-computop.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/computop/integrate-payment-methods-for-computop/integrate-the-paypal-payment-method-for-computop.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/computop/integrate-payment-methods-for-computop/integrate-the-sofort-payment-method-for-computop.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/crefopay/crefopay-callbacks.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/crefopay/crefopay-enable-b2b-payments.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/crefopay/crefopay.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/heidelpay/heidelpay-oms-workflow.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/heidelpay/heidelpay-workflow-for-errors.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/heidelpay/integrate-payment-methods-for-heidelpay/integrate-the-ideal-payment-method-for-heidelpay.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/heidelpay/integrate-payment-methods-for-heidelpay/integrate-the-sofort-payment-method-for-heidelpay.md
Changed meta description for pages within PBC Payment Service provider. also fixed the broken links on the install and configure adyen page.
This is a mandatory step to make sure you are aware of the license agreement and agree to it. `HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH` is a hash of the commit you are basing your branch from the master …
> PBC PSP pt1 SEO Update

- docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/manage-orders-in-the-back-office.md
- docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/orders/change-the-state-of-order-items.md
- docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/orders/comment-orders.md
- docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/orders/create-returns.md
- docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/orders/create-shipments.md
- docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/orders/edit-billing-addresses-in-orders.md
- docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/orders/edit-shipments.md
- docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/orders/view-returns-of-an-order.md
- docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/reclamations/create-reclamations.md
- docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/reclamations/view-reclamations.md
- docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/view-refunds.md
- docs/pbc/all/order-management-system/202410.0/base-shop/order-management-feature-overview/custom-order-reference-overview.md
- docs/pbc/all/order-management-system/202410.0/base-shop/order-management-feature-overview/oms-order-management-system-matrix.md
- docs/pbc/all/order-management-system/202410.0/base-shop/order-management-feature-overview/order-cancellation-overview.md
- docs/pbc/all/order-management-system/202410.0/base-shop/order-management-feature-overview/order-management-feature-overview.md
- docs/pbc/all/order-management-system/202410.0/base-shop/state-machine-cookbook/state-machine-cookbook-state-machine-fundamentals.md
- docs/pbc/all/order-management-system/202410.0/base-shop/state-machine-cookbook/state-machine-cookbook.md
- docs/pbc/all/order-management-system/202410.0/base-shop/third-party-integrations/nekom-cc-gmbh.md
- docs/pbc/all/order-management-system/202410.0/marketplace/create-merchant-oms-flows.md
- docs/pbc/all/order-management-system/202410.0/marketplace/glue-api-retrieve-marketplace-orders.md
- docs/pbc/all/order-management-system/202410.0/marketplace/import-and-export-data/export-file-details-merchant-order-expenses.csv.md
- docs/pbc/all/order-management-system/202410.0/marketplace/import-and-export-data/export-file-details-merchant-orders.csv.md
- docs/pbc/all/order-management-system/202410.0/marketplace/import-and-export-data/marketplace-import-and-export-order-management-system-data.md
- docs/pbc/all/order-management-system/202410.0/marketplace/install-features/install-the-marketplace-order-management-merchant-portal-feature.md
- docs/pbc/all/order-management-system/202410.0/marketplace/manage-in-the-back-office/manage-marketplace-orders-in-the-back-office.md
- docs/pbc/all/order-management-system/202410.0/marketplace/marketplace-order-management-feature-overview/marketplace-order-management-feature-overview.md
- docs/pbc/all/order-management-system/202410.0/marketplace/marketplace-order-management-feature-overview/marketplace-order-overview.md
- docs/pbc/all/order-management-system/202410.0/order-management-system.md
The following pages have been changed pt2 for SEO update;
- base shop > manage in the back office > manage orders in the back office
- base shop > manage in the back office > orders > change the state of order items
- base shop > manage in the back office > orders > comment orders
- base shop > manage in the back office > orders > create returns
- base shop > manage in the back office > orders > create shipments
- base shop > manage in the back office > orders > edit billing addresses in orders
- base shop > manage in the back office > orders > edit shipments
- base shop > manage in the back office > orders > view returns of an order
- base shop > manage in the back office > reclamations > create reclamations
- base shop > manage in the back office > reclamations > view reclamations
- …
> PBC OMS Pt2 SEO Update

- docs/pbc/all/customer-relationship-management/202410.0/base-shop/customer-account-management-feature-overview/customer-accounts-overview.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/customer-account-management-feature-overview/customer-login-overview.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/customer-account-management-feature-overview/customer-registration-overview.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/customer-account-management-feature-overview/password-management-overview.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/domain-model-and-relationships/company-account-module-relations.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/domain-model-and-relationships/customer-login-by-token-reference-information.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/generate-login-tokens.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/import-and-export-data/file-details-customer.csv.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/install-and-upgrade/install-features/install-the-company-account-feature.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/install-and-upgrade/install-features/install-the-company-account-merchant-b2b-contract-requests-feature.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/install-and-upgrade/install-features/install-the-company-account-merchant-b2b-contracts-feature.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/install-and-upgrade/install-glue-api/install-the-company-account-glue-api.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/install-and-upgrade/install-glue-api/install-the-customer-account-management-glue-api.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-companybusinessunit-module.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-companyuserauthrestapi-module.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-companyusersrestapi-module.md
- docs/pbc/all/customer-relationship-management/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-sharedcartpage-module.md
Changed the following meta description for an SEO Update;
- customer account management feature overview > customer accounts overview
- customer account management feature overview >  customer login overview
- customer account management feature overview > customer registration overview
- customer account management feature overview > password management overview
- domain model and relationships > company account module relations
- domain model and relationships >  customer login by token reference information
- generate login tokens
- import and export data > file details customer
- install and upgrade > install the company account feature
- install and upgrade >  install the company account merchant b2b contract requests feature
- install and upgrade >  install the company account …
> PBC CRM Part 1 SEO Update

- docs/pbc/all/merchant-management/202410.0/base-shop/install-and-upgrade/install-the-merchant-b2b-contract-requests-comments-feature.md
- docs/pbc/all/merchant-management/202410.0/base-shop/install-and-upgrade/install-the-merchant-b2b-contract-requests-company-account-feature.md
- docs/pbc/all/merchant-management/202410.0/base-shop/install-and-upgrade/install-the-merchant-b2b-contracts-comments-feature.md
- docs/pbc/all/merchant-management/202410.0/base-shop/install-and-upgrade/install-the-merchant-b2b-contracts-company-account-feature.md
- docs/pbc/all/merchant-management/202410.0/base-shop/install-and-upgrade/install-the-merchant-feature.md
- docs/pbc/all/merchant-management/202410.0/base-shop/install-and-upgrade/install-the-merchants-and-merchant-relations-feature.md
- docs/pbc/all/merchant-management/202410.0/base-shop/manage-in-the-back-office/create-merchant-relations.md
- docs/pbc/all/merchant-management/202410.0/base-shop/manage-in-the-back-office/create-merchants.md
- docs/pbc/all/merchant-management/202410.0/base-shop/manage-in-the-back-office/edit-merchant-relations.md
- docs/pbc/all/merchant-management/202410.0/base-shop/manage-in-the-back-office/edit-merchants.md
- docs/pbc/all/merchant-management/202410.0/base-shop/manage-in-the-back-office/manage-merchants-in-the-back-office.md
The follow pages meta description have changed for an SEO update;
- install the merchant b2b contract requests comments feature
- install the merchant b2b contract requests company account feature
- install the merchant b2b contracts comments feature
- install the merchant b2b contracts company account feature
- install the merchant feature
- install the merchants and merchant relations feature
- create merchant relations
- create merchants
- edit merchant relations
- edit merchants
- manage merchants in the back office
`I hereby agree to …
> PBC Merchant Management Base Shop SEO Update

- docs/pbc/all/merchant-management/202410.0/marketplace/domain-model-and-relationships/marketplace-merchant-feature-domain-model.md
- docs/pbc/all/merchant-management/202410.0/marketplace/domain-model-and-relationships/merchant-category-feature-domain-model.md
- docs/pbc/all/merchant-management/202410.0/marketplace/import-and-export-data/import-file-details-merchant-category.csv.md
- docs/pbc/all/merchant-management/202410.0/marketplace/import-and-export-data/import-file-details-merchant-profile-address.csv.md
- docs/pbc/all/merchant-management/202410.0/marketplace/import-and-export-data/import-merchant-management-data.md
- docs/pbc/all/merchant-management/202410.0/marketplace/import-and-export-data/merchant-commission/import-file-details-merchant-comission.csv.md
- docs/pbc/all/merchant-management/202410.0/marketplace/import-and-export-data/merchant-commission/import-file-details-merchant_commission_amount.csv.md
- docs/pbc/all/merchant-management/202410.0/marketplace/import-and-export-data/merchant-commission/import-file-details-merchant_commission_group.csv.md
- docs/pbc/all/merchant-management/202410.0/marketplace/import-and-export-data/merchant-commission/import-file-details-merchant_commission_merchant.csv.md
- docs/pbc/all/merchant-management/202410.0/marketplace/import-and-export-data/merchant-commission/import-file-details-merchant_commission_store.csv.md
- docs/pbc/all/merchant-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-commission-product-feature.md
- docs/pbc/all/merchant-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-feature.md
- docs/pbc/all/merchant-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-portal-core-feature.md
- docs/pbc/all/merchant-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-portal-product-offer-management-feature.md
- docs/pbc/all/merchant-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-merchant-portal-marketplace-merchant-portal-product-offer-management-merchant-portal-order-management-feature.md
- docs/pbc/all/merchant-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-merchant-portal-marketplace-order-management-feature.md
- docs/pbc/all/merchant-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-merchant-portal-marketplace-product-inventory-management-feature.md
- docs/pbc/all/merchant-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-merchant-portal-marketplace-product-tax-feature.md
- docs/pbc/all/merchant-management/202410.0/marketplace/install-and-upgrade/install-the-merchant-portal.md
- docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-back-office/back-office-import-merchant-commissions.md
- docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-back-office/manage-merchant-relations/create-merchant-relations.md
- docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-back-office/manage-merchant-relations/edit-merchant-relations.md
Following pages meta desc changed for SEO update;
- domain model and relationships > marketplace merchant feature domain model
- domain model and relationships > merchant category feature domain model
- import and export data > import file details merchant category csv
- import and export data > import file details merchant profile address csv
- import and export data > import merchant management data
- import and export data > merchant commission > import file details merchant commission csv
- import and export data > merchant commission > import file details merchant commission amount csv
- import and export data > merchant commission > import file details merchant commission group csv
- import and export data > merchant commission > import file details merchant commission merchant csv …
> PBC Pt1 Merchant Management Marketplace SEO Update

- docs/pbc/all/order-management-system/202410.0/base-shop/datapayload-conversion/multi-language-setup.md
- docs/pbc/all/order-management-system/202410.0/base-shop/datapayload-conversion/state-machine/state-machine-console-commands.md
- docs/pbc/all/order-management-system/202410.0/base-shop/datapayload-conversion/step-engine/step-engine-workflow-overview.md
- docs/pbc/all/order-management-system/202410.0/base-shop/display-custom-names-for-order-item-states-on-the-storefront.md
- docs/pbc/all/order-management-system/202410.0/base-shop/domain-model-and-relationships/custom-order-reference-module-relations.md
- docs/pbc/all/order-management-system/202410.0/base-shop/glue-api-retrieve-orders.md
- docs/pbc/all/order-management-system/202410.0/base-shop/import-and-export-data/import-and-export-order-management-system-data.md
- docs/pbc/all/order-management-system/202410.0/base-shop/import-and-export-data/orders-data-export/export-file-details-order-expenses.csv.md
- docs/pbc/all/order-management-system/202410.0/base-shop/import-and-export-data/orders-data-export/export-file-details-order-items.csv.md
- docs/pbc/all/order-management-system/202410.0/base-shop/import-and-export-data/orders-data-export/export-file-details-orders.csv.md
- docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/install-features/install-the-reclamations-feature.md
- docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/install-features/install-the-sales-data-export-feature.md
- docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/install-features/install-the-splittable-order-items-feature.md
- docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/install-glue-api/install-the-checkout-glue-api.md
- docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/install-glue-api/install-the-order-management-glue-api.md
- docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/install-glue-api/install-the-shipment-glue-api.md
- docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-oms-module.md
- docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-ordersrestapi-module.md
- docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-sales-module.md
- docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-salesquantity-module.md
- docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-salessplit-module.md
part 1 of meta description updates with the order management system:
- base shop > datapayload conversion > multi-language
- base shop > datapayload conversion > state machine console commands
- base shop > datapayload conversion > step engine > step engine workflow overview
- base shop > display custon names for order items states on the storefront
- base shop > glue api retrieve orders
- base shop > domain model and relationships > custom order reference module relations
- base shop > import and export data > import and export order management system data
- base shop > import and export data >  orders data export > export file details order expenses csv
- base shop > import and export data >  orders data export > export file details order items csv
- base shop > import and export data > …
> PBC OMS pt1 SEO Update

- docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-back-office/manage-merchant-users/create-merchant-users.md
- docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-back-office/manage-merchant-users/edit-merchant-users.md
- docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-back-office/manage-merchants/create-merchants.md
- docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-merchant-portal/manage-merchant-relation-requests.md
- docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-merchant-portal/manage-merchant-relations.md
- docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-merchant-portal/manage-merchants-in-the-merchant-portal.md
- docs/pbc/all/merchant-management/202410.0/marketplace/manage-using-glue-api/glue-api-retrieve-merchant-addresses.md
- docs/pbc/all/merchant-management/202410.0/marketplace/manage-using-glue-api/glue-api-retrieve-merchant-opening-hours.md
- docs/pbc/all/merchant-management/202410.0/marketplace/manage-using-glue-api/glue-api-retrieve-merchants.md
- docs/pbc/all/merchant-management/202410.0/marketplace/marketplace-merchant-commission-feature-overview.md
- docs/pbc/all/merchant-management/202410.0/marketplace/marketplace-merchant-portal-core-feature-overview/gui-modules.md
- docs/pbc/all/merchant-management/202410.0/marketplace/marketplace-merchant-portal-core-feature-overview/merchant-user.md
- docs/pbc/all/merchant-management/202410.0/marketplace/marketplace-merchant-portal-core-feature-overview/persistence-acl-configuration.md
- docs/pbc/all/merchant-management/202410.0/marketplace/merchant-category-feature-overview.md
- docs/pbc/all/merchant-management/202410.0/marketplace/third-party-integrations/channelpilot-marketplace.md
- docs/pbc/all/merchant-management/202410.0/marketplace/tutorials-and-howtos/create-gui-modules.md
- docs/pbc/all/merchant-management/202410.0/marketplace/tutorials-and-howtos/create-gui-table-column-types.md
- docs/pbc/all/merchant-management/202410.0/marketplace/tutorials-and-howtos/create-gui-table-filter-types.md
- docs/pbc/all/merchant-management/202410.0/marketplace/tutorials-and-howtos/create-gui-tables.md
- docs/pbc/all/merchant-management/202410.0/marketplace/tutorials-and-howtos/create-merchant-commission-calculator-type-plugins.md
- docs/pbc/all/merchant-management/202410.0/marketplace/tutorials-and-howtos/create-merchant-commission-collector-rule.md
- docs/pbc/all/merchant-management/202410.0/marketplace/tutorials-and-howtos/extend-gui-tables.md
- docs/pbc/all/merchant-management/202410.0/marketplace/tutorials-and-howtos/extend-merchant-portal-dashboard.md
- docs/pbc/all/merchant-management/202410.0/merchant-management.md
the following pages have had their meta description changed for an SEO update;
- manage in back office > manage merchant users > create merchant users
- manage in back office > manage merchant users > edit merchant users
- manage in back office > manage merchants > create merchants
- manage in back office > manage in the merchant portal > manage merchant relation requests
- manage in back office > manage in the merchant portal > manage merchant relations
- manage in back office > manage in the merchant portal > manage merchants in the merchant portal
- manage in back office > manage using glue api > glue api retrieve merchant addresses
- manage in back office > manage using glue api > glue api retrieve merchant opening hours
- manage in back office > manage using glue api > glue api …
> PBC Pt2 Merchant Management Marketplace SEO update

- docs/pbc/all/offer-management/202410.0/base-shop/upgrade-modules/upgrade-the-offer-module.md
- docs/pbc/all/offer-management/202410.0/base-shop/upgrade-modules/upgrade-the-offergui-module.md
- docs/pbc/all/offer-management/202410.0/marketplace/glue-api-retrieve-product-offers.md
- docs/pbc/all/offer-management/202410.0/marketplace/import-and-export-data/import-file-details-product-offer-shipment-type.csv.md
- docs/pbc/all/offer-management/202410.0/marketplace/import-and-export-data/import-offer-management-data.md
- docs/pbc/all/offer-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-portal-product-offer-management-feature.md
- docs/pbc/all/offer-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-portal-product-offer-management-merchant-portal-order-management-merchant-portal-feature.md
- docs/pbc/all/offer-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-offer-cart-feature.md
- docs/pbc/all/offer-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-offer-checkout-feature.md
- docs/pbc/all/offer-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-offer-marketplace-product-feature.md
- docs/pbc/all/offer-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-offer-quick-add-to-cart-feature.md
- docs/pbc/all/offer-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-product-offer-shipment-availability-feature.md
- docs/pbc/all/offer-management/202410.0/marketplace/install-and-upgrade/install-glue-api/install-the-marketplace-product-offer-cart-glue-api.md
- docs/pbc/all/offer-management/202410.0/marketplace/install-and-upgrade/install-glue-api/install-the-marketplace-product-offer-wishlist-glue-api.md
- docs/pbc/all/offer-management/202410.0/marketplace/manage-in-the-merchant-portal/create-product-offers.md
- docs/pbc/all/offer-management/202410.0/marketplace/manage-in-the-merchant-portal/manage-product-offers-in-the-merchant-portal.md
- docs/pbc/all/offer-management/202410.0/marketplace/marketplace-product-offer-feature-domain-model-and-relationships/marketplace-product-offer-feature-domain-model-and-relationships.md
- docs/pbc/all/offer-management/202410.0/marketplace/product-offer-shipment-availability-feature-overview.md
- docs/pbc/all/offer-management/202410.0/marketplace/render-merchant-product-offers-on-the-storefront.md
- docs/pbc/all/offer-management/202410.0/offer-management.md
- docs/pbc/all/offer-management/202410.0/unified-commerce/glue-api-retrieve-product-offer-service-point-availability.md
- docs/pbc/all/offer-management/202410.0/unified-commerce/import-file-details-product-offer-service.csv.md
- docs/pbc/all/offer-management/202410.0/unified-commerce/install-features/install-the-marketplace-product-offer-service-points-feature.md
- docs/pbc/all/offer-management/202410.0/unified-commerce/product-offer-service-feature-overview.md
- docs/pbc/all/offer-management/202410.0/unified-commerce/product-offer-service-points-availability-feature.md
- docs/pbc/all/offer-management/202410.0/unified-commerce/unified-commerce-create-and-edit-product-offers.md
changed the following pages meta description for an SEO update;
- base shop > upgrade modules > upgrade the offer module
- base shop > upgrade modules > upgrade the offer gui module
- marketplace > glue api retrieve product offers
- marketplace > import and export data > import file details product offer shipment type csv
- marketplace > import and export data > import offer management
- marketplace > install and upgrade > install features > install the marketplace merchant portal product offer management feature
- marketplace > install and upgrade > install features > install the marketplace merchant portal product offer management merchant portal order management merchant portal feature
- marketplace > install and upgrade > install features > install the marketplace product offer cart …
> PBC Offer Management SEO Update

- docs/pbc/all/return-management/202410.0/base-shop/build-a-return-management-process-best-practices.md
- docs/pbc/all/return-management/202410.0/base-shop/manage-in-the-back-office/change-the-state-of-order-items-in-returns.md
- docs/pbc/all/return-management/202410.0/base-shop/manage-in-the-back-office/manage-returns-in-the-back-office.md
- docs/pbc/all/return-management/202410.0/base-shop/manage-in-the-back-office/manage-returns.md
- docs/pbc/all/return-management/202410.0/base-shop/set-number-of-days-for-a-return-policy.md
- docs/pbc/all/return-management/202410.0/marketplace/glue-api-manage-marketplace-returns.md
Meta desc changed for some pages within Return Management for an SEO update;
- base shop > build a return management process best practices
- base shop > manage in the back office > change the state of order items in reteurns
- base shop > manage in the back office > manage returns in the back office
- base shop > manage in the back office > manage returns
- base shop > set number of days for a return policy
- marketplace > glue api manage marketplace returns
`I hereby agree to Spryker\'s Contribution License Agreement in …
> PBC Return Management SEO Update

- docs/pbc/all/product-information-management/202410.0/base-shop/third-party-integrations/akeneo/akeneo-connector-eco-module-console-commands.md
- docs/pbc/all/product-information-management/202410.0/base-shop/third-party-integrations/censhare-pim.md
- docs/pbc/all/product-information-management/202410.0/base-shop/tutorials-and-howtos/howto-display-product-groups-by-color-on-the-storefront.md
- docs/pbc/all/product-information-management/202410.0/base-shop/tutorials-and-howtos/howto-render-configurable-bundle-templates-in-the-storefront.md
- docs/pbc/all/product-information-management/202410.0/base-shop/tutorials-and-howtos/product-data-from-import-to-frontend-views.md
- docs/pbc/all/product-information-management/202410.0/base-shop/tutorials-and-howtos/split-products-by-stores.md
- docs/pbc/all/product-information-management/202410.0/base-shop/tutorials-and-howtos/tutorial-product.md
- docs/pbc/all/product-information-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-marketplace-product-offer-feature.md
- docs/pbc/all/product-information-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-merchant-portal-tax-feature.md
- docs/pbc/all/product-information-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-options-cart-feature.md
- docs/pbc/all/product-information-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-options-feature.md
- docs/pbc/all/product-information-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-quick-add-to-cart-feature.md
- docs/pbc/all/product-information-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-product-marketplace-merchant-commission-feature.md
- docs/pbc/all/product-information-management/202410.0/marketplace/install-and-upgrade/install-glue-api/install-the-marketplace-product-cart-glue-api.md
- docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-back-office/manage-marketplace-products-in-the-back-office.md
- docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-back-office/product-options/manage-product-options.md
- docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-back-office/product-options/product-options.md
- docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-back-office/products/abstract-products/abstract-products.md
- docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-back-office/products/abstract-products/create-abstract-products.md
- docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-back-office/products/abstract-products/edit-abstract-products.md
- docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-back-office/products/create-product-variants.md
- docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-back-office/products/products.md
- docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-merchant-portal/concrete-products/edit-marketplace-concrete-products.md
- docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-merchant-portal/manage-products-in-the-merchant-portal.md
- docs/pbc/all/product-information-management/202410.0/marketplace/manage-using-glue-api/glue-api-retrieve-concrete-products.md
- docs/pbc/all/product-information-management/202410.0/marketplace/manage-using-glue-api/glue-api-retrieve-product-offers-of-concrete-products.md
- docs/pbc/all/product-information-management/202410.0/marketplace/marketplace-product-feature-overview.md
- docs/pbc/all/product-information-management/202410.0/product-information-management.md
following meta desc changed for pages within the PIM section of docs;
- base shop > third party integrations > akeneo > akeneo connector eco module console commands
- base shop > third party integrations > censhare pim
- base shop > tutorials and how tos > how to display product groups by color on the storefront
- base shop > tutorials and how tos > how to render configurable bundle templates in the storefront
- base shop > tutorials and how tos > product data from import to frontend views
- base shop > tutorials and how tos > split product by stores
- base shop > tutorials and how tos > tutorial product
- marketplace > install and upgrade > install features > install the marketplace product marketplace product offer feature
- marketplace > install and upgrade > install features > install …
> PBC PIM Marketplace SEO Update

- docs/pbc/all/product-relationship-management/202410.0/build-your-own-product-relation-type.md
- docs/pbc/all/product-relationship-management/202410.0/import-file-details-product-relation.csv.md
- docs/pbc/all/product-relationship-management/202410.0/install-and-upgrade/install-the-product-relations-feature.md
- docs/pbc/all/product-relationship-management/202410.0/install-and-upgrade/upgrade-the-productrelationstorage-module.md
- docs/pbc/all/product-relationship-management/202410.0/manage-in-the-back-office/best-practices-promote-products-with-product-relations.md
- docs/pbc/all/product-relationship-management/202410.0/manage-in-the-back-office/create-product-relations.md
- docs/pbc/all/product-relationship-management/202410.0/manage-in-the-back-office/edit-product-relations.md
- docs/pbc/all/product-relationship-management/202410.0/manage-in-the-back-office/manage-product-relations-in-the-back-office.md
- docs/pbc/all/product-relationship-management/202410.0/manage-in-the-back-office/view-product-relations.md
- docs/pbc/all/product-relationship-management/202410.0/product-relations-module-relations.md
- docs/pbc/all/product-relationship-management/202410.0/third-party-integrations/8select.md
- docs/pbc/all/product-relationship-management/202410.0/third-party-integrations/contentserv.md
- docs/pbc/all/product-relationship-management/202410.0/third-party-integrations/econda/export-econda-data.md
- docs/pbc/all/product-relationship-management/202410.0/third-party-integrations/econda/install-econda.md
- docs/pbc/all/product-relationship-management/202410.0/third-party-integrations/econda/integrate-econda-cross-selling.md
- docs/pbc/all/product-relationship-management/202410.0/third-party-integrations/econda/integrate-econda.md
- docs/pbc/all/product-relationship-management/202410.0/third-party-integrations/nosto.md
Updated the meta desc for the following pages for an SEO update within Product relationship management ;
- build your own product relation type
- import file details product relation
- product relations module relations
- install and upgrade > install the product relations feature
- install and upgrade > upgrade the product relation store module
- manage in the back office > best practices promote product with product relations
- install and upgrade > create product relations
- install and upgrade > edit product relations
- install and upgrade > manage product relations in the back office
- install and upgrade > view product relations
- third party integrations > 8select
- third party integrations > contentserv
- third party integrations > nosto
- third party integrations > econda > …
> PBC PRM SEO Update

- docs/pbc/all/ratings-reviews/202410.0/import-and-export-data/import-file-details-product-review.csv.md
- docs/pbc/all/ratings-reviews/202410.0/import-and-export-data/ratings-and-reviews-data-import.md
- docs/pbc/all/ratings-reviews/202410.0/manage-product-reviews-in-the-back-office.md
- docs/pbc/all/ratings-reviews/202410.0/manage-using-glue-api/glue-api-manage-product-reviews.md
- docs/pbc/all/ratings-reviews/202410.0/manage-using-glue-api/glue-api-retrieve-product-reviews-when-retrieving-concrete-products.md
- docs/pbc/all/ratings-reviews/202410.0/ratings-and-reviews.md
- docs/pbc/all/ratings-reviews/202410.0/third-party-integrations/bazaarvoice.md
- docs/pbc/all/ratings-reviews/202410.0/third-party-integrations/configure-bazaarvoice.md
- docs/pbc/all/ratings-reviews/202410.0/third-party-integrations/disconnect-bazaarvoice.md
- docs/pbc/all/ratings-reviews/202410.0/third-party-integrations/integrate-bazaarvoice.md
- docs/pbc/all/ratings-reviews/202410.0/tutorials-and-howtos/howto-configure-product-reviews.md
the following pages have the meta desc changed for an SEO update;
- import and export data > import file details product review csv
- import and export data > ratings and reviews data import
- manage product reviews in the back office
- ratings and reviews
- manage using glue api > glue api manage product reviews
- manage using glue api > glue api retrieve product reviews when retrieving concrete products
- third party integrations > bazaarvoice
- third party integrations > configure bazaarvoice
- third party integrations > disconnect bazaarvoice
- third party integrations > integrate bazaarvoice tutorials and how tos > how to configure product reviews
- Please check out our contribution guide: …
> PBC Ratings and Reviews SEO Update

- docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/install-features/install-the-quotation-process-approval-process-feature.md
- docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/install-features/install-the-quotation-process-feature.md
- docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/install-features/install-the-quotation-process-glue-api.md
- docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/install-features/install-the-quotation-process-multiple-carts-feature.md
- docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/upgrade-modules/upgrade-the-quoterequest-module.md
- docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/upgrade-modules/upgrade-the-quoterequestagent-module.md
- docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/upgrade-modules/upgrade-the-quoterequestagentpage-module.md
- docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/upgrade-modules/upgrade-the-quoterequestagentwidget-module.md
- docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/upgrade-modules/upgrade-the-quoterequestpage-module.md
- docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/upgrade-modules/upgrade-the-quoterequestwidget-module.md
- docs/pbc/all/request-for-quote/202410.0/request-for-quote.md
- docs/pbc/all/request-for-quote/202410.0/use-cases-request-for-quote-processes.md
meta desc changed for the following pages under RFQ;
- install and upgrade > install features > install thte quoatation process approvval process feature
- install and upgrade > install features > install the quotation process feature
- install and upgrade > install features > install the quotation process glue api
- install and upgrade > install features > install the quotation process multople carts feature
- install and upgrade > upgrade modules > upgrade the quoterequest module
- install and upgrade > upgrade modules > upgrade the quote request agent module
- install and upgrade > upgrade modules > upgrade the quote request agent page module
- install and upgrade > upgrade modules > upgrade the quote request agent widget module
- install and upgrade > upgrade modules > upgrade the …
> PBC RFQ SEO Update

- _includes/pbc/all/upgrade-modules/upgrade-the-twig-module.md
- docs/dg/dev/integrate-and-configure/twig-and-twigextension.md
Ticket: https://spryker.atlassian.net/browse/FRW-9287
> FRW-9287 Updated twig integration guide.

- docs/pbc/all/service-point-management/202410.0/service-point-management.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/enable-click-collect.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/import-and-export-data/import-file-details-service-point-address.csv.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/import-and-export-data/import-file-details-service-point-store.csv.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/import-and-export-data/import-file-details-service-point.csv.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/import-and-export-data/import-file-details-service-type.csv.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/import-and-export-data/import-file-details-service.csv.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/install-features/install-the-service-points-cart-feature.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/install-features/install-the-service-points-feature.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-service-point-addresses/glue-api-add-service-point-addresses.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-service-point-addresses/glue-api-retrieve-service-point-addresses.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-service-point-addresses/glue-api-update-service-point-addresses.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-service-points/glue-api-add-service-points.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-service-points/glue-api-retrieve-service-points.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-service-points/glue-api-update-service-points.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-service-types/glue-api-add-service-types.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-service-types/glue-api-retrieve-service-types.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-service-types/glue-api-update-service-types.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-services/glue-api-add-services.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-services/glue-api-retrieve-services.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-services/glue-api-update-services.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/service-points-cart-checkout-feature-overview.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/service-points-cart-feature-overview.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/service-points-feature-overview.md
- docs/pbc/all/service-point-management/202410.0/unified-commerce/service-points-order-management-feature.md
following pages amended meta desc for an SEO update;
- service point management
- unified commerce > enable click and collect
- unified commerce > service points cart checkout feature overview
- unified commerce > service points cart feature overview
- unified commerce > service points feature overview
- unified commerce > service points order management
- unified commerce > import and export data > import file details service point address csv
- unified commerce > import and export data > import file details service point store csv
- unified commerce > import and export data > import file details service point csv
- unified commerce > import and export data > import file details service type csv
- unified commerce > import and export data > import file details service csv
- unified …
> PBC Service Point SEO Update

- docs/ca/devscu/configure-spryker-code-upgrader.md
> SUPESC-930: Updated doc to use json value without whitespaces.

- docs/pbc/all/payment-service-provider/202410.0/base-shop/retrieve-and-use-payment-details-from-third-party-psps.md
Added description for the newly added feature to have the External Payment App payment states displayed in the back office.
https://spryker.atlassian.net/browse/ACP-4656
> ACP-4656 Added Payment History description for SalesPaymentDetails.

- docs/pbc/all/business-intelligence/202410.0/amazon-quicksight-third-party-integration/install-amazon-quicksight.md
Ticket: https://spryker.atlassian.net/browse/CC-35134
> CC-20504 Fixed SQL Exception when opening the Quote Products dataset.

- docs/about/all/about-spryker.md
- docs/dg/dev/guidelines/performance-guidelines/architecture-performance-guidelines.md
- docs/pbc/all/order-management-system/202410.0/base-shop/datapayload-conversion/state-machine/common-pitfalls-in-oms-design.md
> about and fix bug

- docs/ca/dev/monitoring.md
- docs/ca/dev/spryker-monitoring-integration.md
- docs/dg/dev/integrate-and-configure/configure-services.md
> Davide branch into Spryker OTEL

- _data/sidebars/pbc_all_sidebar.yml
- docs/pbc/all/back-office/202410.0/base-shop/install-and-upgrade/back-office-accessibility-integration-guide.md
- docs/pbc/all/back-office/202410.0/base-shop/install-and-upgrade/install-back-office-accessibility-improvements.md
> BO A11y integration guide

- docs/ca/dev/add-variables-in-the-parameter-store.md
- docs/ca/dev/connect-a-code-repository.md
> quick fixes

- docs/dg/dev/guidelines/performance-guidelines/general-performance-guidelines.md
Merchant portal performance documentation
> Merchant portal performance documentation

- docs/pbc/all/search/202410.0/base-shop/third-party-integrations/algolia/integrate-algolia.md
Update documentation for the algolia integration
> Update documentation for the algolia integration

- _data/sidebars/ca_dev_sidebar.yml
- docs/about/all/releases/release-notes-202410.0.md
- docs/ca/dev/configure-debugging.md
- docs/ca/dev/monitoring/monitoring-issues-and-informing-about-alerts.md
- docs/ca/dev/monitoring/spryker-monitoring-integration.md
- docs/ca/dev/monitoring/working-with-logs.md
> restructure monitoring docs

- _data/sidebars/ca_dev_sidebar.yml
- docs/ca/dev/access/access-the-aws-management-console.md
- docs/ca/dev/security/multi-factor-authentication-and-passwords.md
Added note about recent change to enforce MFA and linked respective MFA set up document and brief troubleshooting
> MFA enforcement note

- _data/sidebars/about_all_sidebar.yml
- docs/about/all/self-service-portal.md
> add ssp intro

- docs/about/all/releases/security-release-notes-202412.0.md
> Security release notes description fix

- _includes/pbc/all/install-features/202505.0/install-the-cart-feature.md
Added a new configuration.
https://spryker.atlassian.net/browse/CC-26244
> CC-26244 [Performance] Quote is validated twice in Yves CartController

- docs/ca/dev/monitoring/spryker-monitoring-integration/opentelemetry-instrumentation.md
> Added PHP version to Otel documentation

- docs/dg/dev/guidelines/performance-guidelines/general-performance-guidelines.md
- Removed old (from 2019-2020 year) optimization module recommendations.
- added new
> Performance optimization update

- docs/about/all/self-service-portal.md
- docs/pbc/all/order-management-system/202410.0/base-shop/order-management-feature-overview/invoice-generation-overview.md
> Legal and SSP updates

- docs/ca/dev/connect-a-code-repository.md
- docs/dg/dev/acp/install-prerequisites-and-enable-acp.md
- docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-macos-and-linux.md
- docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-windows.md
- docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-macos-and-linux.md
- docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-windows.md
- docs/dg/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-macos-and-linux.md
- docs/dg/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-windows.md
- docs/pbc/all/discount-management/202410.0/marketplace/marketplace-promotions-discounts-feature-overview.md
> Legal connection

- Gemfile.lock
- _includes/topnav.html
- docs/pbc/all/multi-factor-authentication/202505.0/multi-factor-authentication.md
- docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/vertex/install-vertex/install-vertex.md
- docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/vertex/install-vertex/integrate-the-vertex-app.md
- docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/vertex/install-vertex/integrate-vertex-validator.md
removed the text [beta] from showing in the  top nav for PBC
> removed beta from top nav

- docs/dg/dev/internationalization-and-multi-store/adding-stores-in-a-multi-database-setup.md
> Fixing table format for the new store config

- docs/pbc/all/ratings-reviews/202311.0/third-party-integrations/bazaarvoice.md
- docs/pbc/all/ratings-reviews/202311.0/third-party-integrations/configure-bazaarvoice.md
- docs/pbc/all/ratings-reviews/202404.0/third-party-integrations/bazaarvoice.md
- docs/pbc/all/ratings-reviews/202404.0/third-party-integrations/configure-bazaarvoice.md
- docs/pbc/all/ratings-reviews/202410.0/third-party-integrations/bazaarvoice.md
- docs/pbc/all/ratings-reviews/202410.0/third-party-integrations/configure-bazaarvoice.md
fixed outdated Bazaarvoice links, based on issues raised
- https://github.com/spryker/spryker-docs/issues/2822
- https://github.com/spryker/spryker-docs/issues/2823
- https://github.com/spryker/spryker-docs/issues/2824
- https://github.com/spryker/spryker-docs/issues/2826
- https://github.com/spryker/spryker-docs/issues/2827
- https://github.com/spryker/spryker-docs/issues/2828
> fix bazaarvoice links

- _data/sidebars/dg_dev_sidebar.yml
- docs/dg/dev/upgrade-and-migrate/upgrade-to-angular-18.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/debug-payment-integrations-locally.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/adyen/install-and-configure-adyen.md
- docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/product-options/import-file-details-product-option-price.csv.md
- docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/products-data-import/import-file-details-product-abstract-approval-status.csv.md
https://spryker.atlassian.net/browse/CC-35247
> CC-35253: Update Angular to 18

- docs/ca/devscu/prepare-a-project-for-spryker-code-upgrader.md
https://spryker.atlassian.net/browse/SUPESC-971
> SUPESC-971: Fixed min php version for upgrader

- _data/sidebars/dg_dev_sidebar.yml
- docs/dg/dev/guidelines/performance-guidelines/general-performance-guidelines.md
- docs/dg/dev/integrate-and-configure/integrate-automated-svg-sprite-extraction.md
- docs/dg/dev/integrate-and-configure/integrate-svg-sprite-asset.md
https://spryker.atlassian.net/browse/SUPESC-899
> SUPESC-899 Svg sprite asset generation integration

- Rakefile
- docs/dg/dev/set-up-spryker-locally/configure-after-installing/set-up-a-self-signed-ssl-certificate.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/billpay/billpay-switch-invoice-payments-to-a-preauthorize-mode.md
- docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/powerpay.md
Update set-up-a-self-signed-ssl-certificate with updated date as the page got updated recently.
> Update set-up-a-self-signed-ssl-certificate with updated date

- docs/dg/dev/set-up-spryker-locally/redis-configuration.md
> FRW-10389 Adjusted redis doc.

- docs/dg/dev/set-up-spryker-locally/redis-configuration.md
https://spryker.atlassian.net/browse/FRW-10455 Added information for storage gui.
> FRW-10455: Added information how to enable StorageGui module

- _includes/pbc/all/install-features/202410.0/marketplace/install-the-merchant-portal-agent-assist-feature.md
- Added FE-related changes for the feature documentation
https://spryker.atlassian.net/browse/CC-34706
> CC-34706: Added FE related docs for agent assist mode at MP

- _includes/pbc/all/content-management-system/manage-in-the-back-office/navigation/reference-information-navigation-node-types.md
- docs/dg/dev/updating-spryker/analyzing-and-upgrading-projects-with-spryker-jarvis.md
- docs/dg/dev/updating-spryker/updating-spryker.md
- docs/pbc/all/return-management/latest/base-shop/return-management-feature-overview.md
> Wistia vids

- _data/sidebars/about_all_sidebar.yml
- docs/about/all/releases/release-notes-202507.0.md
- docs/dg/dev/acp/install-prerequisites-and-enable-acp.md
- docs/dg/dev/acp/receive-acp-messages.md
> ACP-5302: Added missing and adjusted incorrect ACP installation steps

- _includes/pbc/all/install-features/latest/install-self-service-portal.md
- _includes/pbc/all/install-features/latest/install-the-order-amendment-feature.md
- _includes/pbc/all/install-features/latest/install-the-ssp-asset-management-feature.md
- _includes/pbc/all/install-features/latest/install-the-ssp-dashboard-management-feature.md
- _includes/pbc/all/install-features/latest/install-the-ssp-file-management-feature.md
- _includes/pbc/all/install-features/latest/install-the-ssp-inquiry-management-feature.md
- _includes/pbc/all/install-features/latest/install-the-ssp-service-management-feature.md
- docs/about/all/self-service-portal.md
- docs/dg/dev/acp/app-composition-platform.md
- docs/pbc/all/business-intelligence/202410.0/amazon-quicksight-third-party-integration/install-amazon-quicksight.md
- docs/pbc/all/self-service-portal/latest/self-service-portal.md
- docs/pbc/all/self-service-portal/latest/ssp-asset-management-feature-overview.md
- docs/pbc/all/self-service-portal/latest/ssp-dashboard-management-feature-overview.md
- docs/pbc/all/self-service-portal/latest/ssp-file-management-feature-overview.md
- docs/pbc/all/self-service-portal/latest/ssp-inquiry-management-feature-overview.md
- docs/pbc/all/self-service-portal/latest/ssp-service-management-feature-overview.md
Ticket: https://spryker.atlassian.net/browse/CC-35690
> CC-35690 Adjusted Quicksight IG.

- _includes/pbc/all/install-features/latest/marketplace/install-the-merchant-portal-data-import-feature.md
Enhance and improve readability of plugin registration examples for Merchant Portal Data Import feature
- https://spryker.atlassian.net/browse/CC-35488
> Improve plugin registration examples for Merchant Portal Data Import feature

- _includes/pbc/all/install-features/latest/install-the-agent-assist-cart-feature.md
- _includes/pbc/all/install-features/latest/install-the-agent-assist-feature.md
Integration guide updates for the ticket: https://spryker.atlassian.net/browse/CC-36205
in 1 month.
> CC-36205: Agent Assist: Information about the agent who submitted Order (Fixathon)

- _data/sidebars/integrations.yml
- docs/integrations/spryker-glue-api/authenticating-and-authorization/integrate-a-ciam-provider.md
> added CIAM page in
