docs/scos/dev/feature-integration-guides/202009.0/cms-feature-integration.md
Typo with functions in src/Pyz/Zed/EventBehavior/EventBehaviorDependencyProvider.php:
new CmsPageEventResourceQueryContainerPluginCmsBlockEventResourceQueryContainerPlugin(),
new CmsBlockEventResourceQueryContainerPluginCmsEventResourceQueryContainerPlugin(),
new CmsEventResourceQueryContainerPluginCmsSlotBlockEventResourceBulkRepositoryPlugin(),
new CmsSlotBlockEventResourceBulkRepositoryPluginCmsSlotEventResourceBulkRepositoryPlugin(),
new CmsSlotEventResourceBulkRepositoryPluginContentStorageEventResourceBulkRepositoryPlugin(),
=> Typo in code snippet

docs/scos/dev/back-end-development/data-manipulation/data-publishing/handling-data-with-publish-and-synchronization.md
I fixed a name of a method that doesn't belong to QueueDependencyProvider and corrected QueueQueueDependencyProvider to Queue\QueueDependencyProvider.
TBD
=> QueueQueue and a method name typoes

docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-macos-and-linux.md
This step is not necessary, and the yaml is not correct afterwards (with the colon in both the image: and the tag:), resulting in the build failing.
It's fine to leave as it is in the repo.
=> remove unnecessary breaking step in install instructions

docs/scos/dev/back-end-development/data-manipulation/data-publishing/handling-data-with-publish-and-synchronization.md
The mentioned code can't even work, because there is no `$messageIds` variable. Looks like we're providing a single id to the `store` method and therefore don't need to iterate at all in that method, because this is already done in the `deleteCollectionByHelloWorldEvents` method.
=> Fix store method in HelloWorldStorageDeleter

docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-demo-mode-on-macos-and-linux.md, docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-demo-mode-on-windows.md, docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-macos-and-linux.md, docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-windows.md
Update installing-in-demo-mode-on-macos-and-linux for 202204.0 to have a fluent getting-started for developers
Update installing-in-demo-mode-on-macos-and-linux for 202204.0 to have the getting-started working again
=> Update getting-started for 202204.0

docs/scos/dev/feature-integration-guides/202204.0/glue-api/glue-api-product-feature-integration.md
Concrete Data should be included when concrete-products are requested and vice versa with abstract-products
This change should also be made in the demo shops
=> Update Confusing Plugin Usage

docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-demo-mode-on-windows.md, docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-windows.md
Problem statement: Several users did oversee the hint for the "hostnames per line" limitation.
The adjustment includes the following:
- changed order of "hostnames per line"-limitation-hint
- made some warning to notices
- changed order of hosts-file adjustment to after bootstrap-section
- applied the rule of max. 10 hostnames per file for demo-mode
=> Makes line-size limit in hosts file for windows users more highlighted

docs/scos/user/intro-to-spryker/contribute-to-documentation/build-the-documentation-site.md
Added M1 Mac Jekyll install steps. Changed and reordered Mac install steps because Homebrew installs command line tools and GCC automatically.
=> Add m1 mac jekyll install steps

_includes/pbc/all/install-features/202204.0/install-the-product-bundles-feature.md
Following the [Product Bundle feature integration](https://docs.spryker.com/docs/scos/dev/feature-integration-guides/202204.0/product-bundles-feature-integration.html) causes the following error when trying to execute `console propel:install`.
```
In PropelSchemaMerger.php line 112:
Ambiguous use of name, package and namespace in schema file "spy_product_bundle_storage.schema.xml"  
```
This is caused by the mismatching namespace with [src/Spryker/Zed/ProductBundleStorage/Persistence/Propel/Schema/spy_product_bundle_storage.schema.xml](https://github.com/spryker/product-bundle-storage/blob/1.1.0/src/Spryker/Zed/ProductBundleStorage/Persistence/Propel/Schema/spy_product_bundle_storage.schema.xml).
=> Fix code snippet in Product Bundles feature integration guide

docs/scos/user/intro-to-spryker/whats-new/php8-as-a-minimum-version-for-all-spryker-projects.md
With the 8.0 as a version, I get an error
```
roave/better-reflection[5.0.0, ..., 5.10.x-dev] require php ~8.0.12 || ~8.1.0 -> your php version (8.0; overridden via config.platform, actual: 8.0.19) does not satisfy that requirement
```
and the fix shown has resolved the problem.
=> minor PHP version update

docs/scos/dev/back-end-development/data-manipulation/data-publishing/handle-data-with-publish-and-synchronization.md
Without this missing part, the example code errors out because the `filterByIdHelloWorldMessage_In` can't handle the array of `EventEntityTransfer`s: it kept trying to put those entire transfer objects into the SQL, which resulted in errors.
TBD
=> Fixed example code

docs/cloud/dev/spryker-cloud-commerce-os/multi-store-setups/checklist-for-a-new-store-implementation.md, docs/cloud/dev/spryker-cloud-commerce-os/multi-store-setups/multistore-setup-options.md, docs/scos/dev/tutorials-and-howtos/howtos/howto-set-up-multiple-stores.md
=> Multistore docs fixes

docs/scos/user/intro-to-spryker/docs-release-notes.md
=> Adjusting the docs release notes page

docs/cloud/dev/spryker-cloud-commerce-os/add-variables-in-the-parameter-store.md
=> Add disclaimer about customer-owned and spryker-owned variables

docs/cloud/dev/spryker-cloud-commerce-os/add-variables-in-the-parameter-store.md
=> added reserved variable sub-section. Plus, removed deprecated text.

docs/scos/dev/glue-api-guides/202212.0/old-glue-infrastructure/glue-infrastructure.md, docs/scos/dev/glue-api-guides/202212.0/old-glue-infrastructure/glue-rest-api.md, docs/scos/dev/glue-api-guides/202212.0/old-glue-infrastructure/handling-concurrent-rest-requests-and-caching-with-entity-tags.md, docs/scos/dev/glue-api-guides/202212.0/old-glue-infrastructure/reference-information-glueapplication-errors.md, docs/scos/dev/glue-api-guides/202212.0/old-glue-infrastructure/resolving-search-engine-friendly-urls.md, docs/scos/dev/glue-api-guides/202212.0/old-glue-infrastructure/rest-api-b2b-reference.md, docs/scos/dev/glue-api-guides/202212.0/old-glue-infrastructure/rest-api-b2c-reference.md
This PR adds missing redirects to the docs in the `/docs/scos/dev/glue-api-guides/202212.0/old-glue-infrastructure` folder.
Jira task: https://spryker.atlassian.net/browse/DOC-169
TBD
=> add missing redirects

docs/scos/dev/back-end-development/data-manipulation/data-publishing/handle-data-with-publish-and-synchronization.md
It fixes a typo in the instructions for the creation of spy_helloworld_message_storage table
TBD
=> Fixes typo in persistence folder's name

docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/security-update.md
Ticket: https://spryker.atlassian.net/browse/SDK-2491
=> SDK-4093. Added Security update checker doc

docs/marketplace/dev/feature-walkthroughs/202307.0/persistence-acl-feature-walkthrough/execution-flow.md, docs/marketplace/dev/feature-walkthroughs/202307.0/persistence-acl-feature-walkthrough/rules-and-scopes/rules-and-scopes.md
=> Tables for rules and scopes + execution flow fix

_includes/pbc/all/install-features/202400.0/install-the-shipment-feature.md, docs/pbc/all/carrier-management/202400.0/base-shop/install-and-upgrade/install-features/install-the-shipment-feature.md
https://spryker.atlassian.net/browse/CC-31052
https://github.com/spryker/spryker-shop/pull/2381
=> Install the shipment feature

docs/scos/dev/front-end-development/202307.0/oryx/dependency-injection/dependency-injection-advanced-strategies.md, docs/scos/dev/front-end-development/202307.0/oryx/dependency-injection/dependency-injection-defining-services.md, docs/scos/dev/front-end-development/202307.0/oryx/dependency-injection/dependency-injection-providing-services.md, docs/scos/dev/front-end-development/202307.0/oryx/dependency-injection/dependency-injection-using-services.md, docs/scos/dev/front-end-development/202307.0/oryx/dependency-injection/dependency-injection.md, docs/scos/dev/front-end-development/202307.0/oryx/dependency-injection/oryx-service-layer.md, docs/scos/dev/front-end-development/202307.0/oryx/oryx-application-orchestration/oryx-application-environment.md, docs/scos/dev/front-end-development/202307.0/oryx/oryx-application-orchestration/oryx-application-feature.md, docs/scos/dev/front-end-development/202307.0/oryx/oryx-application-orchestration/oryx-application-orchestration.md, docs/scos/dev/front-end-development/202307.0/oryx/oryx-application-orchestration/oryx-application-plugins.md, docs/scos/dev/front-end-development/202307.0/oryx/oryx-application-orchestration/oryx-application.md, docs/scos/dev/front-end-development/202307.0/oryx/oryx-boilerplate.md, docs/scos/dev/front-end-development/202307.0/oryx/oryx-compositions.md, docs/scos/dev/front-end-development/202307.0/oryx/oryx-feature-sets.md, docs/scos/dev/front-end-development/202307.0/oryx/oryx-packages.md, docs/scos/dev/front-end-development/202307.0/oryx/oryx-presets.md, docs/scos/dev/front-end-development/202307.0/oryx/oryx-routing.md, docs/scos/dev/front-end-development/202307.0/oryx/oryx-server-side-rendering.md, docs/scos/dev/front-end-development/202307.0/oryx/oryx-supported-browsers.md, docs/scos/dev/front-end-development/202307.0/oryx/oryx-versioning.md, docs/scos/dev/front-end-development/202307.0/oryx/oryx.md, docs/scos/dev/front-end-development/202307.0/oryx/reactivity/key-concepts-of-reactivity.md, docs/scos/dev/front-end-development/202307.0/oryx/reactivity/oryx-integration-of-backend-apis.md, docs/scos/dev/front-end-development/202307.0/oryx/reactivity/reactive-components.md, docs/scos/dev/front-end-development/202307.0/oryx/reactivity/reactivity.md, docs/scos/dev/front-end-development/202307.0/oryx/set-up-oryx.md, docs/scos/dev/front-end-development/202307.0/oryx/styling/oryx-color-system.md, docs/scos/dev/front-end-development/202307.0/oryx/styling/oryx-design-tokens.md, docs/scos/dev/front-end-development/202307.0/oryx/styling/oryx-typography.md
Before 1.0 we've improved the package layers slightly to prevent cycle dependencies in the layered package architecture.
=> fix: align package documentation with latest changes

docs/pbc/all/search/202400.0/base-shop/third-party-integrations/integrate-algolia.md
=> Removed not needed plugin

docs/pbc/all/search/202307.0/base-shop/third-party-integrations/algolia/algolia.md
=> Upadating the video for Algolia

docs/pbc/all/tax-management/202400.0/base-shop/vertex/install-vertex.md
Ticket: https://spryker.atlassian.net/browse/PBC-3053
TBD
=> PBC-3053: Update Vertex integration guide.

docs/pbc/all/tax-management/202400.0/base-shop/vertex/install-vertex.md
Ticket: https://spryker.atlassian.net/browse/PBC-3077
- Updated Vertex integration guide according to latest changes in integration process.
=> PBC-3077 Update Vertex integration guide

_data/sidebars/scos_user_sidebar.yml, docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202309.0/security-release-notes-202309.0.md, docs/scos/user/intro-to-spryker/releases/release-notes/security-release-notes-202306.0.md, docs/scos/user/intro-to-spryker/releases/release-notes/security-release-notes-202309.0.md
This PR contains the security release notes for Q3.
=> Sec release notes q3

_data/sidebars/scos_dev_sidebar.yml, docs/scos/dev/glue-api-guides/202307.0/authentication-and-authorization.md, docs/scos/dev/glue-api-guides/202307.0/glue-api-guides.md, docs/scos/dev/glue-api-guides/202307.0/use-api-key-authorization.md, docs/scos/dev/migration-concepts/migrate-to-decoupled-glue-infrastructure/decoupled-glue-infrastructure-integrate-api-key-authorization.md
Ticket: https://spryker.atlassian.net/browse/FRW-2426
=> FRW-2426 API Key authorization documentation

docs/pbc/all/back-office/202307.0/back-office-translations-overview.md
According to our public demoshops it looks like the path for Zed translations is wrong in the documentation. See https://github.com/spryker-shop/b2b-demo-marketplace/blob/master/data/translation/README.md
=> Fix wrong path for adding/overriding Zed translations

_includes/pbc/all/install-features/202311.0/install-the-product-feature.md, docs/pbc/all/product-information-management/202311.0/base-shop/install-and-upgrade/install-features/install-the-product-feature.md
=> Updating the product feature ig

_includes/pbc/all/install-features/202400.0/install-the-service-points-cart-checkout-feature.md, _includes/pbc/all/install-features/202400.0/install-the-service-points-cart-feature.md, docs/pbc/all/service-points/202400.0/unified-commerce/install-and-upgrade/install-the-service-points-cart-checkout-feature.md
Tickets:
- https://spryker.atlassian.net/browse/CC-30030
- https://spryker.atlassian.net/browse/CC-30476
Epics:
- https://spryker.atlassian.net/browse/CC-26572
- https://spryker.atlassian.net/browse/CC-29672
=> Install the Service Points Cart + Checkout feature

_data/sidebars/pbc_all_sidebar.yml, docs/pbc/all/search/202311.0/base-shop/third-party-integrations/algolia/integrate-algolia.md, docs/scos/user/intro-to-spryker/docs-updates.md
=> Docs updates 10.2023

_data/sidebars/pbc_all_sidebar.yml, _data/sidebars/scos_user_sidebar.yml, docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/configure-vertex.md, docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/vertex-faq.md, docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/vertex.md, docs/pbc/all/tax-management/202311.0/tax-management.md
=> Vertex overview page

docs/pbc/all/cart-and-checkout/202204.0/base-shop/feature-overviews/approval-process-feature-overview.md
=> Fixed Redirect

docs/scos/dev/front-end-development/202311.0/oryx/getting-started/oryx-boilerplate.md, docs/scos/dev/front-end-development/202311.0/oryx/getting-started/set-up-oryx.md
Closes [HRZ-89573](https://spryker.atlassian.net/browse/HRZ-89573)
[HRZ-89573]: https://spryker.atlassian.net/browse/HRZ-89573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> oryx: rename boilerplate urls

_scripts/redirects_generator/run-redirects-generator.md
Add instructions for running the redirects generator
=> Guide for the redirects generator

docs/pbc/all/search/202311.0/base-shop/best-practices/generic-faceted-search.md, docs/pbc/all/search/202311.0/base-shop/best-practices/other-best-practices.md, docs/pbc/all/search/202311.0/base-shop/best-practices/precise-search-by-super-attributes.md
=> fixing redirects in search PBC

_templates/feature-installation-guide-template.md
=> Adding notes to IG guide template

_data/sidebars/pbc_all_sidebar.yml, docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/configure-stripe.md, docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/disconnect-stripe.md, docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/install-stripe.md, docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/integrate-stripe.md, docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/stripe.md
=> ACP-773: Stripe documentation mvp

docs/scos/dev/the-docker-sdk/202204.0/configure-services.md, docs/scos/dev/the-docker-sdk/202311.0/configure-services.md
Within our online documentation, we explain how to enable our [Advanced NewRelic Integration](https://docs.spryker.com/docs/scos/dev/the-docker-sdk/202204.0/configure-services.html#new-relic) This integration depends on the spryker/eco module. 
The problem is, that the [SprykerEco NewRelic](https://github.com/spryker-eco/new-relic) module [relies on the environment property within the deploy file to set the environment within the NewRelic application](https://github.com/spryker-eco/new-relic/blob/master/src/SprykerEco/Service/NewRelic/Plugin/NewRelicMonitoringExtensionPlugin.php#L57).
Often times, our customers do not configure this value, and this means all of their environments might be named `docker`
This creates confusion and clashes within NewRelic
This PR changes the classes a …
=> Improve NewRelic Integration

_includes/pbc/all/install-features/202311.0/install-the-data-exchange-api.md, docs/pbc/all/data-exchange/202311.0/tutorials-and-howtos/how-to-send-request-in-data-exchange-api.md
https://spryker.atlassian.net/browse/FRW-6430
=> FRW-6430 Data Exchange API Complex Endpoints for POST, PUT and PATCH

docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/install-vertex/integrate-the-vertex-app.md
Tracking time ticket: https://spryker.atlassian.net/browse/ACP-344
Merge is possible w/o waiting for the whole story to be shipped or resolved.
=> Vertex: Fixed incorrect method naming for the TaxAppDependencyProvider

docs/dg/dev/upgrade-and-migrate/upgrade-to-symfony-6.md
https://spryker.atlassian.net/browse/FRW-7503
=> Changed SF to 6.4 LTS

docs/dg/dev/architecture/architectural-convention-reference.md
The dropdown boxes behave differently depending if the content is wrapped into empty lines or not. The empty lines allow to recognise the content as markdown instead of html, which was the desired format here.
=> AE-62 Fixed dropdown box style format error with empty lines

docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-macos-and-linux.md, docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-windows.md, docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-windows.md
There is a typo within the installation instructions, that instructs the user to clone the B2B code, and then to change into the directory `b2c-demo-shop`. This is incorrect
The directory that the user should change into is `b2b-demo-shop` where the code was cloned
=> Fix typo within installation instructions

docs/dg/dev/integrate-and-configure/configure-services.md
There is a bug within our instructions on how to [configure New Relic](https://docs.spryker.com/docs/dg/dev/integrate-and-configure/configure-services.html#new-relic) within the class `src/Pyz/Service/NewRelic/Plugin/NewRelicMonitoringExtensionPlugin.php` the license parameter is declared with the wrong type. Instead of `null` it should be an empty string `''`
This bug leads to a TypeError
This commit fixes the type to an empty string in line with the latest version of the [spryker-eco newrelic module](https://github.com/spryker-eco/new-relic/blob/master/src/SprykerEco/Service/NewRelic/Plugin/NewRelicMonitoringExtensionPlugin.php#L59C9-L59C61)
=> Fix newrelic_set_appname license parameter type

_includes/searching-by-logs.md, docs/ca/dev/working-with-logs.md
=> Audit Logs in AWS

_includes/pbc/all/install-features/202407.0/install-the-cart-feature.md
https://spryker.atlassian.net/browse/CC-34067
=> CC-13685: Updated product quantity and total in Mini Cart Widget from catalog AJAX add-to-cart action.

docs/dg/dev/upgrade-and-migrate/migrate-to-decoupled-glue-infrastructure/decoupled-glue-infrastructure-integrate-the-documentation-generator.md
There is a missing package in "Decoupled Glue infrastructure: Integrate the documentation generator" page. Due to this missing composer package, the documentation generation does not happen.
The code block for `DocumentationGeneratorApiDependencyProvider` requires the installation of `spryker/glue-storefront-api-application-glue-json-api-convention-connector` package.
=> Missing composer package added

docs/pbc/all/emails/202410.0/emails.md, docs/pbc/all/emails/202410.0/howto-create-and-register-a-mail-provider.md, docs/pbc/all/emails/202410.0/third-party-integrations/install-and-configure-inxmail.md, docs/pbc/all/emails/202410.0/third-party-integrations/integrate-inxmail.md, docs/pbc/all/emails/202410.0/third-party-integrations/inxmail-api-requests.md, docs/pbc/all/emails/202410.0/third-party-integrations/inxmail-order-referenced-commands.md
changed the following meta description for an SEO Update;
- emails
- how to create and register a mail provider
- third party integrations > install and configure inxmail
- third party integrations > integrate inxmail
- third party integrations > inxmail api requests
- third party integrations > inxmail order referenced commands
This is a mandatory step to make …
=> PBC Email SEO Update
